### ISSUE TITLE
Errors during publish will deadlock Visual Studio

### ISSUE THREAD

**Issue by skrysmanski** [Azure/service-fabric-issues#291] opened 2017-05-24 07:53 UTC
Certain errors while publishing or starting a Service Fabric application will make Visual Studio 2017 deadlock/hang indefinitely.

I've identified at least one way to reproduce this problem (see below) but I also observed this in other cases (but haven't tried to reproduce them).

## Reproduce
To reproduce the poblem:

1. Open a new Visual Studio 2017 instance.
1. Create a new `Service Fabric Application` project. Then choose `Stateless Service` (but I can also reproduce the bug with "ASP.NET Core"; so the other types are most likely also affected).
1. In the created solution, open `ApplicationManifest.xml`.
1. Change the name of the variable used in `<ApplicationManifest>/<DefaultServices>/<Service>/<StatelessService>/InstanceCount` to something that doesn't exist (e.g. to `[Stateless1_InstanceCount2]`).
1. Start solution with F5 (Start Debugging)

Visual Studio will now try to publish the application to the local Service Fabric cluster but will never move past the "Registering application type..." line in the build output.

![build-output](https://cloud.githubusercontent.com/assets/914747/26392214/1abd7820-4066-11e7-9a11-1590b3a9fba1.png)

## Git Repo
I've created a git repo with which I can reproduce the problem:

https://github.com/skrysmanski/bugs-service-fabric-deploy-hang

## Versions
* Visual Studio 2017 (15.2 - 26430.12)
* Service Fabric 5.6.210.9494
* Service Fabric SDK 2.6.210.9494

**Comment by Mardoxx** [comment] 2017-05-29 10:41
`7>Register-ServiceFabricApplicationType : InstanceCount has parameter 'Service1_InstanceCount2' which is unrecognized. `

**Comment by skrysmanski** [comment] 2017-05-30 09:34
@Mardoxx  How are you deploying your application? Do you hit "Publish" or do you use "Start Debugging"?

**Comment by Mardoxx** [comment] 2017-05-30 09:37
"Start debugging"

**Comment by MikkelHegn** [comment] 2017-06-05 22:06
@skrysmanski _ I also cannot reproduce this error. @dbreshears How can we get more info about what's going on?

**Comment by ravipal** [comment] 2017-06-05 23:54
@skrysmanski - I can't reproduce either. Can you please run the deployment sctipt 'J:\Sources\ERD\SFTest2\Scripts\Deploy-FabricApplication.ps1 -Application...' in a powershell session and see whether it hangs.

**Comment by skrysmanski** [comment] 2017-06-06 06:48
I've updated the initial issue with my current version infos and added a link to a git repo with which I can reproduce the problem.

**Comment by skrysmanski** [comment] 2017-06-06 06:52
@ravipal When calling the exact command that is printed onto the output panel in VS, I get an exception (as expected):

```
J:\Sources\ERD\SFRunHang (master)
λ powershell
Windows PowerShell
Copyright (C) 2016 Microsoft Corporation. All rights reserved.

PS J:\Sources\ERD\SFRunHang> . 'J:\Sources\ERD\SFRunHang\SFRunHang\Scripts\Deploy-FabricApplication.ps1' -ApplicationPackagePath 'J:\Sources\ERD\SFRunHang\SFRunHang\pkg\Debug' -PublishProfileFile 'J:\Sources\ERD\SFRunHang\SFRunHang\PublishProfiles\Local.5Node.xml' -DeployOnly:$true -ApplicationParameter:@{} -UnregisterUnusedApplicationVersionsAfterUpgrade $false -OverrideUpgradeBehavior 'None' -OverwriteBehavior 'Always' -SkipPackageValidation:$true -ErrorAction Stop
Copying application to image store...
Copy application package succeeded
Registering application type...
Register-ServiceFabricApplicationType : InstanceCount has parameter 'Stateless1_InstanceCount2' which is unrecognized. Parameters have to be defined.
FileName: C:\SfDevCluster\Data\ImageBuilderProxy\AppType\SFRunHangType\ApplicationManifest.xml
At C:\Program Files\Microsoft SDKs\Service Fabric\Tools\PSModule\ServiceFabricSDK\Publish-NewServiceFabricApplication.ps1:251 char:9
+         Register-ServiceFabricApplicationType -ApplicationPathInImage ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (Microsoft.Servi...usterConnection:ClusterConnection) [Register-ServiceFabricApplicationType], FabricException
    + FullyQualifiedErrorId : RegisterApplicationTypeErrorId,Microsoft.ServiceFabric.Powershell.RegisterApplicationType

My current speculation is that my VS installation can't work with exceptions thrown by PowerShell. But I don't know why.

```

**Comment by skrysmanski** [comment] 2017-06-06 07:00
One more thing: When VS hangs like this and I kill it, one `MSBuild` process will stay open and keep some files locked in my project folder.

I've attached a debugger to this process and created screenshots from the parallel stack and modules window. Maybe this can help?

![parallel-stacks](https://cloud.githubusercontent.com/assets/914747/26817375/98ae6fe8-4a96-11e7-8856-f80fccf17e11.png)

![modules](https://cloud.githubusercontent.com/assets/914747/26817366/944c1932-4a96-11e7-8466-0e3c8246083f.png)

**Comment by ravipal** [comment] 2017-06-07 19:39
Even with the repro project, I can't repro the hang issue. I always get the error message from powershell. Also when this error happens you should see a dialog indicating the deployment failed.
Try running "devenv /setup" from admin developers command prompt and see if this fixes the issue. If not, please attach to the hung VS process and take a process dump and share it with me (ravipal@microsoft.com).

**Comment by masnider** [comment] 2017-08-25 18:08
@skrysmanski @ravipal - any progress here?

**Comment by MikkelHegn** [comment] 2017-10-23 19:04
Closing due to no feedback

**Closed by MikkelHegn** 2017-10-23 19:04 UTC
Labels: investigating, question

**Comment by rcannizzaro** [comment] 2019-01-16 01:43
I can reproduce this if I have the StopOnFirstBuildError extension installed (https://marketplace.visualstudio.com/items?itemName=EinarEgilsson.StopOnFirstBuildError). Use v1.8 for testing. Ensure that the extension triggers by setting 'Build > Stop build on first error'.

**Comment by Jaans** [comment] 2019-04-29 07:54
> I can reproduce this if I have the StopOnFirstBuildError extension installed (https://marketplace.visualstudio.com/items?itemName=EinarEgilsson.StopOnFirstBuildError). Use v1.8 for testing. Ensure that the extension triggers by setting 'Build > Stop build on first error'.

This solved the Hang / Freeze of Visual Studio 2017 and Service Fabric Publish action.
I had a different extension (VSColorOutput) that also has a "Stop Build on First Error" option:
![image](https://user-images.githubusercontent.com/3510981/56882727-cd6bfd80-6aa7-11e9-816b-a3b4af7d7898.png)
By turning that off it stopped hanging.
