### ISSUE TITLE
Remote Registry Not Available while creating a Unsecure Standalone win2012 Cluster

### ISSUE THREAD

**Issue by juepiezhongren** [Azure/service-fabric-issues#360] opened 2017-07-21 05:59 UTC
### Below is installing log, begging for advices:
Unable to change open service manager handle because 5
Unable to change open service manager handle because 5
Unable to query service configuration because System.InvalidOperationException: Unable to change open service manager handle because 5
   在 System.Fabric.FabricDeployer.FabricDeployerServiceController.GetServiceStartupType(String machineName, String serviceName)
Unable to query service configuration because System.InvalidOperationException: Unable to change open service manager handle because 5
   在 System.Fabric.FabricDeployer.FabricDeployerServiceController.GetServiceStartupType(String machineName, String serviceName)
Querying remote registry service on machine 10.10.13.17 resulted in exception: Unable to change open service manager handle because 5.
Querying remote registry service on machine 10.10.13.18 resulted in exception: Unable to change open service manager handle because 5.
Best Practices Analyzer determined environment has an issue. Please see additional BPA log output in DeploymentTraces folder.

LocalAdminPrivilege        : True
IsJsonValid                : True
IsCabValid                 : 
RequiredPortsOpen          : True
RemoteRegistryAvailable    : False
FirewallAvailable          : 
RpcCheckPassed             : 
NoConflictingInstallations : 
FabricInstallable          : 
DataDrivesAvailable        : 
Passed                     : False

**Comment by rishirsinha** [comment] 2017-08-28 19:40
The system error code 5 in "Unable to change open service manager handle because 5" means access denied. This is caused by one of two issues 

1. The powershell window you are running is not an admin window.
2. The user you are running is not admin on the remote machines.

Please verify both and if these are not the case let us know.

**Comment by rishirsinha** [comment] 2017-09-11 18:59
@juepiezhongren, did this resolve the issue? Please let us know in a couple of weeks.

**Comment by rishirsinha** [comment] 2017-11-27 17:42
Closing because of absence or response.

**Comment by rishirsinha** [comment] 2018-08-27 17:09
Is the issue access deined (error code 5)

**Comment by suvamM** [comment] 2019-05-29 06:58
Hi, I am facing this issue as well. I've got 3 Windows 2016 server VMs, and I am trying to setup a SF cluster using them. I suspect the issue is that the admin is not the same for the 3 VMs. How do I achieve this?

**Comment by ChackDan** [comment] 2019-06-07 23:55
@maburlik @jkochhar - can one of you followup on this.

**Comment by adamsmithkld** [comment] 2019-06-21 13:03
For what it's worth I'm seeing the same error on our only unsecured cluster on Server 2016. It's preventing me from running a cluster configuration upgrade.

**Comment by MyCADDev** [comment] 2019-06-26 14:22
I'm seeing the same problem with Windows Server 2012.

**Comment by jkochhar** [comment] 2019-06-27 15:13
@MyCADDev @adamsmithkld Are you able to share deployment traces? Did you check remote registry is running service? 
Get-Service -Name RemoteRegistry

**Comment by MyCADDev** [comment] 2019-06-27 15:28
Deployment traces is below. I have xxxxxxxxxxx the application specific words

`
2019-06-25T20:00:01.3517018Z ##[section]Starting: Deploy to Platform
2019-06-25T20:00:01.3521808Z ==============================================================================
2019-06-25T20:00:01.3521882Z Task         : PowerShell
2019-06-25T20:00:01.3521993Z Description  : Run a PowerShell script
2019-06-25T20:00:01.3522039Z Version      : 1.2.3
2019-06-25T20:00:01.3522078Z Author       : Microsoft Corporation
2019-06-25T20:00:01.3522130Z Help         : [More Information](https://go.microsoft.com/fwlink/?LinkID=613736)
2019-06-25T20:00:01.3522309Z ==============================================================================
2019-06-25T20:00:01.3537344Z ##[command]. 'xxxxxxxxxxxxxxxxxxxxxxxxxxx.ps1' xxxxxxxxxxxxx xxxxxxxxxx
2019-06-25T20:00:01.9451474Z Connect to Service Fabric Cluster 171.33.84.151:19000
2019-06-25T20:00:02.3760120Z True
2019-06-25T20:00:02.4150250Z 
2019-06-25T20:00:02.4150580Z 
2019-06-25T20:00:02.4152727Z ConnectionEndpoint   : {171.33.84.151:19000}
2019-06-25T20:00:02.4153541Z FabricClientSettings : {
2019-06-25T20:00:02.4153888Z                        ClientFriendlyName                   : PowerShell-3c1b9e0c-fff4-4676-aa53-abadcdc7e7af
2019-06-25T20:00:02.4154556Z                        PartitionLocationCacheLimit          : 100000
2019-06-25T20:00:02.4155472Z                        PartitionLocationCacheBucketCount    : 1024
2019-06-25T20:00:02.4155609Z                        ServiceChangePollInterval            : 00:02:00
2019-06-25T20:00:02.4156266Z                        ConnectionInitializationTimeout      : 00:00:02
2019-06-25T20:00:02.4156889Z                        KeepAliveInterval                    : 00:00:20
2019-06-25T20:00:02.4157193Z                        ConnectionIdleTimeout                : 00:00:00
2019-06-25T20:00:02.4157879Z                        HealthOperationTimeout               : 00:02:00
2019-06-25T20:00:02.4158374Z                        HealthReportSendInterval             : 00:00:00
2019-06-25T20:00:02.4159108Z                        HealthReportRetrySendInterval        : 00:00:30
2019-06-25T20:00:02.4159466Z                        NotificationGatewayConnectionTimeout : 00:00:30
2019-06-25T20:00:02.4160092Z                        NotificationCacheUpdateTimeout       : 00:00:30
2019-06-25T20:00:02.4160587Z                        AuthTokenBufferSize                  : 4096
2019-06-25T20:00:02.4160940Z                        }
2019-06-25T20:00:02.4161657Z GatewayInformation   : {
2019-06-25T20:00:02.4162004Z                        NodeAddress                          : 10.9.2.244:19000
2019-06-25T20:00:02.4162624Z                        NodeId                               : 85772935593a0315f92e3293832c5fe9
2019-06-25T20:00:02.4162979Z                        NodeInstanceId                       : 132042120093470792
2019-06-25T20:00:02.4163645Z                        NodeName                             : xxxxxxxxxxxxxxxxxxxxxxx
2019-06-25T20:00:02.4164006Z                        }
2019-06-25T20:00:02.4164416Z 
2019-06-25T20:00:02.5442463Z xxxxxxxxxxxxxxxxxxxxx
2019-06-25T20:00:02.6136551Z Installed version is same version as we're trying to deploy, upgrade
2019-06-25T20:00:12.1205414Z Upload new version of xxxxxxxxxxxxxxxxxx to image store xxxxxxxxxxxxxxxxxxxxxxx
2019-06-25T20:00:12.2603131Z Using ImageStoreConnectionString='fabric:ImageStore'
2019-06-25T20:01:03.9420083Z Upload to Image Store succeeded
2019-06-25T20:01:03.9429589Z Register new xxxxxxxxxxxxxxx package
2019-06-25T20:01:05.8348678Z Register application type succeeded
2019-06-25T20:01:05.8354435Z Remove old package, shouldn't be there
2019-06-25T20:01:05.8771357Z Using ImageStoreConnectionString='fabric:ImageStore'
2019-06-25T20:01:06.1325576Z Remove application package succeeded
2019-06-25T20:01:06.1358564Z Shutdown
2019-06-25T20:03:06.2695569Z ##[error]xxxxxxxxxxxxxxxxxxxxxxxxxxx : System.TimeoutException: Operation timed out. ---> 
System.Runtime.InteropServices.COMException: Exception from HRESULT: 0x80071BFF
   at System.Fabric.Interop.NativeClient.IFabricApplicationManagementClient10.EndDeleteApplication2(IFabricAsyncOperati
onContext context)
   at System.Fabric.Interop.Utility.<>c__DisplayClass22_0.<WrapNativeAsyncInvoke>b__0(IFabricAsyncOperationContext 
context)
   at System.Fabric.Interop.AsyncCallOutAdapter2`1.Finish(IFabricAsyncOperationContext context, Boolean 
expectedCompletedSynchronously)
   --- End of inner exception stack trace ---
   at System.Management.Automation.MshCommandRuntime.ThrowTerminatingError(ErrorRecord errorRecord)
At line:1 char:1
+ . 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx' xxxxxxxxxxxxxxxxxxxx xxxxxxxxxxx
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,xxxxxxxxxxxxxxxxxxx
 

2019-06-25T20:03:06.3685969Z ##[error]Process completed with exit code -1 and had 1 error(s) written to the error stream.
2019-06-25T20:03:06.3689479Z ##[section]Finishing: Deploy to xxxxxxxxxxxxxx
`

**Comment by MyCADDev** [comment] 2019-06-27 15:32
@jkochhar The Remote Registry is in stopped condition. Should I start it manually?

`PS C:\Users\Administrator> Get-Service -Name RemoteRegistry

Status   Name               DisplayName
------   ----               -----------
Stopped  RemoteRegistry     Remote Registry
`

**Comment by MyCADDev** [comment] 2019-06-27 15:33
```Test```

**Comment by jkochhar** [comment] 2019-06-27 18:09
@MyCADDev Are you deploying an application?

**Comment by maburlik** [comment] 2019-06-27 18:29
@suvamM We had fixed the original issue that was mentioned in this thread in the RTO release of 6.4. We would need more details from your deployment including logs, deployed version, user configuration details, and execution context in order to investigate if you are still seeing this in 6.4+.

@MyCADDev's issue appears to be unrelated to the original issue and it's a bit unclear what specifically is timing out since it appears that this is a custom deployment script running and it's unclear which specific operation is failing. Generally timeouts are expected to happen so need to be retried, but if this is a persistent issue please provide your script, fabric ETL traces, and a bit of background for the app against which you are running your commands such as size & versioning history.

**Closed by maburlik** 2019-06-27 18:29 UTC
Labels: investigating, question

**Comment by MyCADDev** [comment] 2019-06-27 18:52
@jkochhar My deployment script is giving intermittent failure. After that I tried TestConfiguration script to see if there are any errors and I got the error mentioned i this issue. Output below.

I will try with 6.4+. as mentioned by @maburlik 

thanks

```PS C:\Users\Administrator> C:\servicefabric\TestConfiguration.ps1 -ClusterConfigFilePath C:\servicefabric\ClusterConfig.Unsecure.DevCluster.json
Trace folder already exists. Traces will be written to existing trace folder: C:\Users\Administrator\DeploymentTraces
Running Best Practices Analyzer...
Unable to change open service manager handle because Error 5: Access is denied
Unable to change open service manager handle because Error 5: Access is denied
Unable to change open service manager handle because Error 5: Access is denied
Unable to query service configuration because System.InvalidOperationException: Unable to change open service manager handle because Error 5: Access is denied
   at System.Fabric.FabricDeployer.FabricDeployerServiceController.GetServiceStartupType(String machineName, String serviceName)
Unable to query service configuration because System.InvalidOperationException: Unable to change open service manager handle because Error 5: Access is denied
   at System.Fabric.FabricDeployer.FabricDeployerServiceController.GetServiceStartupType(String machineName, String serviceName)
Unable to query service configuration because System.InvalidOperationException: Unable to change open service manager handle because Error 5: Access is denied
   at System.Fabric.FabricDeployer.FabricDeployerServiceController.GetServiceStartupType(String machineName, String serviceName)
Unable to change open service manager handle because Error 5: Access is denied
Querying remote registry service on machine 10.9.10.205 resulted in exception: Unable to change open service manager handle because Error 5: Access is denied. Iteration: 0.
Querying remote registry service on machine 10.9.18.244 resulted in exception: Unable to change open service manager handle because Error 5: Access is denied. Iteration: 0.
Querying remote registry service on machine 10.9.17.201 resulted in exception: Unable to change open service manager handle because Error 5: Access is denied. Iteration: 0.
Unable to query service configuration because System.InvalidOperationException: Unable to change open service manager handle because Error 5: Access is denied
   at System.Fabric.FabricDeployer.FabricDeployerServiceController.GetServiceStartupType(String machineName, String serviceName)
Querying remote registry service on machine 10.9.8.181 resulted in exception: Unable to change open service manager handle because Error 5: Access is denied. Iteration: 0.
Unable to change open service manager handle because Error 5: Access is denied
Unable to change open service manager handle because Error 5: Access is denied
Unable to change open service manager handle because Error 5: Access is denied
Unable to query service configuration because System.InvalidOperationException: Unable to change open service manager handle because Error 5: Access is denied
   at System.Fabric.FabricDeployer.FabricDeployerServiceController.GetServiceStartupType(String machineName, String serviceName)
Unable to query service configuration because System.InvalidOperationException: Unable to change open service manager handle because Error 5: Access is denied
   at System.Fabric.FabricDeployer.FabricDeployerServiceController.GetServiceStartupType(String machineName, String serviceName)
Querying remote registry service on machine 10.9.18.244 resulted in exception: Unable to change open service manager handle because Error 5: Access is denied. Iteration: 1.
Querying remote registry service on machine 10.9.17.201 resulted in exception: Unable to change open service manager handle because Error 5: Access is denied. Iteration: 1.
Unable to query service configuration because System.InvalidOperationException: Unable to change open service manager handle because Error 5: Access is denied
   at System.Fabric.FabricDeployer.FabricDeployerServiceController.GetServiceStartupType(String machineName, String serviceName)
Unable to change open service manager handle because Error 5: Access is denied
Querying remote registry service on machine 10.9.10.205 resulted in exception: Unable to change open service manager handle because Error 5: Access is denied. Iteration: 1.
Unable to query service configuration because System.InvalidOperationException: Unable to change open service manager handle because Error 5: Access is denied
   at System.Fabric.FabricDeployer.FabricDeployerServiceController.GetServiceStartupType(String machineName, String serviceName)
Querying remote registry service on machine 10.9.8.181 resulted in exception: Unable to change open service manager handle because Error 5: Access is denied. Iteration: 1.
Unable to change open service manager handle because Error 5: Access is denied
Unable to change open service manager handle because Error 5: Access is denied
Unable to change open service manager handle because Error 5: Access is denied
Unable to change open service manager handle because Error 5: Access is denied
Unable to query service configuration because System.InvalidOperationException: Unable to change open service manager handle because Error 5: Access is denied
   at System.Fabric.FabricDeployer.FabricDeployerServiceController.GetServiceStartupType(String machineName, String serviceName)
Unable to query service configuration because System.InvalidOperationException: Unable to change open service manager handle because Error 5: Access is denied
   at System.Fabric.FabricDeployer.FabricDeployerServiceController.GetServiceStartupType(String machineName, String serviceName)
Unable to query service configuration because System.InvalidOperationException: Unable to change open service manager handle because Error 5: Access is denied
   at System.Fabric.FabricDeployer.FabricDeployerServiceController.GetServiceStartupType(String machineName, String serviceName)
Unable to query service configuration because System.InvalidOperationException: Unable to change open service manager handle because Error 5: Access is denied
   at System.Fabric.FabricDeployer.FabricDeployerServiceController.GetServiceStartupType(String machineName, String serviceName)
Querying remote registry service on machine 10.9.17.201 resulted in exception: Unable to change open service manager handle because Error 5: Access is denied. Iteration: 2.
Querying remote registry service on machine 10.9.8.181 resulted in exception: Unable to change open service manager handle because Error 5: Access is denied. Iteration: 2.
Querying remote registry service on machine 10.9.18.244 resulted in exception: Unable to change open service manager handle because Error 5: Access is denied. Iteration: 2.
Querying remote registry service on machine 10.9.10.205 resulted in exception: Unable to change open service manager handle because Error 5: Access is denied. Iteration: 2.
Unable to change open service manager handle because Error 5: Access is denied
Unable to change open service manager handle because Error 5: Access is denied
Unable to query service configuration because System.InvalidOperationException: Unable to change open service manager handle because Error 5: Access is denied
   at System.Fabric.FabricDeployer.FabricDeployerServiceController.GetServiceStartupType(String machineName, String serviceName)
Unable to change open service manager handle because Error 5: Access is denied
Unable to query service configuration because System.InvalidOperationException: Unable to change open service manager handle because Error 5: Access is denied
   at System.Fabric.FabricDeployer.FabricDeployerServiceController.GetServiceStartupType(String machineName, String serviceName)
Querying remote registry service on machine 10.9.8.181 resulted in exception: Unable to change open service manager handle because Error 5: Access is denied. Iteration: 3.
Unable to query service configuration because System.InvalidOperationException: Unable to change open service manager handle because Error 5: Access is denied
   at System.Fabric.FabricDeployer.FabricDeployerServiceController.GetServiceStartupType(String machineName, String serviceName)
Unable to change open service manager handle because Error 5: Access is denied
Querying remote registry service on machine 10.9.10.205 resulted in exception: Unable to change open service manager handle because Error 5: Access is denied. Iteration: 3.
Unable to query service configuration because System.InvalidOperationException: Unable to change open service manager handle because Error 5: Access is denied
   at System.Fabric.FabricDeployer.FabricDeployerServiceController.GetServiceStartupType(String machineName, String serviceName)
Querying remote registry service on machine 10.9.17.201 resulted in exception: Unable to change open service manager handle because Error 5: Access is denied. Iteration: 3.
Querying remote registry service on machine 10.9.18.244 resulted in exception: Unable to change open service manager handle because Error 5: Access is denied. Iteration: 3.
Unable to change open service manager handle because Error 5: Access is denied
Unable to query service configuration because System.InvalidOperationException: Unable to change open service manager handle because Error 5: Access is denied
   at System.Fabric.FabricDeployer.FabricDeployerServiceController.GetServiceStartupType(String machineName, String serviceName)
Querying remote registry service on machine 10.9.8.181 resulted in exception: Unable to change open service manager handle because Error 5: Access is denied. Iteration: 4.
Unable to change open service manager handle because Error 5: Access is denied
Unable to change open service manager handle because Error 5: Access is denied
Unable to change open service manager handle because Error 5: Access is denied
Unable to query service configuration because System.InvalidOperationException: Unable to change open service manager handle because Error 5: Access is denied
   at System.Fabric.FabricDeployer.FabricDeployerServiceController.GetServiceStartupType(String machineName, String serviceName)
Unable to query service configuration because System.InvalidOperationException: Unable to change open service manager handle because Error 5: Access is denied
   at System.Fabric.FabricDeployer.FabricDeployerServiceController.GetServiceStartupType(String machineName, String serviceName)
Unable to query service configuration because System.InvalidOperationException: Unable to change open service manager handle because Error 5: Access is denied
   at System.Fabric.FabricDeployer.FabricDeployerServiceController.GetServiceStartupType(String machineName, String serviceName)
Querying remote registry service on machine 10.9.10.205 resulted in exception: Unable to change open service manager handle because Error 5: Access is denied. Iteration: 4.
Querying remote registry service on machine 10.9.18.244 resulted in exception: Unable to change open service manager handle because Error 5: Access is denied. Iteration: 4.
Querying remote registry service on machine 10.9.17.201 resulted in exception: Unable to change open service manager handle because Error 5: Access is denied. Iteration: 4.
Best Practices Analyzer determined environment has an issue. Please see additional BPA log output in DeploymentTraces folder.


LocalAdminPrivilege        : True
IsJsonValid                : True
IsCabValid                 :
RequiredPortsOpen          : True
RemoteRegistryAvailable    : False
FirewallAvailable          :
RpcCheckPassed             :
NoDomainController         :
NoConflictingInstallations :
FabricInstallable          :
DataDrivesAvailable        :
DrivesEnoughAvailableSpace :
IsAllOrNoneIOTDevice       :
DotNetExeInPath            :
Passed                     : False

Test Config failed with exception: System.InvalidOperationException: Best Practices Analyzer determined environment has an issue. Please see additional BPA log output in DeploymentTraces folder
   at System.Management.Automation.MshCommandRuntime.ThrowTerminatingError(ErrorRecord errorRecord)```

**Comment by jkochhar** [comment] 2019-06-28 06:37
Thanks @MyCADDev . Where are your nodes hosted? It could be NTLM is disabled that can result in 'Access Denied' errors. As @maburlik  mentioned you should try with 6.4+ and if you still hit issues open a git hub issue.

**Comment by MyCADDev** [comment] 2019-07-01 13:37
@jkochhar nodes are hosted in a Private Cloud - Windows Server 2012 VMs.
Things were working a couple of months ago. Started seeing this error when we deployed a new Cluster.

**Comment by MyCADDev** [comment] 2019-07-01 15:48
@jkochhar getting same error in 6.5.639.9590. See TestConfiguration script output below.

I will also raise a ticket internal to our organization. Need to get to bottom of this soon.

```
PS C:\Users\Administrator> C:\servicefabric\TestConfiguration.ps1 -ClusterConfigFilePath C:\servicefabric\ClusterConfig.
Unsecure.DevCluster.json
Trace folder doesn't exist. Creating trace folder: C:\Users\Administrator\DeploymentTraces
Running Best Practices Analyzer...
Diagnostics Store is not a file share. Please consider using a file share accessible from all cluster machines, collecti
ng logs in a local folder is inconvenient.
Unable to change open service manager handle because Error 5: Access is denied
Unable to change open service manager handle because Error 5: Access is denied
Unable to change open service manager handle because Error 5: Access is denied
Unable to change open service manager handle because Error 5: Access is denied
Unable to query service configuration because System.InvalidOperationException: Unable to change open service manager ha
ndle because Error 5: Access is denied
   at System.Fabric.FabricDeployer.FabricDeployerServiceController.GetServiceStartupType(String machineName, String serv
iceName)
Unable to query service configuration because System.InvalidOperationException: Unable to change open service manager ha
ndle because Error 5: Access is denied
   at System.Fabric.FabricDeployer.FabricDeployerServiceController.GetServiceStartupType(String machineName, String serv
iceName)
Unable to query service configuration because System.InvalidOperationException: Unable to change open service manager ha
ndle because Error 5: Access is denied
   at System.Fabric.FabricDeployer.FabricDeployerServiceController.GetServiceStartupType(String machineName, String serv
iceName)
Querying remote registry service on machine 10.9.26.143 resulted in exception: Unable to change open service manager han
dle because Error 5: Access is denied. Iteration: 0.
Unable to query service configuration because System.InvalidOperationException: Unable to change open service manager ha
ndle because Error 5: Access is denied
   at System.Fabric.FabricDeployer.FabricDeployerServiceController.GetServiceStartupType(String machineName, String serv
iceName)
Querying remote registry service on machine 10.9.25.33 resulted in exception: Unable to change open service manager hand
le because Error 5: Access is denied. Iteration: 0.
Querying remote registry service on machine 10.9.4.69 resulted in exception: Unable to change open service manager handl
e because Error 5: Access is denied. Iteration: 0.
Querying remote registry service on machine 10.9.33.9 resulted in exception: Unable to change open service manager handl
e because Error 5: Access is denied. Iteration: 0.
Unable to change open service manager handle because Error 5: Access is denied
Unable to query service configuration because System.InvalidOperationException: Unable to change open service manager ha
ndle because Error 5: Access is denied
   at System.Fabric.FabricDeployer.FabricDeployerServiceController.GetServiceStartupType(String machineName, String serv
iceName)
Querying remote registry service on machine 10.9.11.101 resulted in exception: Unable to change open service manager han
dle because Error 5: Access is denied. Iteration: 0.
Unable to change open service manager handle because Error 5: Access is denied
Unable to query service configuration because System.InvalidOperationException: Unable to change open service manager ha
ndle because Error 5: Access is denied
   at System.Fabric.FabricDeployer.FabricDeployerServiceController.GetServiceStartupType(String machineName, String serv
iceName)
Querying remote registry service on machine 10.9.26.143 resulted in exception: Unable to change open service manager han
dle because Error 5: Access is denied. Iteration: 1.
Unable to change open service manager handle because Error 5: Access is denied
Unable to change open service manager handle because Error 5: Access is denied
Unable to change open service manager handle because Error 5: Access is denied
Unable to query service configuration because System.InvalidOperationException: Unable to change open service manager ha
ndle because Error 5: Access is denied
   at System.Fabric.FabricDeployer.FabricDeployerServiceController.GetServiceStartupType(String machineName, String serv
iceName)
Unable to query service configuration because System.InvalidOperationException: Unable to change open service manager ha
ndle because Error 5: Access is denied
   at System.Fabric.FabricDeployer.FabricDeployerServiceController.GetServiceStartupType(String machineName, String serv
iceName)
Unable to query service configuration because System.InvalidOperationException: Unable to change open service manager ha
ndle because Error 5: Access is denied
   at System.Fabric.FabricDeployer.FabricDeployerServiceController.GetServiceStartupType(String machineName, String serv
iceName)
Querying remote registry service on machine 10.9.25.33 resulted in exception: Unable to change open service manager hand
le because Error 5: Access is denied. Iteration: 1.
Querying remote registry service on machine 10.9.33.9 resulted in exception: Unable to change open service manager handl
e because Error 5: Access is denied. Iteration: 1.
Querying remote registry service on machine 10.9.4.69 resulted in exception: Unable to change open service manager handl
e because Error 5: Access is denied. Iteration: 1.
Unable to change open service manager handle because Error 5: Access is denied
Unable to query service configuration because System.InvalidOperationException: Unable to change open service manager ha
ndle because Error 5: Access is denied
   at System.Fabric.FabricDeployer.FabricDeployerServiceController.GetServiceStartupType(String machineName, String serv
iceName)
Querying remote registry service on machine 10.9.11.101 resulted in exception: Unable to change open service manager han
dle because Error 5: Access is denied. Iteration: 1.
Unable to change open service manager handle because Error 5: Access is denied
Unable to query service configuration because System.InvalidOperationException: Unable to change open service manager ha
ndle because Error 5: Access is denied
   at System.Fabric.FabricDeployer.FabricDeployerServiceController.GetServiceStartupType(String machineName, String serv
iceName)
Querying remote registry service on machine 10.9.26.143 resulted in exception: Unable to change open service manager han
dle because Error 5: Access is denied. Iteration: 2.
Unable to change open service manager handle because Error 5: Access is denied
Unable to change open service manager handle because Error 5: Access is denied
Unable to change open service manager handle because Error 5: Access is denied
Unable to query service configuration because System.InvalidOperationException: Unable to change open service manager ha
ndle because Error 5: Access is denied
   at System.Fabric.FabricDeployer.FabricDeployerServiceController.GetServiceStartupType(String machineName, String serv
iceName)
Unable to query service configuration because System.InvalidOperationException: Unable to change open service manager ha
ndle because Error 5: Access is denied
   at System.Fabric.FabricDeployer.FabricDeployerServiceController.GetServiceStartupType(String machineName, String serv
iceName)
Unable to query service configuration because System.InvalidOperationException: Unable to change open service manager ha
ndle because Error 5: Access is denied
   at System.Fabric.FabricDeployer.FabricDeployerServiceController.GetServiceStartupType(String machineName, String serv
iceName)
Querying remote registry service on machine 10.9.33.9 resulted in exception: Unable to change open service manager handl
e because Error 5: Access is denied. Iteration: 2.
Querying remote registry service on machine 10.9.25.33 resulted in exception: Unable to change open service manager hand
le because Error 5: Access is denied. Iteration: 2.
Querying remote registry service on machine 10.9.4.69 resulted in exception: Unable to change open service manager handl
e because Error 5: Access is denied. Iteration: 2.
Unable to change open service manager handle because Error 5: Access is denied
Unable to query service configuration because System.InvalidOperationException: Unable to change open service manager ha
ndle because Error 5: Access is denied
   at System.Fabric.FabricDeployer.FabricDeployerServiceController.GetServiceStartupType(String machineName, String serv
iceName)
Querying remote registry service on machine 10.9.11.101 resulted in exception: Unable to change open service manager han
dle because Error 5: Access is denied. Iteration: 2.
Unable to change open service manager handle because Error 5: Access is denied
Unable to query service configuration because System.InvalidOperationException: Unable to change open service manager ha
ndle because Error 5: Access is denied
   at System.Fabric.FabricDeployer.FabricDeployerServiceController.GetServiceStartupType(String machineName, String serv
iceName)
Querying remote registry service on machine 10.9.26.143 resulted in exception: Unable to change open service manager han
dle because Error 5: Access is denied. Iteration: 3.
Unable to change open service manager handle because Error 5: Access is denied
Unable to query service configuration because System.InvalidOperationException: Unable to change open service manager ha
ndle because Error 5: Access is denied
   at System.Fabric.FabricDeployer.FabricDeployerServiceController.GetServiceStartupType(String machineName, String serv
iceName)
Querying remote registry service on machine 10.9.4.69 resulted in exception: Unable to change open service manager handl
e because Error 5: Access is denied. Iteration: 3.
Unable to change open service manager handle because Error 5: Access is denied
Unable to query service configuration because System.InvalidOperationException: Unable to change open service manager ha
ndle because Error 5: Access is denied
   at System.Fabric.FabricDeployer.FabricDeployerServiceController.GetServiceStartupType(String machineName, String serv
iceName)
Unable to change open service manager handle because Error 5: Access is denied
Unable to query service configuration because System.InvalidOperationException: Unable to change open service manager ha
ndle because Error 5: Access is denied
   at System.Fabric.FabricDeployer.FabricDeployerServiceController.GetServiceStartupType(String machineName, String serv
iceName)
Querying remote registry service on machine 10.9.33.9 resulted in exception: Unable to change open service manager handl
e because Error 5: Access is denied. Iteration: 3.
Querying remote registry service on machine 10.9.25.33 resulted in exception: Unable to change open service manager hand
le because Error 5: Access is denied. Iteration: 3.
Unable to change open service manager handle because Error 5: Access is denied
Unable to query service configuration because System.InvalidOperationException: Unable to change open service manager ha
ndle because Error 5: Access is denied
   at System.Fabric.FabricDeployer.FabricDeployerServiceController.GetServiceStartupType(String machineName, String serv
iceName)
Querying remote registry service on machine 10.9.11.101 resulted in exception: Unable to change open service manager han
dle because Error 5: Access is denied. Iteration: 3.
Unable to change open service manager handle because Error 5: Access is denied
Unable to query service configuration because System.InvalidOperationException: Unable to change open service manager ha
ndle because Error 5: Access is denied
   at System.Fabric.FabricDeployer.FabricDeployerServiceController.GetServiceStartupType(String machineName, String serv
iceName)
Querying remote registry service on machine 10.9.33.9 resulted in exception: Unable to change open service manager handl
e because Error 5: Access is denied. Iteration: 4.
Unable to change open service manager handle because Error 5: Access is denied
Unable to change open service manager handle because Error 5: Access is denied
Unable to change open service manager handle because Error 5: Access is denied
Unable to query service configuration because System.InvalidOperationException: Unable to change open service manager ha
ndle because Error 5: Access is denied
   at System.Fabric.FabricDeployer.FabricDeployerServiceController.GetServiceStartupType(String machineName, String serv
iceName)
Unable to query service configuration because System.InvalidOperationException: Unable to change open service manager ha
ndle because Error 5: Access is denied
   at System.Fabric.FabricDeployer.FabricDeployerServiceController.GetServiceStartupType(String machineName, String serv
iceName)
Unable to query service configuration because System.InvalidOperationException: Unable to change open service manager ha
ndle because Error 5: Access is denied
   at System.Fabric.FabricDeployer.FabricDeployerServiceController.GetServiceStartupType(String machineName, String serv
iceName)
Querying remote registry service on machine 10.9.4.69 resulted in exception: Unable to change open service manager handl
e because Error 5: Access is denied. Iteration: 4.
Querying remote registry service on machine 10.9.26.143 resulted in exception: Unable to change open service manager han
dle because Error 5: Access is denied. Iteration: 4.
Querying remote registry service on machine 10.9.25.33 resulted in exception: Unable to change open service manager hand
le because Error 5: Access is denied. Iteration: 4.
Unable to change open service manager handle because Error 5: Access is denied
Unable to query service configuration because System.InvalidOperationException: Unable to change open service manager ha
ndle because Error 5: Access is denied
   at System.Fabric.FabricDeployer.FabricDeployerServiceController.GetServiceStartupType(String machineName, String serv
iceName)
Querying remote registry service on machine 10.9.11.101 resulted in exception: Unable to change open service manager han
dle because Error 5: Access is denied. Iteration: 4.
Best Practices Analyzer determined environment has an issue. Please see additional BPA log output in DeploymentTraces fo
lder.


LocalAdminPrivilege        : True
IsJsonValid                : True
IsCabValid                 :
RequiredPortsOpen          : True
RemoteRegistryAvailable    : False
FirewallAvailable          :
RpcCheckPassed             :
NoDomainController         :
NoConflictingInstallations :
FabricInstallable          :
DataDrivesAvailable        :
DrivesEnoughAvailableSpace :
Passed                     : False

Test Config failed with exception: System.InvalidOperationException: Best Practices Analyzer determined environment has
an issue. Please see additional BPA log output in DeploymentTraces folder.
   at System.Management.Automation.MshCommandRuntime.ThrowTerminatingError(ErrorRecord errorRecord)
PS C:\Users\Administrator>```

**Comment by MyCADDev** [comment] 2019-07-01 17:49
Found the problem.

The nodes are requiring password for file sharing. There was a change in the VMs which was done by my organization. Now this passes 
```RemoteRegistryAvailable    : True```

**Comment by jkochhar** [comment] 2019-07-03 04:29
Great! Thanks for confirming @MyCADDev
