### ISSUE TITLE
Build Warning : Found conflicts between different versions of the same depenant assembly.

### ISSUE THREAD

**Issue by johnkattenhorn** [Azure/service-fabric-issues#29] opened 2016-07-14 14:28 UTC
All of the `.sfproj` project have the same complier warning in my solution.

```
Found conflicts between different versions of the same dependent assembly. Please set the "AutoGenerateBindingRedirects" property to true in the project file. For more information, see http://go.microsoft.com/fwlink/?LinkId=294190.

File: C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets
```

I see a bunch of these during the bunch as well:

`Consider app.config remapping of assembly`
And
`No way to resolve conflict between`

I've run the following `Get-Project -All | Add-BindingRedirect` but doesn't seem to help reduce these. 

Is this something to worry about ?

**Comment by mthalman-msft** [comment] 2016-07-14 14:31
No, it's nothing to worry about.  These is a bug in our MSBuild files that caused this warning to be exposed.  It will be fixed in the next release.

**Comment by johnkattenhorn** [comment] 2016-07-14 14:32
Thanks @mthalman-msft - Shall I close this ?

**Comment by mthalman-msft** [comment] 2016-07-14 14:33
Yes, go ahead.  We've got this tracked internally already.

**Comment by johnkattenhorn** [comment] 2016-07-14 14:38
No problem, a little tip I've just discovered if you want to check all the binding redirects but skip the .sfproj files then this works `get-project -all | ? {$_.Type -eq 'C#'} | add-bindingredirect`

**Comment by jahmai** [comment] 2017-04-04 07:19
This is still an issue in VS2017 RTM + Service Fabric SDK 2.4.145.9494.
When exactly was it going to be fixed?

**Comment by dbreshears** [comment] 2017-04-04 15:32
@jahmai.  I see the original issue was resolved fixed several releases ago (appears to have been 5.2 SF or SDK 2.2. I just re-verified it hasn't regressed.   If you can share some repro steps and project somewhere,   we will investigate.

**Comment by jahmai** [comment] 2017-04-04 22:13
So it is definitely happening for our projects:

11>------ Build started: Project: CriticalArc.SafeZone.Azure.Messaging.Application, Configuration: Debug x64 ------
11>D:\criticalarc\packages\Microsoft.Bcl.Build.1.0.21\build\Microsoft.Bcl.Build.targets(243,5): warning : All projects referencing CriticalArc.SafeZone.Azure.Messaging.Service.csproj must install nuget package Microsoft.Bcl.Build. For more information, see http://go.microsoft.com/fwlink/?LinkID=317569.
11>Done building project "CriticalArc.SafeZone.Azure.Messaging.Service.csproj".
11>No way to resolve conflict between "mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" and "mscorlib, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e, Retargetable=Yes". Choosing "mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" arbitrarily.
11>No way to resolve conflict between "System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" and "System.Core, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e, Retargetable=Yes". Choosing "System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" arbitrarily.
11>No way to resolve conflict between "System.ServiceModel.Web, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35" and "System.ServiceModel.Web, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e, Retargetable=Yes". Choosing "System.ServiceModel.Web, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35" arbitrarily.
11>No way to resolve conflict between "System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" and "System, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e, Retargetable=Yes". Choosing "System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" arbitrarily.

I'm just trying to get a repro going.

**Comment by jahmai** [comment] 2017-04-05 01:44
OK, attaching the simplest repro I could make. It's not exactly the same warning output but it's basically the same problem. I assume in my code I am referencing more nuget packages that cause the additional reference conflicts, but this should be enough to treat the root cause?

[Application1.zip](https://github.com/Azure/service-fabric-issues/files/894955/Application1.zip)

**Comment by dbreshears** [comment] 2017-04-11 19:31
@jahmai .  Doesn't seem to be the same issue.   It appears to be related to the an older version of SendGrid or specifically SendGrid.SmtpAPi.dll that you have referenced.   That assembly is referencing 2.0.5.0 of mscorlib and system.core.dll where other nuget packages are referencing 4.0.0.0.   I think you'll need to update the SendMail Nuget packages to avoid the conflicts.

**Comment by jahmai** [comment] 2017-04-11 22:25
@dbreshears I'm not convinced.

First of all, SendGrid.SmtpApi is a portable assembly, which references 2.0.5.0 by design. Second, this is just one of the nuget packages that causes the issue. Third, this only happens for sfproj files and not for any other project type (we can reference app(net46) -> lib(net46) -> sendgrid with no issues). Finally, why does sfproj even care about producing these warnings since it doesn't produce a binary that might have these issues anyway?

**Comment by dbreshears** [comment] 2017-04-12 15:57
@jahmai,  I see that now and didn't realize it was a portable library.    It certainly behaves differently in our .sfproj but will take a deeper dive into our MSbuild logic and Microsoft.Common.targets where the warning is coming from.   I logged a bug for us to investigate.

**Comment by ravipal** [comment] 2017-05-26 00:47
Please add the following target to *.sfproj. That should fix the conflict error.
  \<Target Name="ResolveReferences"/\>

**Comment by jahmai** [comment] 2017-05-26 00:57
@ravipal Yep, that fixes it!

**Comment by jahmai** [comment] 2017-05-26 04:13
@ravipal Actually, while this does suppress the warning, it actually breaks compiling from a fresh check-out because it no longer compiles it's service project dependencies...

**Comment by ravipal** [comment] 2017-05-30 21:17
@jahmai - what do you mean by "it no longer compiles it's service project dependencies...". Say if you have an application A with service S that references a class library project L. If you build A, are you saying it doesn't build L?

**Comment by jahmai** [comment] 2017-05-31 04:10
@ravipal Simpler than that, application A references service S, and building application A no longer builds service S.

**Comment by ravipal** [comment] 2017-05-31 19:35
@jahmai, I tried with the sample project that you attached 'Application1' as well as the other sample project and can't repro build issue. I can still build and package without any issue. Building the application builds all services. Can you please share the project where you see this issue. If it is too large to attach, please send it to ravipal@microsoft.com

**Comment by jahmai** [comment] 2017-06-01 01:25
@ravipal Are you using MSBuild and specifying the Package target?

> C:\Users\Jahmai\Downloads\Application1\Application1>msbuild Application1.sfproj /target:Package
> Microsoft (R) Build Engine version 15.1.1012.6693
> Copyright (C) Microsoft Corporation. All rights reserved.
> 
> Build started 1/06/2017 11:24:25 AM.
> Project "C:\Users\Jahmai\Downloads\Application1\Application1\Application1.sfproj" on node 1 (Package target(s)).
> PrepareForBuild:
>   Creating directory "bin\Debug\".
>   Creating directory "obj\x64\Debug\".
> _CopyAppConfigFile:
>   Copying file from "app.config" to "bin\Debug\Application1.config".
> FixUpServiceFabricApplicationManifest:
>   "C:\Program Files\Microsoft SDKs\Service Fabric\\Tools\AppManifestCleanupUtil\AppManifestCleanupUtil.exe" /amp:"C:\Us
>   ers\Jahmai\Downloads\Application1\Application1\ApplicationPackageRoot\ApplicationManifest.xml" /smpl:"C:\Users\Jahmai
>   \Downloads\Application1\Stateless1\PackageRoot\ServiceManifest.xml" /appparamfiles:"C:\Users\Jahmai\Downloads\Applica
>   tion1\Application1\ApplicationParameters\Cloud.xml;C:\Users\Jahmai\Downloads\Application1\Application1\ApplicationPar
>   ameters\Local.1Node.xml;C:\Users\Jahmai\Downloads\Application1\Application1\ApplicationParameters\Local.5Node.xml"
> Project "C:\Users\Jahmai\Downloads\Application1\Application1\Application1.sfproj" (1) is building "C:\Users\Jahmai\Down
> loads\Application1\Stateless1\Stateless1.csproj" (2:4) on node 1 (BuiltProjectOutputGroup;DebugSymbolsProjectOutputGrou
> p;DocumentationProjectOutputGroup;SatelliteDllsProjectOutputGroup;SGenFilesOutputGroup target(s)).
> PrepareForBuild:
>   Creating directory "bin\x64\Debug\".
>   Creating directory "obj\x64\Debug\".
> Done Building Project "C:\Users\Jahmai\Downloads\Application1\Stateless1\Stateless1.csproj" (BuiltProjectOutputGroup;De
> bugSymbolsProjectOutputGroup;DocumentationProjectOutputGroup;SatelliteDllsProjectOutputGroup;SGenFilesOutputGroup targe
> t(s)).
> 
> Project "C:\Users\Jahmai\Downloads\Application1\Application1\Application1.sfproj" (1) is building "C:\Users\Jahmai\Down
> loads\Application1\Stateless1\Stateless1.csproj" (2:6) on node 1 (BuiltProjectOutputGroupDependencies;DebugSymbolsProje
> ctOutputGroupDependencies;DocumentationProjectOutputGroupDependencies;SGenFilesOutputGroupDependencies target(s)).
> GenerateBindingRedirects:
>   No suggested binding redirects from ResolveAssemblyReferences.
> Done Building Project "C:\Users\Jahmai\Downloads\Application1\Stateless1\Stateless1.csproj" (BuiltProjectOutputGroupDep
> endencies;DebugSymbolsProjectOutputGroupDependencies;DocumentationProjectOutputGroupDependencies;SGenFilesOutputGroupDe
> pendencies target(s)).
> 
> PackageServices:
>   Creating directory "C:\Users\Jahmai\Downloads\Application1\Application1\pkg\Debug\Stateless1Pkg\Config".
>   Copying file from "C:\Users\Jahmai\Downloads\Application1\Stateless1\PackageRoot\Config\Settings.xml" to "C:\Users\Ja
>   hmai\Downloads\Application1\Application1\pkg\Debug\Stateless1Pkg\Config\Settings.xml".
>   Copying file from "C:\Users\Jahmai\Downloads\Application1\Stateless1\PackageRoot\ServiceManifest.xml" to "C:\Users\Ja
>   hmai\Downloads\Application1\Application1\pkg\Debug\Stateless1Pkg\ServiceManifest.xml".
> C:\Users\Jahmai\Downloads\Application1\packages\Microsoft.VisualStudio.Azure.Fabric.MSBuild.1.6.0\build\Microsoft.Visua
> lStudio.Azure.Fabric.Application.targets(248,5): error MSB3030: Could not copy the file "C:\Users\Jahmai\Downloads\Appl
> ication1\Stateless1\obj\x64\Debug\Stateless1.exe" because it was not found. [C:\Users\Jahmai\Downloads\Application1\App
> lication1\Application1.sfproj]
>   Creating directory "C:\Users\Jahmai\Downloads\Application1\Application1\pkg\Debug\Stateless1Pkg\Code".
>   Copying file from "C:\Users\Jahmai\Downloads\Application1\Stateless1\App.config" to "C:\Users\Jahmai\Downloads\Applic
>   ation1\Application1\pkg\Debug\Stateless1Pkg\Code\Stateless1.exe.config".
> C:\Users\Jahmai\Downloads\Application1\packages\Microsoft.VisualStudio.Azure.Fabric.MSBuild.1.6.0\build\Microsoft.Visua
> lStudio.Azure.Fabric.Application.targets(248,5): error MSB3030: Could not copy the file "C:\Users\Jahmai\Downloads\Appl
> ication1\Stateless1\obj\x64\Debug\Stateless1.pdb" because it was not found. [C:\Users\Jahmai\Downloads\Application1\App
> lication1\Application1.sfproj]
> C:\Users\Jahmai\Downloads\Application1\packages\Microsoft.VisualStudio.Azure.Fabric.MSBuild.1.6.0\build\Microsoft.Visua
> lStudio.Azure.Fabric.Application.targets(248,5): error MSB3030: Could not copy the file "C:\Users\Jahmai\Downloads\Appl
> ication1\Stateless1\bin\x64\Debug\Stateless1.exe.config" because it was not found. [C:\Users\Jahmai\Downloads\Applicati
> on1\Application1\Application1.sfproj]
> Done Building Project "C:\Users\Jahmai\Downloads\Application1\Application1\Application1.sfproj" (Package target(s)) --
> FAILED.
> 
> 
> Build FAILED.
> 
> "C:\Users\Jahmai\Downloads\Application1\Application1\Application1.sfproj" (Package target) (1) ->
> (PackageServices target) ->
>   C:\Users\Jahmai\Downloads\Application1\packages\Microsoft.VisualStudio.Azure.Fabric.MSBuild.1.6.0\build\Microsoft.Vis
> ualStudio.Azure.Fabric.Application.targets(248,5): error MSB3030: Could not copy the file "C:\Users\Jahmai\Downloads\Ap
> plication1\Stateless1\obj\x64\Debug\Stateless1.exe" because it was not found. [C:\Users\Jahmai\Downloads\Application1\A
> pplication1\Application1.sfproj]
>   C:\Users\Jahmai\Downloads\Application1\packages\Microsoft.VisualStudio.Azure.Fabric.MSBuild.1.6.0\build\Microsoft.Vis
> ualStudio.Azure.Fabric.Application.targets(248,5): error MSB3030: Could not copy the file "C:\Users\Jahmai\Downloads\Ap
> plication1\Stateless1\obj\x64\Debug\Stateless1.pdb" because it was not found. [C:\Users\Jahmai\Downloads\Application1\A
> pplication1\Application1.sfproj]
>   C:\Users\Jahmai\Downloads\Application1\packages\Microsoft.VisualStudio.Azure.Fabric.MSBuild.1.6.0\build\Microsoft.Vis
> ualStudio.Azure.Fabric.Application.targets(248,5): error MSB3030: Could not copy the file "C:\Users\Jahmai\Downloads\Ap
> plication1\Stateless1\bin\x64\Debug\Stateless1.exe.config" because it was not found. [C:\Users\Jahmai\Downloads\Applica
> tion1\Application1\Application1.sfproj]
> 
>     0 Warning(s)
>     3 Error(s)
> 
> Time Elapsed 00:00:01.19
> 
> C:\Users\Jahmai\Downloads\Application1\Application1>

**Comment by ravipal** [comment] 2017-06-01 19:21
I see the issue with MSBuild. Please add <Target Name="ResolveAssemblyReferences" /> to *.sfproj. This will skip this target for *.sfproj.

**Comment by jahmai** [comment] 2017-06-02 05:53
@ravipal Bingo, that fixed both the warnings, and it still compiles and packages :)

**Comment by dbreshears** [comment] 2017-06-05 21:49
@jahmai.   Thank you for the confirmation.   Closing this as we will fix this in our next update of the tooling

**Closed by dbreshears** 2017-06-05 21:49 UTC
Labels: bug, investigating

**Comment by pamela032709** [comment] 2018-06-08 23:19
can someone tell me where exactly should I add this fix in my project -- <Target Name="ResolveAssemblyReferences" />
thank you

**Comment by ashishnegi** [comment] 2018-06-10 16:18
@pamela032709 check [comment1](https://github.com/Azure/service-fabric-issues/issues/29#issuecomment-304161827) and [comment2](https://github.com/Azure/service-fabric-issues/issues/29#issuecomment-305594089).
