### ISSUE TITLE
“There is an error in XML document” publishing an Upgrade

### ISSUE THREAD

**Issue by CassandraDied** [Azure/service-fabric-issues#111] opened 2016-12-22 11:01 UTC
I'm trying to make an upgrade of the app and getting the next error in Output window:

`1>------ Build started: Project: Company.Project.Fabric, Configuration: Debug x64 ------
2>------ Publish started: Project: Company.Project.Fabric, Configuration: Debug x64 ------
2>There is an error in XML document (0, 0).
========== Build: 1 succeeded, 0 failed, 59 up-to-date, 0 skipped ==========
========== Publish: 0 succeeded, 1 failed, 0 skipped ==========`

This issue is sporadic and unfortunately I didn't figure out what triggers this behavior. Sometimes I just need to wait some time and the error is gone, sometimes I'm just constantly building the fabric project and the issue is gone as well.

I'm almost 100% sure that ApplicationManifest.xml, ServiceManifest.xml and other xml files are correct and resulting manifest file is correct as well. And publishing through PowerShell console is working well.

The only suspicious thing that I mentioned was that after each build of the SF project I can see that the same projects are built again and again. I mean, normally I would expect something like this after the second build(not a rebuild and code isn't changed):
`========== Build: 1 succeeded, 0 failed, 59 up-to-date, 0 skipped ==========`
But sometimes I can see the same projects built and succeeded count isn't 1. Not sure that this is related though: once I got expected amount of build projects and still got XML error.

**Comment by ravipal** [comment] 2016-12-22 19:25
I assume you are using 1.3 version of VS tooling. This issue is fixed in 1.4 version of Service Fabric Tools for Visual Studio.

**Comment by CassandraDied** [comment] 2016-12-26 08:54
I'm facing this issue in 1.4 version as well.
![sf_version](https://cloud.githubusercontent.com/assets/2866070/21478981/ffbfeb30-cb61-11e6-84a9-b57d8c8e46dc.png)

**Comment by karolz-ms** [comment] 2016-12-28 18:46
How big is your application, how many services?

Can you double-check and report the version of Microsoft.VisualStudio.Azure.Fabric.Shared.dll? It should be located under <your VS installation directory>\Common7\IDE\Extensions\Microsoft\Service Fabric Tools. The version should be 1.4.41209.1

**Comment by CassandraDied** [comment] 2016-12-29 08:32
23 services: 9 statefull and 14 stateless.
![sf_dll](https://cloud.githubusercontent.com/assets/2866070/21539720/6fe78f76-cdba-11e6-878a-5a1af97778fe.png)

**Comment by karolz-ms** [comment] 2016-12-29 16:14
How long does it take, approximately, from the moment you see the "Publish started" message to the moment you see "the error in XML document (0,0)" message?

Any chance to have the application (or similar application that exhibits the same issue) with us?

**Comment by CassandraDied** [comment] 2016-12-29 16:20
> How long does it take, approximately

Almost instantly. Less than second.

> Any chance to have the application (or similar application that exhibits the same issue) with us?

I'll try to prepare demo app removing everything from the solution, leaving only empty services, but not sure that it is possible.

**Comment by karolz-ms** [comment] 2016-12-29 16:33
OK, really appreciate your help Chack. 

Looks like we have a new issue, different from the (hopefully fixed) issue that @ravipal mentioned above :-( 

If you can get us a repro, awesome. If not, just let me know, that is helpful too.

**Comment by moosat** [comment] 2017-01-02 09:09
Facing with the same issue, when upgrading to local cluster

**Comment by karolz-ms** [comment] 2017-01-03 16:48
No repro here so solution or workaround at this point, sorry. If you can share your project, that would be very helpful. In the meantime I will try to do some poking around.

Just a sanity check: I assume the issue does not go away if you "Reset Local Cluster" via Fabric Local Cluster Manager?

**Comment by moosat** [comment] 2017-01-03 16:53
Nop

Regards,
Moshe Taieb

‫ב-3 בינו׳ 2017, בשעה 18:48, ‏‏Karol Zadora-Przylecki ‏<notifications@github.com> כתב/ה:‬

**Comment by karolz-ms** [comment] 2017-01-03 17:13
Are you using 1-node or 5-node cluster?

**Comment by karolz-ms** [comment] 2017-01-03 18:37
I was able to reproduce the problem and I am working on a fix. We'll include it in the next tooling release.

I do not think there is a workaround to this issue (other than not doing an upgrade or doing the upgrade outside of VS, via PowerShell)

**Comment by moosat** [comment] 2017-01-03 20:09
Local 1 Node

**Comment by karolz-ms** [comment] 2017-01-04 17:09
Thanks. I do not think the type of the cluster actually matters.

This issue will be fixed in the 1.5 release of the SDK & tools

**Comment by cyclomaticsegal** [comment] 2017-04-25 23:23
How far off is this from being resolved? I am all of sudden facing the same issue? Upgrades will not deploy to any environment, local or otherwise... only completely blowing away the cluster will work now.

**Comment by karolz-ms** [comment] 2017-04-26 16:19
Yup, the fix has been included in the 1.5 release. Feel free to reopen if it still affects you, hopefully not.

**Closed by karolz-ms** 2017-04-26 16:19 UTC

**Comment by asifshiraz** [comment] 2017-06-06 18:11
I am still seeing this issue in VS 2017 Version 15.2 (26430.6) and Microsoft.VisualStudio.Azure.Fabric.Shared.dll version 1.5.50311.1

**Comment by karolz-ms** [comment] 2017-06-06 19:54
@asifshiraz Would it be possible to confirm the problem also repros with the latest release of Fabric tools (2.6.210)?

**Comment by asifshiraz** [comment] 2017-06-07 06:26
I am on 2.6.210.

I have narrowed it down though. I had an my parameters defined incorrectly. However, if the parameters were defined incorrectly, it should still have indicated a more meaningful error message, instead of showing this generic error in XML document.

**Comment by karolz-ms** [comment] 2017-06-07 17:02
That is fair, we should try to improve the error message. Can you give us an example of incorrect configuration that would cause it?
