### ISSUE TITLE
Stateful Service high and increasing CPU usage

### ISSUE THREAD

**Issue by ahofman** [Azure/service-fabric-issues#1341] opened 2018-11-02 05:26 UTC
This issue appears very similar to #1239 .

We have a set of queue processors that are implemented as stateful microservices. These queue processors use a Reliable Dictionary as the queue. Messages are added to the dictionary via RPC, and long-running tasks inside the service consume and delete messages from the Reliable Dictionary.

We have noticed that these services seem to steadily increase in CPU usage over time. We see the following pattern:

- When the service starts, idle CPU is very low
- Messages are added and processing happens; CPU increases
- Processing completes, CPU goes back down, but is slightly higher than the idle CPU before the processing happened

When we leave the service for a long period of time, we notice that the "idle" CPU continues to increase. In some cases it hits 150% (i.e, 1.5 full CPU cores) even when no application processing is taking place. 

We see this behaviour in local SF clusters with 1 node and Azure based SF clusters with many nodes and many partitions.

We have produced a minimal Service Fabric solution that reproduces the problem. This solution has 1 stateful service with 1 Reliable Dictionary. One long running task continuously "consumes" items from the dictionary, and another long running task adds messages to the dictionary every 60 seconds. The sample is attached here: 
[SF_CPU_Repro.zip](https://github.com/Azure/service-fabric-issues/files/2541155/SF_CPU_Repro.zip)

We see the following trend in CPU usage when running this sample:
![image](https://user-images.githubusercontent.com/1689712/47895057-54099e80-deba-11e8-9b39-fc2892fc2037.png)
The idle CPU continues to increase over time.

When we attach a debugger to profile the sample, it shows the following as a hot spot:
![image](https://user-images.githubusercontent.com/1689712/47895111-a77bec80-deba-11e8-9a08-f0b5daadbb25.png)

It looks as though all the CPU time is spent in Service Fabric internals around iterating the dictionary.

Per suggestions in #1239, we checked the sequence numbers in the replica details:
![image](https://user-images.githubusercontent.com/1689712/47895167-ffb2ee80-deba-11e8-9f8b-5a6951152665.png)

These values increase over time, but each field (Completed Sequence Number, Committed Sequence Number and Last Sequence Number) always has the same value at any given time.

**Ideally there would be minimal CPU usage overhead when traversing the empty dictionary.**

**Comment by zuhairp** [comment] 2018-11-26 20:06
Thanks for the repro! The high CPU usage is due to an intersection of two known issues, both of which we are addressing in an upcoming release. 

The first issue is that enumeration has known perf issues which we are fixing. The internal implementation of enumeration is then made worse by how we clean up the tombstones of deleted keys. We clean up the tombstone records at a set size interval - since these are small, there can be tens of thousands of these tombstones before they are removed. We are adding a fix to more eagerly clean up the tombstones. 

As a workaround, I decreased the [CheckpointThresholdInMB](https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-reliable-services-configuration#configuration-names-1) to 1 (it defaults to 50) for the repro's service, and CPU usage decreased to consistently less than 10% (except when the add task adds keys), often around 0%. That threshold setting indirectly controls how often the cleanup occurs, among other things.

**Comment by MedAnd** [comment] 2018-12-01 10:32
Hi @zuhairp,

Is this the relevant fix for above Reliable Dictionary and Reliable Queue in the 6.4 Release notes:

- After  a full copy, the copied state on the secondary is now recovered on EndSettingCurrentState. Previously, the copy state was being recovered on the first checkpoint or apply (whichever came first). Expected impact is that copy will take slightly longer since EndSettingCurrentState will be doing work - before it was doing nothing. With this change, the first checkpoint or apply will be significantly faster which should help replica health.

**Comment by bhalbright** [comment] 2018-12-06 15:37
> As a workaround, I decreased the [CheckpointThresholdInMB](https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-reliable-services-configuration#configuration-names-1) to 1 (it defaults to 50) for the repro's service, and CPU usage decreased to consistently less than 10% (except when the add task adds keys), often around 0%. That threshold setting indirectly controls how often the cleanup occurs, among other things.

I'm a service fabric beginner so please forgive if this is a dumb question, but it is possible to update the "CheckpointThresholdInMB" config at runtime or can it only be done via an upgrade of the application?

**Comment by zuhairp** [comment] 2018-12-06 19:01
It can't be changed at runtime. Only through upgrade

**Comment by masnider** [comment] 2019-05-09 23:01
This issue has been root caused and the fix checked in. The fix is included in the forthcoming Service Fabric Runtime 6.5 release, which is _currently_ scheduled to start rolling out near the end of this month. That date could always move based on testing and feedback from canary rollouts, but it is the current target.

**Comment by zuhairp** [comment] 2019-06-13 17:34
Service Fabric Runtime 6.5 has been released, and includes the fixes for the issue seen here

**Closed by zuhairp** 2019-06-13 17:34 UTC
Labels: bug, fix coming, question
