### ISSUE TITLE
Unable to resolve service DNS name

### ISSUE THREAD

**Issue by KristofferBerge** [Azure/service-fabric-issues#332] opened 2017-06-28 08:36 UTC
I'm having trouble communicating between two services in my local cluster using DNS name as I explain in this post on stackoverflow: https://stackoverflow.com/questions/44723374/cant-communicate-with-service-using-dns-in-service-fabric

I'm trying to follow this tutorial where it seems pretty simple to do this: https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-dnsservice

The DNS service seems to be running and the application I'm trying to reach shows it's DNS name in the service fabric explorer. But when I do a http get request (from one service to the other) using the DNS name I get an exception saying that 'The remote name could not be resolved'. The request succeeds if I replace the DNS name with localhost. Both services are running in the same local cluster and I'm able to reach both services using postman.

    using(var client = new HttpClient()) {
        //This works
        var response = await client.GetAsync("http://localhost:8770/api/values");

        //This throws an error
        //var response = await client.GetAsync("http://SocketService.TimeSeriesActorApplication:8770/api/values");
    }

**Comment by jrouaix** [comment] 2017-07-10 12:08
Hello @KristofferBerge, i have also pretty weird behavior in the new version of service fabric. I try to locate a RabbitMq on docker on my same machine ... doesn't working when using localhost but working when using 127.0.0.1.
I just assume here that the new DNS service is not wired to enable access to localhost and doesn't resolve it.
So you'll get rid of that just by replacing localhost by 127.0.0.1 or perhaps the internal DNS name of your service running on the same cluster (but didn't try it yet).

**Comment by xaostation** [comment] 2017-08-09 15:25
Was this ever resolved?  I'm having the same issue as KristofferBerge.

**Comment by asifshiraz** [comment] 2017-09-11 18:02
I'm seeing the same issue. Looking forward to finding a resolution.

**Comment by thakursagar** [comment] 2017-09-11 18:54
I'm seeing the same problem too... sometimes it works fine but then it will start giving these errors.. i even tried flushing my dns but no luck.

**Comment by asifshiraz** [comment] 2017-09-12 05:26
If I do `fabricClient.PropertyManager.GetPropertyAsync(name, serviceDnsName).Result;` then I can see the property returned, but it is in Binary. As a workaround, I can manually resolve the dns name and then use in my HttpClient, would that work? But in that case, I'm not sure how to decode the binary Value.

**Comment by mani-ramaswamy** [comment] 2017-09-12 18:26
+Milan.

**Comment by milvuko** [comment] 2017-09-12 18:53
The issue you are seeing is most probably cause by the environment error. DnsService must be set as the first DNS server in the DNS server chain in order for DNS name resolve to work. Service Fabric Explorer displays a warning on the DnsService if that is not the case. Another way to check if DnsService is set as the first DNS server on the Windows box is to invoke "ipconfig /all" from the command line and verify that the local IP address is the first IP address in the DNS Servers chain. In case the local IP address is not the first one in the chain, please try to restart FabricHost.exe process, it should fix the issue.
Note that there is a known issue on Windows OS where DNS settings set by Service Fabric take roughly 10 min to get applied even though the DnsService is set as the primary DNS. After that initial delay DNS resolve starts working as expected. The bug is getting fixed in the next release of Service Fabric.

If the above doesn't fix the issue you are seeing, you can try flushing the Windows DNS cache by invoking "ipconfig /flushdns". Windows OS does negative DNS caching. This is disabled by Service Fabric once it is launched so it shouldn't cause issues, but it is worth trying.

Minor note, although it is probably not the cause for the problem you are seeing: service has to expose a valid endpoint (IPv4 address) in order for DNS resolve to work for that service.

**Comment by TravisTroyer** [comment] 2017-10-03 14:09
I seem to be experiencing this same issue on version 6.0.211.9494, both locally and in Azure.

What's interesting is that nslookup against 127.0.0.1 returns an empty result for my hostname, rather than a non-existent domain error.

Result with my service DNS name:
```
>nslookup services1.application1.local 127.0.0.1
Server:  localhost
Address:  127.0.0.1

Name:    services1.application1.local
```

Result with bogus name:
```
>nslookup doesnotexist.local 127.0.0.1
Server:  localhost
Address:  127.0.0.1

*** localhost can't find doesnotexist.local: Non-existent domain
```

Result with working domain name:
```
>nslookup azure.microsoft.com 127.0.0.1
Server:  localhost
Address:  127.0.0.1

Non-authoritative answer:
Name:    waws-prod-bn1-003.cloudapp.net
Address:  191.236.192.121
Aliases:  azure.microsoft.com
          azure.microsoft.com.nsatc.net
          acom-prod-useast2-01.azurewebsites.net
          waws-prod-bn1-003.vip.azurewebsites.windows.net
```

It appears as if the Service Fabric DNS service knows about my hostname, but doesn't return an IP address.

**Comment by milvuko** [comment] 2017-10-03 16:58
@TravisTroyer can you please verify that the service is exposing an endpoint? 
For example, a stateless service should have  a non-trivial CreateServiceInstanceListeners method implementation.

Also, the following powershell command should return non-empty endpoint set:
Resolve-ServiceFabricService -PartitionKindSingleton -ServiceName fabric:/name_of_the_service

Output of the following command would be useful as well. 
nslookup -type=any services1.application1.local 127.0.0.1

**Comment by TravisTroyer** [comment] 2017-10-03 17:25
@milvuko I realized I was standing up my own ICommunicationListener implementation and returning it from the createCommunicationListener callback for the ServiceInstanceListener.  This was all to stand-up and self-host OWIN.

It all started working once I swapped out my ICommunicationListener implementation for the IServiceRemotingListener returned from ServiceRemotingExtensions.CreateServiceRemotingListener, as demonstrated in the service remoting documentation.

I'm not sure whether we'd ever expect this scenario to work, but I can find a way to workaround if DNS just isn't supported from custom ICommunicationListener implementations (probably dependent on the internals of that implementation?).

In case it's still at all helpful, here's my nslookup output:
```
>nslookup -type=any services1.application1.local 127.0.0.1
Server:  localhost
Address:  127.0.0.1

services1.application1.local    text =

        "http://+:80/api/event-store/;https://+:443/api/event-store/"
services1.application1.local    SRV service location:
          priority       = 0
          weight         = 0
          port           = 80
          svr hostname   = +
(root)  ??? unknown type 41 ???
```

**Comment by milvuko** [comment] 2017-10-03 17:40
@TravisTroyer Thanks, custom ICommunicationListener is definitely supported. However, in order for meaningful endpoint to be exposed, you have to make sure that "+" in the URL is replaced by IP address of FQDN when ICommunicationListener.OpenAsync returns. 
```
        Task<string> ICommunicationListener.OpenAsync(CancellationToken cancellationToken)
        {
                string uri = "http://+:80/api/event-store";
              
                // Start the actual HTTP listener

                // Publish the address - replace wildcard with actual IP address
                string publishAddress = uri.Replace("+", this.Context.NodeContext.IPAddressOrFQDN);
                return Task.FromResult(publishAddress);
        }
```

**Comment by TravisTroyer** [comment] 2017-10-03 17:46
@milvuko That definitely fixed my issue.  Thank you!

**Closed** 2017-11-09 06:03 UTC
Labels: investigating

**Comment by andradf** [comment] 2018-03-14 18:40
For anyone still having similar issues, make sure your Service DNS Name has at least one period in it. service1 won't work as opposed to service1.app1 which will.
