### ISSUE TITLE
Exported certificate is invalid (Container)

### ISSUE THREAD

**Issue by Abdruggi** [Azure/service-fabric-issues#448] opened 2017-09-11 14:54 UTC
Service fabric exports the certificate and provides the environment variable. Unfortunately, the exported pfx is invalid. I am able to manually export and reimport the certificate. Therefore, the problem must be service fabric related.

**Comment by rakshitatandon** [comment] 2017-09-11 19:07
Can share details about why the pfx is invalid ? Is there an error generated ? It should be present inside the work folder of your application on your host. Are you able to load it from there ?

**Comment by Abdruggi** [comment] 2017-09-11 19:32
The cert and password files are present. No, the cert inside the host work folder is corrupt/invalid. Manual import fails with following error: “This file is invalid for use as the following: Personal information exchange”.

The behavior is wired. We have currently two applications (kestrel/dotnet) running on our cluster. One app (App A) is working like a charm, but the other (App B) doesn’t. The startup code is the same (cert import).

I first thought the cert in the host cert store might be corrupt. But manual export and reimport works. Using the App A certificate in App B causes the same error.

**Comment by rakshitatandon** [comment] 2017-09-11 19:38
Is App A also exposing a certificate inside the container ? That certificate works but the cert for App B doesn't ? Is there some specific difference between the type of cert used by App A vs App B ?

**Comment by Abdruggi** [comment] 2017-09-11 19:40
:NET Exception:

Unhandled Exception: System.Security.Cryptography.CryptographicException: Cannot find the requested object.
at System.Security.Cryptography.CryptographicException.ThrowCryptographicException(Int32 hr)
at System.Security.Cryptography.X509Certificates.X509Utils._QueryCertFileType(String fileName)
at System.Security.Cryptography.X509Certificates.X509Certificate.LoadCertificateFromFile(String fileName, Object password, X509KeyStorageFlags keyStorageFlags)
at System.Security.Cryptography.X509Certificates.X509Certificate2..ctor(String fileName, String password, X509KeyStorageFlags keyStorageFlags) " "   at System.Security.Cryptography.X509Certificates.X509Certificate2..ctor(String fileName, String password, X509KeyStorageFlags keyStorageFlags)

**Comment by rakshitatandon** [comment] 2017-09-11 19:44
The exception looks like it is unable to find the certificate at the path passed in by fileName. Does the certificate exist at the corresponding path ?

**Comment by Abdruggi** [comment] 2017-09-11 19:45
Yes, both app's are exposing a cert inside the container. App A works with Cert A (did not try to use Cert B. Will do it tomorrow). App B doesn't work with either of them.

**Comment by Abdruggi** [comment] 2017-09-11 19:51
The file must be present. Otherwise, setting the necessary acl's before importing it would fail.
```
var acl = File.GetAccessControl(filePath);
acl.AddAccessRule(new FileSystemAccessRule(Environment.UserName, FileSystemRights.Read, AccessControlType.Allow));
File.SetAccessControl(filePath, acl);
```

By default, the cert is just readable by the system user. Granting read rights to the process user is required.

**Comment by rakshitatandon** [comment] 2017-09-11 19:54
Could you send traces from your cluster to ratando@microsoft.com. I can help take a look.
As an experiment, can you try copying over Cert A pfx/password to App B's work store and try loading it from within your application ? This is to verify that App B is doing everything correct. It should work given that App A is also working with the same cert.

**Comment by Abdruggi** [comment] 2017-09-11 19:59
Thx for your help. Will do it tomorrow when i am back in the office. It's 10pm where i live:-)

Could it be some kind of a timing problem like the cert export is not done before container startup?

**Comment by rakshitatandon** [comment] 2017-09-11 20:12
Sure no problems. Certificates are exported as part of container bootstrapping so if your container is up, then it should have the necessary certificates exported. You can do a docker ps -a to see if the container is up. You can even trying doing docker exec -it [containerId] cmd.exe which will open a new command prompt inside your container. cd into the path pointed by the environment variable and check if the certificate is present there.
You may also check the exported PFX files on the host. If you do see them there and are not able to manually export them to store, then there is some issue with the generated PFX file. Traces can help figure out why the PFX wasn't generated properly.

**Comment by Abdruggi** [comment] 2017-09-12 15:32
I need another day to collect the logs. We are currently rebuilding our test cluster from scratch to make sure the source of the problem is not infrastructure related.

**Comment by rakshitatandon** [comment] 2017-09-12 18:05
Sure. Can you also ensure that your certificate is present in "LocalMachine" and the correct StoreName is passed in the application manifest. The default is "My".

**Comment by Abdruggi** [comment] 2017-09-13 17:00
After further testing I am able to provide more information. We have a testing cluster with two apps running (App1 with Cert1 and App2 with Cert2). Both certificates are in the same store (Localmachine/My) and access is granted to Network Service. The private key is marked exportable on both certificates. During testing, I just replaced the thumbprint in the applicationmanifest.xml.

App1 with Cert1: OK
App1 with Cert2: Exported certificate is invalid
App2 with Cert1: OK
App2 with Cert2: Exported certificate is invalid

Both certificates in the host certificate store are perfectly fine. Manual export and reimport works. 
It look like service fabric is having problems with one of the certificates. Which logs do you need for further investigation?

**Comment by rakshitatandon** [comment] 2017-09-13 17:56
Is there any specific difference between the 2 certificate types ? You can find the logs in FabricLogRoot (this is a configurable setting which you would have set while deploying your cluster).

**Comment by Abdruggi** [comment] 2017-09-13 18:22
To be honest, there is no difference. I got both of them from our internal ca team. The F5 load balancer has no problem using them. Because the logs are huge, would it be ok to upload them to one drive and send you a link?

**Comment by rakshitatandon** [comment] 2017-09-13 18:28
Yes sure.

**Comment by Abdruggi** [comment] 2017-09-22 16:35
How does service fabric export the certificates? certutil.exe, .NET, ..? I would like to reproduce the whole exportation process to find the root of the problem.

**Comment by rakshitatandon** [comment] 2017-09-22 18:48
Service Fabric uses native Crypt32 library APIs to read certificate from store and export as PFX.
https://msdn.microsoft.com/en-us/library/windows/desktop/aa387313(v=vs.85).aspx

**Comment by mani-ramaswamy** [comment] 2017-10-31 18:03
Closing since we haven't heard back for a few weeks. Please let us know if there's still an issue here and reopen as appropriate.

**Comment by ekumlin** [comment] 2018-02-06 21:49
@mani-ramaswamy, @rakshitatandon -- I've run into this issue as well. It's *not* an issue with the file not existing; I've tried reading the bytes into a variable instead, and passing it as an argument that way, and I get the same error.

The certificate itself was created using:
```
New-SelfSignedCertificate -CertStoreLocation "cert:\LocalMachine\My" -DnsName "FooBar" -Provider "Microsoft Enhanced Cryptographic Provider v1.0" -Subject "CN=FooBar" -NotAfter (Get-Date).AddYears(20)
```

The following code works, if I take the `pfx` file generated from that self-signed certificate (with password `foo`), **on my host machine** (*not* in the container).
```
// Both of these work
var x = new X509Certificate2(@"E:\\FooBar.pfx", "foo");
var y = new X509Certificate2(File.ReadAllBytes(@"E:\\FooBar.pfx"), "foo");
```

However, when running in the container (after following the steps [here](https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-securing-containers)), the following does *not* work.
```
var file = new FileInfo(Environment.GetEnvironmentVariable("Certificates_<my-svc-pkg-name>_<my-code-pkg-name>_FooBar_PFX"));

/* ACL code omitted */

var password = File.ReadAllLines(passwordFilePath, Encoding.Default)[0];
password = password.Replace("\0", string.Empty);

// Everything above this works fine -- the below throws an exception
return new X509Certificate2(
    file.FullName, // Also throws the same exception with File.ReadAllBytes(file.FullName)
    password,
    X509KeyStorageFlags.MachineKeySet | X509KeyStorageFlags.PersistKeySet);
```

*(Note 1: I have correctly ACL'd both the `pfx` and password files and can read their contents.)*
*(Note 2: I have also tried with no storage flags, and with `X509KeyStorageFlags.Exportable`; neither shows any change.)*

The following exception is produced:
```
"Exception": {
    "ClassName": "Internal.Cryptography.CryptoThrowHelper+WindowsCryptographicException",
    "Message": "Cannot find the requested object",
    "Data": null,
    "InnerException": null,
    "HelpURL": null,
    "StackTraceString": "
       at Internal.Cryptography.Pal.CertificatePal.FromBlobOrFile(Byte[] rawData, String fileName, SafePasswordHandle password, X509KeyStorageFlags keyStorageFlags)
       at System.Security.Cryptography.X509Certificates.X509Certificate..ctor(Byte[] rawData, String password, X509KeyStorageFlags keyStorageFlags)
       at <MyService>.<MyMethod>(String certificateFilePath, String passwordFilePath) in D:\\Repos\\<MyService>\\<MyFile>.cs:line 102",
    "RemoteStackTraceString": null,
    "RemoteStackIndex": 0,
    "ExceptionMethod": null,
    "HResult": -2146885623,
    "Source": "System.Security.Cryptography.X509Certificates",
    "WatsonBuckets": null
}
```

**Can this issue be re-opened?** (Alternatively I can open a new issue.)

**Comment by rakshitatandon** [comment] 2018-03-17 00:16
Thanks for reporting. This is a known issue and will be fixed in 6.2

**Comment by tvperez76** [comment] 2018-03-26 06:27
What’s the ETA on getting this issue resolved?  Is there a workaround?  Not being able to utilize certificates from a container is a showstopper.

**Comment by mani-ramaswamy** [comment] 2018-03-26 17:08
We should have the next release out in a few weeks time with the fix.  @rakshitatandon  to comment on any workarounds.

**Comment by rakshitatandon** [comment] 2018-03-27 17:41
To workaround this issue, you should still be able to use the 2nd approach highlighted in this doc https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-securing-containers i.e. using data packages.

**Comment by AaronRM** [comment] 2018-05-16 21:56
I can second the comments from @askew. The PFX imported to the container by Service Fabric (even in 6.2) does *not* contain the private key (even when the cert installed on the host does contain an exportable private key). @rakshitatandon Can you please follow up/comment on this?

**Comment by ChackDan** [comment] 2018-05-25 17:59
Rakshita has narrowed the issue to a potential bug. She is following up with the Crypto team on this.

**Comment by masnider** [comment] 2018-05-25 18:05
@rakshitatandon is looking into this

**Comment by stevshan** [comment] 2018-06-15 04:47
Currently, this issue seems to be a bug in Service Fabric CertStore.

**Comment by stevshan** [comment] 2018-06-26 21:09
The fix will be released together with 6.2 CU4 and 6.3.

**Closed by stevshan** 2018-06-26 21:09 UTC
Labels: question

**Comment by xenalite** [comment] 2018-09-15 10:45
@stevshan @rakshitatandon This issue is still reproducible in 6.3
I am using Azure SF cluster version `6.3.176.9494`.

Imported an application certificate on all cluster nodes using `Add-AzureRmServiceFabricApplicationCertificate` using `SecretIdentifier` parameter set.

The certificate appears in Personal store of LocalMachine, with a private key, but it's non-exportable.
Then the exported PFX certificate does not have a private key.

It seems to that any certificate attached to VM Scale sets via the OS Profile are not exportable.
So the only other way of distributing your certificate on all nodes is to do it manually or use a data package. :|

**Comment by dragav** [comment] 2018-09-22 20:03
That is correct, most certificate provisioning methods in use today will install the certificate as non-exportable on the host. This is by design and won't change. We're working on improving support for secrets (including certificates) into containers.

In the meantime, there are several alternatives to working around this limitation; to recommend what would be best for you we'd need more details on your setup - where do you store your certificate, is this an Azure or on-prem cluster etc. Feel free to email me/us directly: dragosav or sfsssteam at Microsoft dot com. Thanks.

**Comment by MarkDixonTech** [comment] 2018-09-25 14:40
The problem seems to be that whilst the certificate and private key is deployed to the Service Fabric node, it is marked as non-exportable and therefore the private key cannot be deployed to the container within the node. 

The pfx file is deployed to the container but the private key is missing whereas it is not within the node. 

As yet I haven't been able to get the second method working

**Comment by MikeChristensen** [comment] 2019-05-21 22:08
This is about 7 months old now, but did anyone ever figure out how to gain access to a cluster certificate from within a Docker container including the private key?

**Comment by askew** [comment] 2019-05-30 10:37
@MikeChristensen , I ended up getting a certificate directly from KeyVault using a managed identity.

https://github.com/askew/container-certs-service-fabric
