### ISSUE TITLE
DNS service port

### ISSUE THREAD

**Issue by nileshbits** [Azure/service-fabric-issues#971] opened 2018-04-11 12:11 UTC
I'm trying to use the SF runtime installed on a VSTS Agent, but the DNS service port is conflicting:
"
DnsService UDP listener is unable to 
                        start. Please make sure there are no processes listening on the DNS port 53.
                        List of processes listening on the DNS port:
                          UDP    0.0.0.0:53             *:*                                    8576
                        
"

Is there a workaround for this? Can we change the DNS service port? Thanks!

**Comment by masnider** [comment] 2018-04-11 17:39
_Usually_ this is ICS (internet connection sharing). If you stop and disable that service (Which Windows recently started auto-starting), then this goes away. The DNS protocol itself is bound to port 53, so there's no good way to "change the port" and have DNS still work.

**Comment by nileshbits** [comment] 2018-04-11 20:13
yes, even my independent research threw up the same culprit. Not sure if there is a way around this other than turning off ICS, please let me know how the SF team works with this - I'm guessing you would have the same problem when testing SF? Thanks.

**Comment by ninzavivek** [comment] 2018-04-25 18:29
The issue has been fixed in 6.2. Please upgrade to 6.2 and reopen if the issue persists.

**Closed by ninzavivek** 2018-04-25 18:29 UTC
Labels: question

**Comment by ibuildit** [comment] 2018-09-20 11:48
I'm using august 20 release and I still have this issue.

**Comment by ibuildit** [comment] 2018-09-20 12:00
If I disable Hyper-V, the problem is gone and DNS service is OK.

**Comment by ibuildit** [comment] 2018-09-20 12:31
removed and added back hyper-v and after the included reboots the DNS issue is gone. Error message as described in original post is gone.
