### ISSUE TITLE
ServiceProxy.Create asking for primary returns secondary replica instead

### ISSUE THREAD

**Issue by zeodamian** [Azure/service-fabric-issues#192] opened 2017-03-12 14:42 UTC
[As specified on SO](http://stackoverflow.com/questions/42748513/serviceproxy-create-asking-for-primary-returns-secondary-replica-instead) I get a secondary replica when asking for the primary replica.

This happens after rolling upgrade to the service.

Funny thing is that some actor types get the primary as expected, while other get a secondary replica.

Not sure how I could possibly be doing something wrong to get this result. And even so, then there is definitely something that needs clarification.

**Edit:** I just want to clarify that this happens at every upgrade, and it does not go away until projects using ServiceProxy to call the upgraded service, has been restarted.
This kind of defeats the purpose of microservices and rolling upgrades, no?

**Comment by BharatNarasimman** [comment] 2017-03-13 21:30
@zeodamian Are you seeing FabricNotPrimaryException thrown from your service proxy method when you call the ServiceProxy that have the TargetReplicaSelector as Primary?

**Comment by zeodamian** [comment] 2017-03-14 14:42
Yes, that's what I get.

**Comment by zeodamian** [comment] 2017-03-24 11:22
So updating with some more info:

Version is 5.3.311.9590

ActorProxy does not have this problem, only ServiceProxy. (i.e. upgrading actors never result in this problem).

I have been able to manually move the primary replica with PowerShell until it seems that the one that was primary before upgrade, is again primary, and then it can be found with ServiceProxy.
However, any instances of actors for example, that has used Servicceproxy in the meanwhile, seems to be using a reference to the replica that became primary at that time.

So, this makes it almost impossible to do an upgrade without disrupting communications with the service. Until we can do that, it is not possible to bring this to production.

**Comment by VipulM-MSFT** [comment] 2017-03-24 17:13
Thanks we are investigating; have your tried without specifying target replica selector? Would it be possible for you to create a standalone repro?

**Comment by suchiagicha** [comment] 2017-03-30 17:34
@zeodamian 

I could not repro this issue.  if TargetSelector is Primary, we re-resolve on FabricNotPrimaryException exception and retry the request. So User Api should not be seeing this exception. 
I am assuming you are not seeing this as First Chance Exception.

Could you share your code for repro'ing this issue ? . We can then look at it.

**Comment by zeodamian** [comment] 2017-04-09 15:44
Hi, thanks you for looking at this, and sorry for late reply!

What happened is that we upgraded to latest version of SF and that gave a slightly different behaviour.

Previously, I had let the actors keep pounding ServiceProxy, in hope that it would eventually recover. And it did! After maybe 15-20 minutes or so. (No moving around of primary, just trying to let all sort out by itself).
After the upgrade, the same thing happened, but ServiceProxy recovered much faster, after a couple of minutes maybe.

Then we did yet another change:
This service was previously the only service in the application. Now we bunched 3 (stateful) services together in the application, and then upgrading worked without this error happening at all.

I don't know if any of it makes sense. 

I was about to do a standalone repro, by simply adding an actor project and a stateful service, and let the actor user ServiceProxy to call the service before and after an upgrade to the service, but never got to it. And now, everything works, so we're happy with that. 

Something definitely wasn't working right, but I'm not sure I can reproduce it now.

**Comment by BharatNarasimman** [comment] 2017-04-09 16:18
@zeodamian  thanks for trying and getting back. I will close this for now, please reopen if you see are able to reproduce that behavior.

**Closed by BharatNarasimman** 2017-04-09 16:18 UTC
Labels: investigating

**Comment by smphayward** [comment] 2017-04-25 20:47
We are having the same issue with Service Fabric. We create a ServiceProxy as follows:

var appBuilderManager = PartitionKey.GetService<IAppManager>(FabricUris.AppManager, context.TenantId, TargetReplicaSelector.Default);

Then we make a call to it where the reliable dictionary must be writeable:

var saveResponse = await appBuilderManager.UpsertAppsToDraftAsync(context, new[] { app });

This throws a System.Fabric.FabricNotPrimaryException exception. At the bottom of the stack trace is the ThrowIfNotWritable() method, which seems to be internal to Service Fabric.

We see this periodically but once a service gets into this state there seems to be no way to get it out of this state short of re-deploying the effected services.

We're using SDK v 2.3.301 hosted on Azure. The Azure VMs are hosting Service Fabric v 5.5.216.0.

**Comment by VipulM-MSFT** [comment] 2017-10-27 17:05
@smphayward - is this issue resolved? Do you let the not primary exception bubble up and transfer to the client? If it does, the client will re-resolve the primary automatically.

**Comment by smphayward** [comment] 2018-03-07 16:41
@VipulM-MSFT The issue seemed to sort itself out after rebuilding the cluster but we just had it occur again. Took us 3 days to track down. This time, RunAsync() was firing on the Secondary Replica. It reported itself as the Primary Replica but any attempt to change a Reliable Dictionary resulted in FabricNotPrimaryException.

We had 4 partitions in that service and the issue only effected one of them.

Subsequent upgrades of the service did not fix the issue.

Removing and re-creating the service did not fix the issue.

The fix was:

- Remove the offending service
- Reboot the cluster one machine at a time (waiting for the rebooted machine to fully re-integrate into the cluster before rebooting the next machine)
- Re-deploy the service

Because of issues like this (and many, many others), we are moving away from reliable dictionaries entirely. Having the data housed with the compute was a nice dream but Cosmos DB will be a much better fit for us.

We will still use Service Fabric for business logic and data access, of course. It's a great product. It's just the Reliable Dictionaries that we've found... umm... unreliable. ;-)
