### ISSUE TITLE
Services fail: Exception at t System.Fabric.Common.FabricPerformanceCounter..ctor(IntPtr instanceHandle, Int32 index)

### ISSUE THREAD

**Issue by Expecho** [Azure/service-fabric-issues#1102] opened 2018-06-08 08:17 UTC
Hi, 

We have a problem with several services deployed at our Azure Cluster (v6.2.283.9494). The error we are getting is this:

> Unhealthy event: SourceId='System.RA', Property='ReplicaOpenStatus', HealthState='Warning', ConsiderWarningAsError=false.
Replica had multiple failures during open on _Generic_0. API call: IStatefulServiceReplica.Open(); Error = System.ArgumentException (-2147024809)
Value does not fall within the expected range.
   at System.Fabric.Interop.Utility.WrapNativeSyncInvoke[TResult](Func`1 func, String functionTag, String functionArgs)
   at System.Fabric.Interop.Utility.WrapNativeSyncInvoke(Action action, String functionTag, String functionArgs)
   at System.Fabric.Interop.Utility.RunInMTA(Action action)
   at System.Fabric.Common.FabricPerformanceCounter..ctor(IntPtr instanceHandle, Int32 index)
   at System.Fabric.Common.FabricPerformanceCounterSetInstance..ctor(FabricPerformanceCounterSet counterSet, String instanceName)
   at Microsoft.ServiceFabric.Replicator.LoggingReplicator.InitializePerformanceCounters()
   at Microsoft.ServiceFabric.Replicator.LoggingReplicator.d__138.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ServiceFabric.Replicator.DynamicStateManager.d__118.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ServiceFabric.Replicator.TransactionalReplicator.d__79.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ServiceFabric.Replicator.StatefulServiceReplica.d__21.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ServiceFabric.Data.ReliableStateManagerImpl.d__49.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ServiceFabric.Services.Runtime.StatefulServiceReplicaAdapter.d__17.MoveNext()
For more information see: http://aka.ms/sfhealth

**Comment by masnider** [comment] 2018-06-12 18:42
This looks like performance counter initialization failing. Added some folks to take a look. In prior cases this has been caused by issues with Windows perf counters, as well as memory issues on the machine. @Expecho you take a look and see if the machines are under memory pressure when this is happening?

**Comment by Expecho** [comment] 2018-06-13 14:36
@masnider the problem went away after deleting the affected applications and redeploying it with its services. Not all services were affected though.


Can't remember the memory pressure but since we are still in early stages I've never seen  high memory pressure ( we have a monitor showing live stream of the servers telemetry using application insights)

**Comment by masnider** [comment] 2018-06-14 02:05
Ok. There have been cases in the past where perf counter initialization would fail when we tried to create a bunch simultaneously, but those issues were worked out some time ago. 

I'll close this issue down for now since you're up and running. If you see it again reopen it and let us know and these folks will probably want to get a look at the environment.

**Closed by masnider** 2018-06-14 02:05 UTC
Labels: question
