### ISSUE TITLE
.NET Core 2.0 Target Stateful Service occurs "Partition is below target replica or instance count" error in 1-node local cluster.

### ISSUE THREAD

**Issue by wminos** [Azure/service-fabric-issues#902] opened 2018-03-05 14:07 UTC
MinReplicaSetSize/TargetReplicaSetSize is all 1.

.NET Framework Target Stateful service is ok.
but .NET Core 2.0 Target Stateful service occurs error.

## Step (.NET Core 2.0 Target)
Visual Studio 2017 > 
New Project > 
Service Fabric Application > 
**.NET Core 2.0**> Stateful ASP.NET Core (or Stateful Service)

- It occurs error in local 1-node cluster.
  - error in explorer: Partition is below target replica or instance count

## Step (.NET Framework Target)
Visual Studio 2017 > 
New Project > 
Service Fabric Application > 
**.NET Framework**> Stateful ASP.NET Core (or Stateful Service)

- This is ok.

**Comment by raunakpandya** [comment] 2018-03-05 14:08
Can you tell us what error do you see?

**Comment by wminos** [comment] 2018-03-05 14:13
<img width="1014" alt="2018-03-05" src="https://user-images.githubusercontent.com/36513305/36979437-d5f28d34-20ca-11e8-8b08-6320238f0b57.png">

**Comment by raunakpandya** [comment] 2018-03-05 14:20
We would need the traces for the cluster to debug this further. BTW, check if this is related #643

**Comment by wminos** [comment] 2018-03-05 14:39
Thank you!
I solved this by adding <RuntimeFrameworkVersion>2.0.5</RuntimeFrameworkVersion> at .csproj.

**Comment by raunakpandya** [comment] 2018-03-05 14:41
Glad to hear that worked. Closing issue as duplicate of #643

**Closed by raunakpandya** 2018-03-05 14:41 UTC

**Comment by cwaldron** [comment] 2018-04-03 01:30
Is there a solution to this problem?  Because I'm seeing the same error and upgraded to the 20 March tool set.
