### ISSUE TITLE
The OutputPath property is not set for project 'Platform.sfproj'.

### ISSUE THREAD

**Issue by Marusyk** [Azure/service-fabric-issues#231] opened 2017-04-06 12:35 UTC
After update Visual Studio 2017 to 15.1 (26403.0) I can't build my Service fabric solution:

> Severity	Code	Description	Project	File	Line	Suppression State
> Error		The OutputPath property is not set for project Platform.sfproj'.  Please check to make sure that you have specified a valid combination of Configuration and Platform for this project.  Configuration='Debug'  Platform='x64'.  This error may also appear if some other project is trying to follow a project-to-project reference to this project, this project has been unloaded or is not included in the solution, and the referencing project does not build using the same or an equivalent Configuration or Platform.	Deezze.Platform	C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets	737	
> 

For all of my projects I have targeted paltform like

 ```
 <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|x64'">
    <PlatformTarget>x64</PlatformTarget>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|x64'">
    <PlatformTarget>x64</PlatformTarget>
  </PropertyGroup>
```

Also while solution is loading message "The project must have its NuGet packages restored in order to work correctly. Would you like to do that now?" appears every time when I press "Yes" button.

Please suggest some solution for that

**Comment by dbreshears** [comment] 2017-04-06 14:05
15.1 should have the 1.5 Service Fabric tooling and thus should attempt to upgrade your 1.4 projects.   Are you able to create a new project with 15.1 successfully?    For the existing project you having issues with,  Open the .sfproj in notepad and validate the project imports specify Microsoft.VisualStudio.Azure.Fabric.MSBuild.1.5.0,  there are 4 places.   Also check that ProjectVersion and MinToolsVersion elements specify 1.5.   

 ```
 <Import Project="..\packages\Microsoft.VisualStudio.Azure.Fabric.MSBuild.1.5.0\build\Microsoft.VisualStudio.Azure.Fabric.Application.props" Condition="Exists('..\packages\Microsoft.VisualStudio.Azure.Fabric.MSBuild.1.5.0\build\Microsoft.VisualStudio.Azure.Fabric.Application.props')" />
  <PropertyGroup Label="Globals">
     <ProjectVersion>1.5</ProjectVersion>
    <MinToolsVersion>1.5</MinToolsVersion>
  </PropertyGroup>

...
<Import Project="..\packages\Microsoft.VisualStudio.Azure.Fabric.MSBuild.1.5.0\build\Microsoft.VisualStudio.Azure.Fabric.Application.targets" Condition="Exists('..\packages\Microsoft.VisualStudio.Azure.Fabric.MSBuild.1.5.0\build\Microsoft.VisualStudio.Azure.Fabric.Application.targets')" />

```
Also, verify that the packages.config for the Application has the following and that this package exists in the packages folder

```
<?xml version="1.0" encoding="utf-8"?>
<packages>
  <package id="Microsoft.VisualStudio.Azure.Fabric.MSBuild" version="1.5.0" />
</packages>

```

**Comment by Marusyk** [comment] 2017-04-06 21:19
Thanks a lot. It was really helpful. ProjectVersion and MinToolsVersion elements were specified to 1.5 automatically but the problem was in `Microsoft.VisualStudio.Azure.Fabric.MSBuild.1.4.0`. So I manually changed it to `Microsoft.VisualStudio.Azure.Fabric.MSBuild.1.5.0` in 4 places and success. Thanks.

**Comment by dbreshears** [comment] 2017-04-06 21:30
Thanks.. was this project previously working with VS 2017 prior to the "15.1" update?   What version of the Service Fabric SDK did you have installed?  2.4 or 2.5?

**Comment by Marusyk** [comment] 2017-04-06 21:38
Yes, it was working in VS 2017 15.0.26228.9 with SDK 2.5.216 before install 15.1

**Comment by ryancrawcour** [comment] 2017-04-12 17:05
I have this same issue on 2 different machines.

**Comment by dbreshears** [comment] 2017-04-13 23:33
Investigating with Ryan,  we discovered the cause of the infinite  loop of "The project '<projectname>' must have its NuGet packages restored in order to work correctly.  Would you like to do that now?".    Selecting Yes, just brings back the same dialog.

The issue in this case is that when the .sfproj file was created, the packages folder was created in its default location next to the .sln file  by the Nuget package manager.    At this point the Service Fabric VS Extension adds Imports for the .props and .targets file and uses a relative path to the location and all works.  

`<Import Project="..\packages\Microsoft.VisualStudio.Azure.Fabric.MSBuild.1.5.0\build\Microsoft.VisualStudio.Azure.Fabric.Application.props" Condition="Exists('..\packages\Microsoft.VisualStudio.Azure.Fabric.MSBuild.1.5.0\build\Microsoft.VisualStudio.Azure.Fabric.Application.props')" />`

Later the folder structure was modified to include a nested folder and although the MSBuild Nuget package was restored appropriately,  the path to the import in the .sproj file was incorrect due to the refactoring.   The extension then doesn't find the Nuget package restored and attempts to restore it, for the props to work correct we need to unload/reload the project programmatically which starts the whole process over again until you press no to get out of the loop.

The workaround is to update the .sfproj file in 4 places with the correct relative path to the props and targets file.   Logging a bug and we will attempt to fix this in an upcoming release.

**Comment by Mardoxx** [comment] 2017-04-14 00:11
I got infinite restore packages issue when upgrading from 1.4 to 1.5 because updated sfproj file was looking (or trying to restore) old 1.4 tools. Renaming it to 1.5 solved it for me.

**Comment by dipankar-das** [comment] 2017-04-18 02:55
Edit the project file using text editor and add 
<MinToolsVersion>1.5</MinToolsVersion>
Next to 
 <ProjectVersion>1.5</ProjectVersion>
 
Reload the project it will work fine.

**Comment by toddabel** [comment] 2017-05-01 18:00
I'm not getting this on a project after syncing changes from another machine. I get the "refresh NuGet" pacakges then this dialog. My .sfproj file already has MinToolsVersion and ProjectVersion set to 1.5

The error in the file are:

===================
5/1/2017 10:54:02 AM
Recoverable
System.ArgumentException: C
![vs error](https://cloud.githubusercontent.com/assets/4468495/25588480/48a2dcc8-2e5d-11e7-81c9-f341e5b2210d.png)
annot access a disposed object.
Object name: 'Microsoft.VisualStudio.ProjectSystem.ProjectCapabilitiesScope'.
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
   at Microsoft.VisualStudio.ErrorHandler.ThrowOnFailure(Int32 hr, Int32[] expectedHRFailure)
   at Microsoft.VisualStudio.Azure.Fabric.Shared.Hierarchy.UnloadAndReloadProject(IServiceProvider serviceProvider, Guid projectId, Boolean reopenDocuments)
   at Microsoft.VisualStudio.Azure.Fabric.ApplicationProject.ProjectSystem.PackageRestoreManager.<InitializeAsync>d__20.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.ProjectSystem.UnconfiguredProjectImpl.AutoLoadMethodStateMachine.<<StartExecution>b__8_0>d.MoveNext()
===================

**Comment by dbreshears** [comment] 2017-05-01 18:22
Is the path to the Microsoft.VisualStudio.Azure.Fabric.MSBuild.1.5.0 Nuget package in the .sfproj correct?  There is an import at the top for the .props and then one at the bottom for the .targets.

**Comment by toddabel** [comment] 2017-05-01 19:54
No it wasn’t correct, correcting these two path statements corrected the error.
Thanks for the help, it would be nice if it was more obvious as to what the issue is.

Todd.

**Comment by dbreshears** [comment] 2017-05-02 01:03
Yeah, it's a bug that we should have fixed in the next release.

**Comment by VDBorovikov** [comment] 2017-05-17 10:11
Having the same problem after updating ```Microsoft.VisualStudio.Azure.Fabric.MSBuild``` to version 1.6.0. So I edited .sfproj manually in 4 places. The previous version 1.5.0.
Don't know whether I need to change the ProjectVersion, but I just left it as is.

**Comment by Mardoxx** [comment] 2017-05-17 10:13
ProjectVersion is the version of the SF tooling installed, not the MSBuild version! ProjectVersion latest is 1.5 (I believe)

**Comment by dbreshears** [comment] 2017-05-17 15:12
Yes in VS 2017 15.2 the version is currently 1.5.  In  VS2017 15.3 Preview 1, this version is 1.6. We hope to have an update to 15.2 this week, that will include the 1.6 tooling version so these two channels are in sync.

**Comment by dereksonthejob** [comment] 2017-05-17 17:18
Hello @dbreshears I have the same issue I am stuck in a pkg update loop. When I change the packages.config file from 1.6 to 1.5 it builds properly but cannot deploy to local cluster.  How can I tell if my paths are correct? 
<Import Project="..\packages\Microsoft.VisualStudio.Azure.Fabric.MSBuild.1.5.0\build\Microsoft.VisualStudio.Azure.Fabric.Application.props" Condition="Exists('..\packages\Microsoft.VisualStudio.Azure.Fabric.MSBuild.1.5.0\build\Microsoft.VisualStudio.Azure.Fabric.Application.props')"

**Comment by dereksonthejob** [comment] 2017-05-17 17:22
Also I cannot update this package
![image](https://cloud.githubusercontent.com/assets/4186787/26167099/d018a978-3b03-11e7-9d9c-e0db8f418ae4.png)

I fails and asks to restart visual studio I believe all of my file paths are correct when comparing to a team mates .sfproj file

**Comment by Mardoxx** [comment] 2017-05-17 18:09
`Microsoft.VisualStudio.Azure.Fabric.MSBuild.1.5.0` should be `Microsoft.VisualStudio.Azure.Fabric.MSBuild.1.6.0`

**Comment by dereksonthejob** [comment] 2017-05-17 18:17
Thanks I did that previously but not in all of the locations.  A total 4 I only placed it in 2 places.  Thanks this helped.

**Comment by MedAnd** [comment] 2017-06-09 15:52
Hi @dbreshears 

I'm testing some workarounds for another VS 2015 to VS 2017 upgrade issue #303... but noticed this bug as well. 

Repro steps:

1. Working with a VS 2017 Service Fabric solution on a Windows 2012 R2 OS - compile, package and publish all work as expected. 
2. Opening the same VS 2017 Service Fabric solution on a Windows 10 OS and the *.sfproj file is automatically modified.

*.sfproj file in VS 2017 on Windows 10 OS contains:

` <Import Project="..\..\packages\Microsoft.VisualStudio.Azure.Fabric.MSBuild.1.6.0\build\Microsoft.VisualStudio.Azure.Fabric.Application.props" Condition="Exists('..\..\packages\Microsoft.VisualStudio.Azure.Fabric.MSBuild.1.6.0\build\Microsoft.VisualStudio.Azure.Fabric.Application.props')" />`

*.sfproj file in VS 2017 on Windows 2012 R2 contains:

`<Import Project="packages\Microsoft.VisualStudio.Azure.Fabric.MSBuild.1.6.0\build\Microsoft.VisualStudio.Azure.Fabric.Application.props" Condition="Exists('packages\Microsoft.VisualStudio.Azure.Fabric.MSBuild.1.6.0\build\Microsoft.VisualStudio.Azure.Fabric.Application.props')" />`

**Comment by dbreshears** [comment] 2017-06-09 17:57
Do you have a repro project that I can try.   Doubt the OS would matter in this case.  We do have logic to find the Nuget package if we find it isn't located where the project specifies since this can be specified via nuget.config at project or solution.   Do you happen to have  Nuget.config at some point that forced restore to the ..\..\packages location?    What if you delete the packages folder on the Windows 10 machine prior to opening the solution, does it still repro?

**Comment by MedAnd** [comment] 2017-06-09 23:20
I deleted the nuget packages folder in the solution in addition to deleting the global nuget packages cache folder for my user on Windows 10 OS. Opening the solution in VS 2017 throws an error, from the VS 2017 log file I can see:

`10/06/2017` 9:05:10 AM
Crippling
System.InvalidOperationException: Internal error: Critical capabilities changes were detected without any change made to the project, and forces the project to be reloaded.
   at Microsoft.VisualStudio.ProjectSystem.ProjectCapabilitiesRequirementsService.RequestReloadForIncompatibleCapabilitiesAsync(IImmutableSet`1 capabilities)
   at Microsoft.VisualStudio.ProjectSystem.UnconfiguredProjectImpl.<Microsoft-VisualStudio-ProjectSystem-IProjectCapabilitiesScopeContext-ReloadIfNecessaryAsync>d__161.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.VisualStudio.ProjectSystem.CommonProjectSystemTools.Rethrow(Exception ex)
   at Microsoft.VisualStudio.ProjectSystem.ProjectErrorReporting.<>c__DisplayClass6_0.<SubmitErrorReport>b__0()
   at Microsoft.VisualStudio.ProjectSystem.ExceptionFilter.<>c__DisplayClass2_0.<Guard>b__0()
   at GuardMethodClass.GuardMethod(Func`1 , Func`2 , Func`2 )
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)

10/06/2017 9:05:23 AM
Recoverable
System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.VisualStudio.Azure.Fabric.ApplicationProject.ProjectSystem.PackageRestoreManager.<InitializeAsync>d__24.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.ProjectSystem.UnconfiguredProjectImpl.AutoLoadMethodStateMachine.<<StartExecution>b__8_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception `exceptionObject)`


Once I click OK, the *.sfproj now goes into an endless loop trying to restore nuget with exception:

![image](https://user-images.githubusercontent.com/13365135/26997428-ea72800c-4dbc-11e7-9587-a57173079983.png)

Do you have an email address, will try to send you something?

**Comment by dbreshears** [comment] 2017-10-26 03:35
Closing, as I believe these issues have been fixed.

**Closed by dbreshears** 2017-10-26 03:35 UTC
Labels: bug, investigating

**Comment by MattHartz** [comment] 2018-01-08 21:43
So how do I fix this in my code?

**Comment by WhitWaldo** [comment] 2018-03-06 03:17
I ran into this issue again today, receiving a number of the issues indicated above. Some details first about my build server. I just installed the latest Visual Studio patch (15.5.7) and updated both Microsoft Azure PowerShell (released 2/27/18) and the Service Fabric SDK (to 3.0.467, released 2/20/17) via the Web Platform Installer.

Thereafter, I found myself unable to build my service fabric solution on the server. First, I received the following error:

> Project.sfproj(55,5): error : Unable to find the '..\packages\Microsoft.VisualStudio.Azure.Fabric.MSBuild.1.6.4\build\Microsoft.VisualStudio.Azure.Fabric.Application.props' file. Please restore the 'Microsoft.VisualStudio.Azure.Fabric.MSBuild' Nuget package.

I looked at the specified directory on my build server and saw that while there was no MSBuild 1.6.4, there was a directory containing all the files it was looking for in 1.6.5, so I modified all the references in the file from 1.6.4 to 1.6.5. The ProjectVersion is set to 2.0, the MinToolsVersion to 1.5 and everything pointing to the x64 platform with TargetFrameworkVersion set to v4.7. Earlier up in this, there's apparently an update of the MinToolsVersion to 1.6, but I haven't yet made that change.

I had actually missed several 1.6.4 references (there were ultimately 9 or 10 of them in the sfproj file) and received this error for a build or two until I noticed them:

> (_CheckForInvalidConfigurationAndPlatform target) -> 
> C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\15.0\Bin\amd64\Microsoft.Common.CurrentVersion.targets(750,5): error : The OutputPath property is not set for project 'Project.sfproj'.  Please check to make sure that you have specified a valid combination of Configuration and Platform for this project.  Configuration='Debug'  Platform='x64'.  You may be seeing this message because you are trying to build a project without a solution file, and have specified a non-default Configuration or Platform that doesn't exist for this project. [C:\vsts-agent-win-x64-2.126.0\_work\1\s\Project\Project.sfproj]

Of course, as someone pointed out in the above thread again, thing had nothing to do with the targets, but was still an MSBuild issue. I eventually found the remaining 1.6.4 references and updated those just to finally successfully build the .sln step.. and fail when building the .sfproj step with the following error:

> Project.sfproj(55,5): error : Unable to find the '..\packages\Microsoft.VisualStudio.Azure.Fabric.MSBuild.1.6.3\build\Microsoft.VisualStudio.Azure.Fabric.Application.props' file. Please restore the 'Microsoft.VisualStudio.Azure.Fabric.MSBuild' Nuget package

Right back where I started - except that this time, I noticed that the path was different. Apparently, at some point, a new directory was made with the name "ServiceFabricBackup". Because my build step is **\*.sfproj it was picking up this second sfproj file and attempting to build it (unsuccessfully).

Deleting that directory and trying once more resolved all the build issues and I'm no longer having an issue with this. But, I wanted to note these troubleshooting steps lest someone encounter a similar issue with error messages that aren't exactly helpful in getting to the bottom of the issue.

If you're making copies of the directory during versioning, any chance you could automatically update the build tools version yourself as well so they don't get out of sync like this again? Similarly, could you make the creation of this backup folder optional (or put it somewhere outside of the project directory)? The folder wasn't added to my solution - just to the directory, so unless I were looking for it, I wouldn't have known it was there except for this issue.
