### ISSUE TITLE
PackageReference Items Not packaged on deployment

### ISSUE THREAD

**Issue by awcab** [Azure/service-fabric-issues#159] opened 2017-02-06 17:04 UTC
I have a stateless service using the new project format with PackageReference items.  None of these are copied to the output directory when packaging the app for deployment causing runtime failures.

**Comment by MikkelHegn** [comment] 2017-02-06 17:30
@awcab - I cannot repo this using the asp.net core project templates that are part of the Service Fabric tooling.
Can you give more details on your project setup?

Thanks.

**Comment by awcab** [comment] 2017-02-06 17:32
Sure, like I mentioned, this is on a stateless service [c# project], not an asp.net project.

**Comment by MikkelHegn** [comment] 2017-02-06 17:37
I don't think the project templates for .NET based services have the targets needed to honor the PackageReference item, they are still using HintPaths and References. Adding reference packages (NuGet) via VS follows that pattern for these project types.

What are you trying to achieve by this, that you cannot accomplish using the "old" reference model?

**Comment by awcab** [comment] 2017-02-06 17:46
I wasn't intending to use the new project type, I just ended up with one along the way and it was converted for me during a dotnet migrate.  The bad thing was that this just mostly worked and it took a lot of digging to find out why not.  During debug, I got a runtime FileNotFoundException. At some level, I would suggest having a obvious error if the tooling isn't going to support the new project type.  At least until it does.

**Comment by MikkelHegn** [comment] 2017-02-06 18:24
Is the project a migrated dotnet core project (from xproj to csproj)? Was the reference lost as part of the migration or added post migration?

**Comment by awcab** [comment] 2017-02-06 18:33
Yes, it was migrated from xproj.  The references weren't lost, they were just converted from packages.config to PackageReference in the csproj.  These don't seem to be respected by the SF tooling.

**Comment by MikkelHegn** [comment] 2017-02-06 18:46
Just did an upgrade of an xproj to csproj and did not reproduce the issue. Can you share the project, or at least the sfproj xproj and csproj files from before and after migration?

**Comment by MikkelHegn** [comment] 2017-02-07 23:46
@awcab: I see there is a list of fixes to the Package Reference in the just released RC of VS2017. Can you give it a spin a let me know if you are still seeing issues?

**Comment by awcab** [comment] 2017-02-08 01:26
Sorry, these RCs have been so unstable.  With the latest one from today, I can't get anything to stay up long enough to test...

**Comment by MikkelHegn** [comment] 2017-02-08 18:04
I'm sorry to hear about that experience - please report the errors you see here, so we can follow-up: https://www.visualstudio.com/en-us/news/releasenotes/vs2017-relnotes#feedback

**Comment by MikkelHegn** [comment] 2017-02-08 22:49
@awcab: can you please reach out on mikhegn@microsoft.com - I would like to understand the RC issues you are seeing and the original issue with PackageReference.

**Comment by blackdwarf** [comment] 2017-02-09 01:59
@awcab can you please share your csproj file here? It would help us try to understand what is happening. 

Also, if you could help me understand: the core problem is not that the project is not restoring, but that the assemblies that are part of the packages are not copied over to the output directory, correct?

**Comment by awcab** [comment] 2017-02-09 16:19
@blackdwarf I've since converted my project back to the old style but I'll try to repro again.  And yes, that's correct.  Specifically, PackageReference elements were not being deployed at all.  There were also crashes around project and nuget conversion so I'm not sure if that's related.

**Comment by FelschR** [comment] 2017-03-07 12:16
I didn't notice this issue (yet) but a very similar one.
I also converted my .NET Core project to the new csproj format and I get a FileNotFoundException for the XML Documentation file that should be generated.

I tried it with just using
`<GenerateDocumentationFile>true</GenerateDocumentationFile>`
but also when adding `<DocumentationFile>` additionally to specify the file name.
The file gets created in the normal /Debug/x64/ structure but is not copied to the Service Fabric deployment folder.
Maybe this is some kind of timing issue? That all files are copied before the XML documentation was created?

Should I create an additional issue for this or should I leave it here. I guess the cause could be the same.

**Comment by danzel** [comment] 2017-03-10 05:36
I've created a new issue for XML documentation not being included over in #190 with full steps to reproduce. Not sure if they are related. Thanks :)

**Comment by Gillardo** [comment] 2017-03-14 16:11
Also having this problem... need file for swashbuckle to

**Comment by hiraldesai** [comment] 2017-05-21 05:33
I'm also facing similar issues. Is there a plan to support the new csproj format anytime soon? I have a project using VS2017 with lots of core projects/services targetting framework 452. All the stateless dotnet core services/apis are fine but stateful service class libraries don't seem to copy the required reference dlls to the `/SFProject/pkg/Debug/StatefulServiceNamePkg/`. All the required files are present in the `StatefulServiceNameProject/bin/x64/Debug`.

**Comment by masnider** [comment] 2017-08-25 18:42
@dbreshears @MikkelHegn @vturecek AFAIK this works now, right guys?

**Comment by dbreshears** [comment] 2017-10-12 05:56
Closing as this should be working now.

**Closed by dbreshears** 2017-10-12 05:56 UTC
Labels: question
