### ISSUE TITLE
When using Refresh Application (Preview) processes cannot access the files because being used by another process by redeployment

### ISSUE THREAD

**Issue by akalcik** [Azure/service-fabric-issues#701] opened 2017-12-09 12:48 UTC
My _Application Debug Mode_ is set to _Refresh Application (Preview)_. When I stop debugging and and try to restart the application with F5 I get bunch of **processes cannot access the files because being used by another process** errors. The only way to deploy is reset the local cluster. I don't have those errors by other _Application Debug Modes_. This seems to be only case with my Asp.Net Core 2.0 Api.

`
Severity	Code	Description	Project	File	Line	Suppression State
Error	MSB3021	Unable to copy file "obj\x64\Debug\net47\win7-x64\ToDoApp.Api.exe" to "bin\x64\Debug\net47\win7-x64\ToDoApp.Api.exe". The process cannot access the file 'bin\x64\Debug\net47\win7-x64\ToDoApp.Api.exe' because it is being used by another process.	ToDoApp	C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets	4106	
Warning	MSB3026	Could not copy "obj\x64\Debug\net47\win7-x64\ToDoApp.Api.exe" to "bin\x64\Debug\net47\win7-x64\ToDoApp.Api.exe". Beginning retry 1 in 1000ms. The process cannot access the file 'bin\x64\Debug\net47\win7-x64\ToDoApp.Api.exe' because it is being used by another process. The file is locked by: "ToDoApp.Api (22252)"	ToDoApp	C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets	4106	
Warning	MSB3026	Could not copy "obj\x64\Debug\net47\win7-x64\ToDoApp.Api.exe" to "bin\x64\Debug\net47\win7-x64\ToDoApp.Api.exe". Beginning retry 2 in 1000ms. The process cannot access the file 'bin\x64\Debug\net47\win7-x64\ToDoApp.Api.exe' because it is being used by another process. The file is locked by: "ToDoApp.Api (22252)"	ToDoApp	C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets	4106	
Warning	MSB3026	Could not copy "obj\x64\Debug\net47\win7-x64\ToDoApp.Api.exe" to "bin\x64\Debug\net47\win7-x64\ToDoApp.Api.exe". Beginning retry 3 in 1000ms. The process cannot access the file 'bin\x64\Debug\net47\win7-x64\ToDoApp.Api.exe' because it is being used by another process. The file is locked by: "ToDoApp.Api (22252)"	ToDoApp	C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets	4106	
Warning	MSB3026	Could not copy "obj\x64\Debug\net47\win7-x64\ToDoApp.Api.exe" to "bin\x64\Debug\net47\win7-x64\ToDoApp.Api.exe". Beginning retry 4 in 1000ms. The process cannot access the file 'bin\x64\Debug\net47\win7-x64\ToDoApp.Api.exe' because it is being used by another process. The file is locked by: "ToDoApp.Api (22252)"	ToDoApp	C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets	4106	
Warning	MSB3026	Could not copy "obj\x64\Debug\net47\win7-x64\ToDoApp.Api.exe" to "bin\x64\Debug\net47\win7-x64\ToDoApp.Api.exe". Beginning retry 5 in 1000ms. The process cannot access the file 'bin\x64\Debug\net47\win7-x64\ToDoApp.Api.exe' because it is being used by another process. The file is locked by: "ToDoApp.Api (22252)"	ToDoApp	C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets	4106	
Warning	MSB3026	Could not copy "obj\x64\Debug\net47\win7-x64\ToDoApp.Api.exe" to "bin\x64\Debug\net47\win7-x64\ToDoApp.Api.exe". Beginning retry 6 in 1000ms. The process cannot access the file 'bin\x64\Debug\net47\win7-x64\ToDoApp.Api.exe' because it is being used by another process. The file is locked by: "ToDoApp.Api (22252)"	ToDoApp	C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets	4106	
Warning	MSB3026	Could not copy "obj\x64\Debug\net47\win7-x64\ToDoApp.Api.exe" to "bin\x64\Debug\net47\win7-x64\ToDoApp.Api.exe". Beginning retry 7 in 1000ms. The process cannot access the file 'bin\x64\Debug\net47\win7-x64\ToDoApp.Api.exe' because it is being used by another process. The file is locked by: "ToDoApp.Api (22252)"	ToDoApp	C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets	4106	
Warning	MSB3026	Could not copy "obj\x64\Debug\net47\win7-x64\ToDoApp.Api.exe" to "bin\x64\Debug\net47\win7-x64\ToDoApp.Api.exe". Beginning retry 8 in 1000ms. The process cannot access the file 'bin\x64\Debug\net47\win7-x64\ToDoApp.Api.exe' because it is being used by another process. The file is locked by: "ToDoApp.Api (22252)"	ToDoApp	C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets	4106	
Warning	MSB3026	Could not copy "obj\x64\Debug\net47\win7-x64\ToDoApp.Api.exe" to "bin\x64\Debug\net47\win7-x64\ToDoApp.Api.exe". Beginning retry 9 in 1000ms. The process cannot access the file 'bin\x64\Debug\net47\win7-x64\ToDoApp.Api.exe' because it is being used by another process. The file is locked by: "ToDoApp.Api (22252)"	ToDoApp	C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets	4106	
Warning	MSB3026	Could not copy "obj\x64\Debug\net47\win7-x64\ToDoApp.Api.exe" to "bin\x64\Debug\net47\win7-x64\ToDoApp.Api.exe". Beginning retry 10 in 1000ms. The process cannot access the file 'bin\x64\Debug\net47\win7-x64\ToDoApp.Api.exe' because it is being used by another process. The file is locked by: "ToDoApp.Api (22252)"	ToDoApp	C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets	4106	
Error	MSB3027	Could not copy "obj\x64\Debug\net47\win7-x64\ToDoApp.Api.exe" to "bin\x64\Debug\net47\win7-x64\ToDoApp.Api.exe". Exceeded retry count of 10. Failed. The file is locked by: "ToDoApp.Api (22252)"	ToDoApp	C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets	4106	
Warning	NU1701	Package 'Microsoft.ServiceFabric 6.0.232' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETStandard,Version=v2.0'. This package may not be fully compatible with your project.	ToDoApp.Common	C:\Projects\kalcik.visualstudio.com\ToDoApp\_git\ToDoApp.ServiceFabric\src\ToDoAppSolution\ToDoApp.Common\ToDoApp.Common.csproj	1	
`

**Comment by vturecek** [comment] 2017-12-12 02:19
What version of Visual Studio are you using? Refresh Mode is out of preview now so something tells me you're using an older version that had a bug similar to what you're describing.

**Comment by akalcik** [comment] 2017-12-12 08:08
Hm. I'm using VS 2017 15.5.0 with Azure Fabric SDK 2.8.232.  I there anything else what am I missing?

**Comment by dbreshears** [comment] 2017-12-14 21:31
@vturecek ,  It is still in preview for 15.5 and will be out of preview in our next update.  @akalcik,  we have fixed several locking bugs such as this and will be in our next update.

**Comment by akalcik** [comment] 2017-12-28 20:11
@dbreshears Thanks. What is meant with "next update"? Can you be more specific?

**Comment by dbreshears** [comment] 2018-01-02 16:51
@akalcik.   I am hoping we can provide an update to the VS tooling in the next couple of weeks.   I don't have a specific date at the moment.   It will likely go out in tandem or fairly close to the next SDK update

**Comment by dbreshears** [comment] 2018-03-15 02:10
@akalcik, VS2017 15.6 contains our latest tooling, re-open if you are still experiencing these locking issues

**Closed by dbreshears** 2018-03-15 02:10 UTC

**Comment by mcsdodo** [comment] 2018-09-21 13:36
VS2017 15.8.5 still has this issues.

**Comment by mikoskinen** [comment] 2018-09-22 07:28
Encountered this problem today.

VS2017 15.8.5
Service Fabric 6.3.176.9494
Service Fabric SDK 3.2.176.9494

> C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(4187,5): warning MSB3026: Could not copy "obj\Debug\netcoreapp2.1\win7-x64\Web1.dll" to "bin\Debug\netcoreapp2.1\win7-x64\Web1.dll". Beginning retry 1 in 1000ms. The process cannot access the file 'bin\Debug\netcoreapp2.1\win7-x64\Web1.dll' because it is being used by another process. The file is locked by: "Web1.exe (21424)"

This happened after few quick Start - Stop - Start commands in VS when I was tweaking service's DNS name.

**Comment by mcsdodo** [comment] 2018-09-26 17:42
I've found out that it was caused by my **antivirus software**. After disabling it works just fine.
