### ISSUE TITLE
Register-ServiceFabricApplicationType : Operation timed out 

### ISSUE THREAD

**Issue by wirtoo** [Azure/service-fabric-issues#898] opened 2018-03-02 13:14 UTC
Hello, guys.
I have a very large application, which i'm trying to deploy on Service Fabric cluster and getting 
`Register-ServiceFabricApplicationType : Operation timed out`
Can I change Register-ServiceFabricApplicationType default timeout value? How can I do it?
I can try to modify configuration here https://resources.azure.com/subscriptions/ID/resourceGroups/GROUP/providers/Microsoft.ServiceFabric/clusters/NAME
but I want to be sure about JSON structure.
Thanks in advance.

**Comment by MikkelHegn** [comment] 2018-03-02 16:51
Duplicate of https://github.com/Azure/service-fabric-issues/issues/347

Let us know if that issue does not adress your issue.

**Closed by MikkelHegn** 2018-03-02 16:51 UTC
