### ISSUE TITLE
FabActUtil.exe access denied issues on build

### ISSUE THREAD

**Issue by kirk-marple** [Azure/service-fabric-issues#26] opened 2016-07-05 21:22 UTC
It looks like there's some collisions happening with multiple actors being built in a solution.  Using the "service-fabric-dotnet-data-aggregation" sample from Microsoft, upgraded to VS2015 Update 3, and all the latest packages, I'm still getting these errors when building.

It seems I can clear out the bin/obj folders from one actor, clean build it, and FabActUtil.exe gets copied OK.  But when I do the same on another actor project, it actually deletes FabActUtil.exe from the first project folder, and takes a few rebuilds to successfully build the second project.

Also, I'm getting access denied messages occasionally on the actor .exe's themselves.

Is there something that happens in the background on building an actor, which interferes with other actor projects getting built?

6>C:\Projects\service-fabric-dotnet-data-aggregation\packages\Microsoft.ServiceFabric.Actors.2.1.150\build\Microsoft.ServiceFabric.Actors.targets(29,5): error MSB3021: Unable to copy file "C:\Projects\service-fabric-dotnet-data-aggregation\packages\Microsoft.ServiceFabric.Actors.2.1.150\build\FabActUtil.exe" to "C:\Projects\service-fabric-dotnet-data-aggregation\HealthMetrics.BandActor\bin\x64\Debug\FabActUtil.exe". Access to the path 'C:\Projects\service-fabric-dotnet-data-aggregation\HealthMetrics.BandActor\bin\x64\Debug\FabActUtil.exe' is denied.

**Comment by Page-Not-Found** [comment] 2016-08-09 21:01
@kirk-marple I have the exact same problem. 

I use Windows 7 Enterprise and VS 2015 Update 3 along with SDK Version 5.1.163

**Comment by seanmck** [comment] 2016-08-09 23:13
When you see this, can you try running the [Handle tool](https://technet.microsoft.com/en-us/sysinternals/handle) to see if there's another process with a lock on the file? That will help us figure out what's getting you into this state.

**Comment by Page-Not-Found** [comment] 2016-08-10 12:02
@seanmck Sure I will try and port the results back.

**Comment by mkosieradzki** [comment] 2016-08-10 12:41
@seanmck Sean, this is quite trivial issue. The process locking this file is FabActUtil.exe itself. You do in your .targets file (in multiple places):
1. Exec FabActUtil
2. Delete FabActUtil

In such case you should have some graceful delete, because AFAIK there is no guarantee that windows releases executable file exactly at the moment it exits...

Introducing a minor delay between 1 and 2 is a workaround for the issue. But to be honest proper solution would be to use some graceful delete mechanism in msbuild or even better to run FabActUtil exe from nuget package folder and not delete executable which is really a bad solution IMO...

**Comment by Page-Not-Found** [comment] 2016-08-10 13:40
@seanmck That did not show the any handles locking the specific file.

**Comment by amanbha** [comment] 2016-08-10 18:24
@mkosieradzki Thanks for the feedback, we will look into possible solution for this. FabActUtil needs to run from out folder as it needs Microsoft.ServiceFabric.Actors.dll and other dlls from packages which it depends on.

**Comment by Page-Not-Found** [comment] 2016-08-10 18:32
@amanbha if you want me to run some tool and create a dump. I could do that, if at all that would be helpful

**Comment by amanbha** [comment] 2016-08-10 18:35
@Page-Not-Found Thanks, identifying what was holding on to it would help when the issue happens.

**Comment by Page-Not-Found** [comment] 2016-08-10 18:54
I tried like mulitple times to get that information with the Handle Util Shared by @seanmck no success. If you would be know the command I need to run, I can give another try.

**Comment by Page-Not-Found** [comment] 2016-08-10 21:08
Finally I was able to get the information. 

`System             pid: 4      type: File          13140: C:\Project1\Project1\FabActUtil.exe`

**Comment by amanbha** [comment] 2016-08-10 21:18
Thanks @Page-Not-Found

**Comment by WonderPanda** [comment] 2016-08-21 22:42
I'm also running into this issue constantly. Any tips or workarounds yet? It's a huge time waster that seems to just be a timing issue as others have mentioned. Continually hitting build/run will show FabActUtil failing on different Actor projects in my solution each time and eventually I seem to get lucky enough that a build will actually work.

**Comment by WonderPanda** [comment] 2016-08-22 02:22
@Page-Not-Found @kirk-marple @seanmck 
I've found that by modifying the Targets file `packages\Microsoft.ServiceFabric.Actors.2.1.163\build\Microsoft.ServiceFabric.Actors.targets`
and updating all of the `Delete` nodes to include `ContinueOnError="True"` so that they appear like so: `<Delete Files="$(TargetDir)\FabActUtil.exe" ContinueOnError="True"/>` I can finally get my solution to build and deploy reliably.

Not sure if anything bad will happen in the case that FabActUtil cannot be cleaned up properly but so far everything is looking good and saving me massive headaches from having to attempt building 20 times in a row before one will take.

**Comment by amanbha** [comment] 2016-08-22 18:18
Thanks for reporting the issue, will include the fix in our next release.

**Comment by amanbha** [comment] 2016-09-14 16:37
Fix for this will be in Service Fabric 5.3 release

**Comment by CassandraDied** [comment] 2016-09-28 21:44
While there is no fix, another workaround.
I've found that MSBuild is unable to delete files that it has copied previously because it has no rights.
Killing all the instances of MSBuild helped and next build all the files were deleted.

**Comment by dagrooms52** [comment] 2016-10-19 20:30
I noticed that the Delete nodes on the targets file were removed in 5.3.301, but the problem persists in my solution. I get the messages "Unable to delete FabActUtil.exe ... Access to the path is denied" as well as "Could not copy FabActUtil.exe to .../Debug/FabActUtil.exe because it is being used by another process." Running Service Fabric 5.3.301.9590 and SDK 2.3.301.9590.

**Comment by dagrooms52** [comment] 2016-10-19 20:54
Problem seems to persist in 5.3.301.9590 - I noticed the Delete nodes are removed from the targets file, so they are no longer an issue. Killing instances of MSBuild yielded no results. Output consists solely of this line: `build\Microsoft.ServiceFabric.Actors.targets(28,5): error MSB3073: The command ""packages\Microsoft.ServiceFabric.Actors.2.3.301\build\\FabActUtil.exe" /app:"etc.." exited with code -1.`

**Comment by amanbha** [comment] 2016-10-19 20:59
@dagrooms52 The error which you shared is different from this issue. Could you run the exact command out side of VS from a command prompt and share the error.

**Comment by dagrooms52** [comment] 2016-10-19 21:28
Running it outside of VS after building (with build failing) gives me:
`System.ArgumentException: An item with the same key has already been added.
   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary```2.Insert(TKey key, TValue value, Boolean add)
   at Microsoft.ServiceFabric.Actors.Generator.ManifestGenerator.Context.LoadExistingContents()
   at Microsoft.ServiceFabric.Actors.Generator.ManifestGenerator.Generate(Arguments arguments)
   at FabActUtil.Tool.GenerateOutput(ToolContext context)
   at FabActUtil.Program.Main(String[] args)`

**Comment by amanbha** [comment] 2016-10-19 22:39
Thanks, Looks like you have 2 default services with the same name in application manifest. Could you try running with removing one of them.

**Comment by dagrooms52** [comment] 2016-10-20 00:52
That fixed it - thanks for your help.

**Comment by amanbha** [comment] 2016-10-20 16:31
@dagrooms52 Could you help me understand how these 2 default services with same name got added in application manifest? I am trying to understand how our tooling can avoid it from happening in the first place.

**Comment by CassandraDied** [comment] 2016-10-20 17:03
@amanbha I had the same problem once. It is hard to reproduce, almost impossible: I added a new service, rebuilt the solution with errors and closed VS. Then, when I opened it again, I noticed that there is no service that I recently created in the solution. So I added it again, with the same name. That caused two default services in manifest file.

**Comment by amanbha** [comment] 2016-10-20 18:43
@CassandraDied  Thanks, that gives me some insight into it, was it an Actor or a Stateful/Stateless service.

**Comment by CassandraDied** [comment] 2016-10-20 18:48
@amanbha it was a Statefull service.

**Comment by amanbha** [comment] 2016-10-20 23:26
@CassandraDied Thanks for providing the info, I will look into fixing this behavior.

**Comment by dagrooms52** [comment] 2016-10-26 17:46
@amanbha I had manually written the new remoting service into the same project as another webservice. When the two services didn't play nicely in the same project, I split the project out, and Visual Studio generated another default service definition for me, hence the duplicate.

**Comment by amanbha** [comment] 2017-06-01 00:08
FabActUtil is now not copied to out folder after build. The fix has been available since 5.3.

**Closed by amanbha** 2017-06-01 00:08 UTC
Labels: bug, fix coming
