### ISSUE TITLE
Deployment issue after upgrading to 5.6.204

### ISSUE THREAD

**Issue by negberts** [Azure/service-fabric-issues#267] opened 2017-05-11 14:40 UTC
After upgrading Visual Studio 2017, The SDK and the nuget packages local deployment in Visual Studio is working fine, however, when trying to deploy in a visualstudio.com release pipeline, both with the vsts task as with the powershell command we receive an error:

```
2017-05-11T11:01:55.2707676Z ##[command]. 'E:\Agent02\_work\r1\a\Deployment - PIM\drop\SFPackage\Scripts\Deploy-FabricApplication.ps1' -PublishProfileFile ../PublishProfiles/Cloud-Dev.xml -ApplicationPackagePath ../Package -UnregisterUnusedApplicationVersionsAfterUpgrade 1
2017-05-11T11:02:12.7059951Z ##[error]Get-ServiceFabricApplicationType : Value does not fall within the expected range.
At C:\Program Files\Microsoft SDKs\Service 
Fabric\Tools\PSModule\ServiceFabricSDK\Publish-UpgradedServiceFabricApplication.ps1:195 char:16
+         $reg = Get-ServiceFabricApplicationType -ApplicationTypeName $names.Appl ...
+                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (Microsoft.Servi...usterConnection:ClusterConnection) [Get-ServiceFabri 
   cApplicationType], ArgumentException
    + FullyQualifiedErrorId : GetApplicationTypeErrorId,Microsoft.ServiceFabric.Powershell.GetApplicationType
```

An issue is also created in vsts-tasks repository, which suggests it has nothing to do with the upgrade since other people did not upgrade:
https://github.com/Microsoft/vsts-tasks/issues/4292

**Comment by njtrentacoste** [comment] 2017-05-11 17:55
I wanted to say that I'm also receiving this error for a standalone cluster.  I upgraded the SF version of the packages throughout the application but not the cluster itself (Updated Standalone cluster package not available yet).  Upon attempting to publish through VS 2017 (v15.2.26430.4), I receive this error.  I'm wondering if it's even possible to deploy an app with newer SF runtime than the cluster?

Thanks
```
8>Started executing script 'Deploy-FabricApplication.ps1'.
8>. 'C:\Work\...\Deploy-FabricApplication.ps1' -ApplicationPackagePath 'C:\Work\...\pkg\Debug' -PublishProfileFile 'C:\Work\...\PublishProfiles\Dev.xml' -DeployOnly:$false -ApplicationParameter:@{} -UnregisterUnusedApplicationVersionsAfterUpgrade $false -OverrideUpgradeBehavior 'None' -OverwriteBehavior 'SameAppTypeAndVersion' -SkipPackageValidation:$false -ErrorAction Stop
8>Get-ServiceFabricApplicationType : Value does not fall within the expected range.
8>At C:\Program Files\Microsoft SDKs\Service 
8>Fabric\Tools\PSModule\ServiceFabricSDK\Publish-NewServiceFabricApplication.ps1:227 char:16
8>+ ...      $reg = Get-ServiceFabricApplicationType -ApplicationTypeName $na ...
8>+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
8>    + CategoryInfo          : InvalidArgument: (Microsoft.Servi...usterConnection:ClusterConnection) [Get-ServiceFabri 
8>   cApplicationType], ArgumentException
8>    + FullyQualifiedErrorId : GetApplicationTypeErrorId,Microsoft.ServiceFabric.Powershell.GetApplicationType
```

**Comment by bishal-pdMSFT** [comment] 2017-05-11 19:07
Use latest SDK version
2.6.204.9494 and try to run PS command Get-ServiceFabricApplicationType on a cluster having version
5.5.216.0, I get exact same error.

**Comment by NCarlsonMSFT** [comment] 2017-05-11 20:44
The issue with the VSTS build is specific to a change on the Hosted VS2017 Agent that is being investigated. If your project can build in VS 2015 I recommend trying the Hosted Agent.

**Comment by negberts** [comment] 2017-05-12 06:38
Upgrading the cluster in Azure fixed the error for me.

**Comment by bishal-pdMSFT** [comment] 2017-05-12 06:40
@NCarlsonMSFT As I mentioned earlier, I get the same error without using VSTS as well. Isn't the problem with latest SDK version?

**Comment by VipulM-MSFT** [comment] 2017-05-12 06:45
Thank you for reporting the issue. We are aware of it and working on fixing this, we will be releasing updated SDK with the fix that will allow this PowerShell command to be able to talk to the previous clusters. The workaround is to update the cluster or go back to using the 5.5 SDK. 

We sincerely apologize for the issue and are working to fix this as soon as possible.

**Comment by njtrentacoste** [comment] 2017-05-12 13:13
Thanks for the quick responses.  Are you saying that deploying an application with newer sdk/runtime than the cluster is supported?  Because I could understand if it wasn't.

Thanks

**Comment by oanapl** [comment] 2017-05-12 15:33
@njtrentacoste, newer clients should work with older clusters as long as no new functionality (introduced in the newer version) is called. Like @VipulM-MSFT said, we will be fixing this bug and we will get it out as soon as we can.
The command in this SDK version will work against 5.6.x.x clusters, if upgrading the 5.5 cluster is an option for you.  Otherwise, you can use 5.5 to talk to the 5.5 cluster.

**Comment by njtrentacoste** [comment] 2017-05-12 17:31
Perfect!  Thanks for clearing that up @oanapl.

**Comment by AndriusDvilevicius** [comment] 2017-05-16 07:00
I have setup a new 5.5.216.0 cluster and installed 2.6.204 SDK/Runtime for VS2015.
I get Get-ServiceFabricApplicationType : Value does not fall within the expected range. when trying to publish to the cluster. 
Running Get-ServiceFabricApplicationType on development machine returns same error, however running same command on cluster machine works fine.
What workaround could I use?

**Comment by birdemily** [comment] 2017-05-16 10:09
i have the same issue. My sdk is 2.6.204, runtime is 5.6.204. I check all are latest version for vs2017.
The cluster i want to delpoy to is 5.5.216.0.
The error message is:
2>Get-ServiceFabricApplicationType : Value does not fall within the expected range.
2>At C:\Program Files\Microsoft SDKs\Service Fabric\Tools\PSModule\ServiceFabricSDK\Publish-NewServiceFabricApplication.p
2>s1:227 char:16
2>+ ...      $reg = Get-ServiceFabricApplicationType -ApplicationTypeName $na ...

Since all things are latest version, what can i do?

**Comment by njtrentacoste** [comment] 2017-05-16 12:56
@Brnwashed @birdemily  What you are describing is the bug.  MS is working to resolve it.  Until it's resolved, or MS releases the updated standalone cluster creation package, the machine you deploy from will need to have the older SDK/Runtime installed.  The application can have the latest packages installed.  You'll need to uninstall the 2.6 SDK/5.6 Runtime from the deployment machine and install the 2.5 SDK/5.5 Runtime.  This will allow you to deploy again.

**Comment by oanapl** [comment] 2017-05-16 16:44
Update: the issue is fixed in 5.6.210.9494 and SDK 2.6.210, which will become available soon.

**Comment by Fluwit** [comment] 2017-05-16 16:47
Thanks for the heads-up!

Faced this issue this afternoon, just managed to complete a deployment from a 2.5 supported IDE. Will try it once it's released.

**Comment by MECLab-Keags** [comment] 2017-05-16 21:45
@birdemily, @Brnwashed Try and upgrade your cluster to 5.6.
I was able to deploy after upgrading, even though my SF projects were still targeting the 5.5 runtime and 2.5 sdk.

**Comment by birdemily** [comment] 2017-05-18 07:29
@njtrentacoste thanks for the reply.

**Comment by hiraldesai** [comment] 2017-05-18 16:47
@oanapl - how soon? Sorry, not trying to rush but just wondering if it's a "couple of days" soon or "couple of weeks" soon so I can decide if I should downgrade my dev environment. 😄

**Comment by oanapl** [comment] 2017-05-18 16:51
We have the build and we are trying to push it out but we are hitting some unrelated deployment issues. Current ETA is next week.

**Comment by hiraldesai** [comment] 2017-05-18 19:13
Thanks for clarifying @oanapl, I will just wait then. Good luck with the deployment issues!

**Comment by gescarra** [comment] 2017-05-19 00:03
Thank you @oanapl. This caused issues at the Azure Boot Camp Hackathon when publishing the app using VS 2017 and the latest SDK. Upgrading the cluster manually to the latest version fixed the issue.

**Comment by andrewdmoreno** [comment] 2017-05-19 19:07
Does anyone know how to get the older 2.5/5.5 version? All download links seem to always cause the latest version to be downloaded.

**Comment by njtrentacoste** [comment] 2017-05-19 19:09
@andrewdmoreno MS Web Platform Installer has em.  That's what I've been using.

**Comment by andrewdmoreno** [comment] 2017-05-19 19:10
@njtrentacoste You're awesome, thanks!

**Comment by oanapl** [comment] 2017-05-24 22:24
The release that has the fix is now available, see https://blogs.msdn.microsoft.com/azureservicefabric/2017/05/24/release-of-sdk-2-6-210-and-runtime-5-6-210-refresh-for-windows-and-sdk-2-7-and-runtime-5-7-preview/

**Closed by oanapl** 2017-05-24 22:24 UTC
Labels: bug, fix coming
