### ISSUE TITLE
FabricDnsService is not preferred DNS server on the node.

### ISSUE THREAD

**Issue by artsai** [Azure/service-fabric-issues#496] opened 2017-09-28 23:56 UTC
I installed version  6.0.211.9494 on my local 1 Node 
fabric:/System/DnsService is giving this warning. 
"FabricDnsService is not preferred DNS server on the node."
I have tried to reset the cluster, it went away then it came back on. 
I'm running Windows 10 Pro. 
Please let me know what I should do.
Thank you, 
Art

**Comment by clazarr** [comment] 2017-09-29 18:21
I am seeing the same behavior with the Service Fabric Explorer reporting a health warning for the FabricDnsService after installing the v6.0.211 runtime and SDK using the Web Platform Installer on Windows 10 Pro v1703.

**Comment by milvuko** [comment] 2017-09-29 21:50
DnsService is by default set as a preferred DNS server on the node (Windows only for now), which means that the IP address of the node is inserted as the first DNS address in the DNS chain.  Current DNS chain can be inspected by looking at the output of "ipconfig /all" command, "DNS Servers" section. In case the IP address of the node is not in the chain, the warning "FabricDnsService is not preferred DNS server on the node." is displayed.
The warning happens when DNS chain is modified while the cluster is running. This occurs mostly on OneBox clusters which are running on mobile devices (laptops). When the device connects to a different network (laptop is attached to a new wireless network for example), network settings are changed due to DHCP, and DNS chain is changed as well. 
Note that ServiceFabric does not monitor the DNS chain for changes, and therefore doesn't recover automatically when the change happens. This is a bug that is being fixed.

The mitigation is to restart the OneBox cluster. On restart, the cluster populates the DNS chain of the node again.

Also, if the DnsService is needed only for containers and not for regular services, then DnsService doesn't have to be set as a preferred DNS on the node. There is a fabric settings that can be set to disable the feature:
```
                "fabricSettings": [
                    {
                        "name": "DnsService",
                        "parameters": [
                            {
                                "name": "IsEnabled",
                                "value": "true"
                            },
                            {
                                "name": "SetAsPreferredDns",
                                "value": "false"
                            }
                    }]
```
Note that settings flag SetAsPreferredDns to false will disable DnsService for regular services. DnsService will continue working for containers. Essentially, setting the flag to false doesn't modify the DNS chain on the node, but does modify the DNS chain of the container.

**Comment by francescocristallo** [comment] 2017-10-09 22:22
I have the same problem, v6.0.211 runtime SDK on Windows 10 Pro, resetting the cluster have no effect on the DNS chain visible using ipconfig/all command.

During Debug, when connecting to a stateful service from a stateless one using an IService interface, an exception is raised:

"Client is trying to connect to invalid address http://localhost:58532/...."

**Comment by milvuko** [comment] 2017-10-09 22:39
Hi @francescocristallo, you raised 2 unrelated issues: DnsService warning and IService communication issue. Communication through IService is not dependent on DnsService.
It would be helpful if you could share the traces that have type ConfigureNodeForDnsService in order to figure out why OneBox restart is not mitigating the warning issue.

**Comment by IgorYastrebov** [comment] 2017-10-24 10:07
I have same issue on my laptop. latest Win10
1) disable all network interfaces, leave only one
2) Reset local cluster, wait for at least 1 minute to monitor empty cluster to ensure DNSService is OK
3) deploy your app, monitor for another minute

**Comment by joaocpribeiro** [comment] 2017-12-07 13:13
@milvuko I have the same issue. I have now a new machine (Windows 10 Pro) and installed Service Fabric SDK 2.8.232. Some time (half minute?) after I start/reset the cluster, the System/DnsService has the warning message "FabricDnsService is not preferred DNS server on the node.".
I tried to install another SDK version (2.7.221) and I added a firewall rule to make sure it is not blocking SF (port 53 - UDP, which is the endpoint of the System/DnsService replica), but the problem remains.
I do not see any DNS-specific error on C:\SfDevCluster\Log\Traces.
Where can I find a more specified error message?
Is there any known workaround to make my SF application work?

**Comment by hdaniel93** [comment] 2017-12-14 22:16
So this error is coming up in a project where it is a stateless api that obtains information from a reliable dictionary in a stateful service and any api request gives a 500 error.Is this why i get a 500 error?Why does the error happen?Is it down to my configuration of hardware/OS?

**Comment by andrew-laughlin** [comment] 2017-12-19 16:01
I see this error on my local cluster with no applications. SF version is 6.0.232.9494.

**Comment by milvuko** [comment] 2018-01-23 18:45
Fixed in SF v6.1.

**Closed by milvuko** 2018-01-23 18:45 UTC
Labels: fix coming

**Comment by wasabii** [comment] 2018-02-19 15:51
On 6.1. Still having the issue. My NICs are DHCP.

**Comment by IgorYastrebov** [comment] 2018-02-19 17:46
pls re-open this issue. 6.1 SDK the issue is there!
laptop, several net connections. Reproduced when I leave 1 connection only.
And now, the issue become even worse than in 6.0 - limit LAN connections and resetting local cluster not help :(

**Comment by spottedmahn** [comment] 2018-02-20 21:43
6.1 fixed it for me, thanks!

![image](https://user-images.githubusercontent.com/14079228/36450830-3a3449cc-165d-11e8-89e2-a17d34406b53.png)

**Comment by Marusyk** [comment] 2018-02-26 11:28
Still got `FabricDnsService is not preferred DNS server on the node.`  

6.1.456.9494

**Comment by alexmarshall132** [comment] 2018-03-10 06:24
Please re-open this issue. It is not solved as of Service Fabric 6.1.467.9494. This is on a fresh install of Windows 10 mind you:

![image](https://user-images.githubusercontent.com/1800742/37239037-0c9a7b70-23f1-11e8-97a7-7e25241b51e3.png)

**Comment by tbertenshaw** [comment] 2018-03-20 08:56
![image](https://user-images.githubusercontent.com/2010002/37644635-589c2518-2c1c-11e8-86dd-9f4a848df79f.png)

Also present in latest Refresh 6.1.472.9494

**Comment by vladislav-karamfilov** [comment] 2018-04-15 11:53
I also see this with latest version 6.1.480

**Comment by KTazayan** [comment] 2018-04-20 08:30
The same situation for me too.

**Comment by ninzavivek** [comment] 2018-04-20 18:45
Are you saying DNS service is not able to heal from this error ever?

**Comment by KTazayan** [comment] 2018-04-27 08:56
I've tried 6.2 and everything seems to be ok.

**Comment by lAnubisl** [comment] 2020-10-20 14:30
Please re-open
![image](https://user-images.githubusercontent.com/1249671/96600656-d420ad00-12f9-11eb-88dd-9340e259eff9.png)
