### ISSUE TITLE
Error with Backup Restore service

### ISSUE THREAD

**Issue by Wackymax** [Azure/service-fabric-issues#1370] opened 2018-11-26 13:57 UTC
I’ve configured the Service Fabric backup and restore service to create periodic backups.

My target service displays an error message:
> “Failed to take periodic backup for this partition with error:\nSystem.Fabric.FabricException: An error > occurred during this operation. Please check the trace logs for more details. ---> System.Runtime.InteropServices.COMException: Exception from HRESULT: 0x80071C7D
at System.Fabric.BackupRestore.Interop.NativeBackupRestoreRuntime.IFabricBackupRestoreAgent.EndUploadBackup(IFabricAsyncOperationContext context)”

I looked at the event logs on the virtual machine and I get this error:

> Can't ACL BackupRestoreService/SecretEncryptionCertThumbprint, ErrorCode E_INVALIDARG
> Failed to get private key file
> Failed to open store '' at LocalMachine: E_INVALIDARG

I tried various certificates for the `SecretEncryptionCertThumbprint` including the cluster certificate but keep on getting the same error.

**Comment by hrushib** [comment] 2018-11-26 17:54
@Wackymax, sorry to see that the service is failing to work. Is this a cluster created in Azure? if so please provide full URL of the cluster's https endpoint for further investigation.

**Comment by Wackymax** [comment] 2018-11-27 05:40
Hi @hrushib,

It is an Azure cluster yes. azu-f-sa-u-cluster.westeurope.cloudapp.azure.com

**Comment by hrushib** [comment] 2018-11-28 14:57
@Wackymax, we are investigating the root cause for the error reported by you, and will fix it soon.

Meanwhile, to fix the above issue please configure the store name for the _secret encrytion certificate_ to `My` in the cluster template used to create this cluster and then do the cluster upgrade. To add this configuration, update the `fabricSettings` section of your cluster's template and add one more parameter to `parameters` list with `name` equal to `SecretEncryptionCertX509StoreName` and `value` set to `My`. After the change, fabric settings section will look like following. 
```json
    "properties": {
        ...
        "addonFeatures": ["BackupRestoreService"],
        "fabricSettings": [{
            "name": "BackupRestoreService",
            "parameters":  [{
                "name": "SecretEncryptionCertThumbprint",
                "value": "[Thumbprint]"
            },
           {
                "name": "SecretEncryptionCertX509StoreName",
                "value": "My"
            }]
        }
        ...
    }
```

Do let me know if you face same issues despite adding this configuration.

**Comment by Wackymax** [comment] 2018-11-29 07:06
Hi @hrushib,

Thank you for the suggestion. Everything appears to be working correctly now. Would it be possible to document the parameters somewhere to help others try to debug and fix issue they may encounter themselves?

Thanks again for the help.

**Comment by raunakpandya** [comment] 2018-12-05 19:58
Closing the issue as its resolved.

**Closed by raunakpandya** 2018-12-05 19:58 UTC
Labels: bug, investigating
