### ISSUE TITLE
Activation error - Exit code 7148

### ISSUE THREAD

**Issue by jackbond** [Azure/service-fabric-issues#406] opened 2017-08-17 18:25 UTC
I have a service fabric cluster which hosts numerous applications. One of the applications has a service type where the service is created, runs for a bit, and then is deleted. Everything works great, but the cluster virtually always has its state set to error because there will be a few of these in the "Unhealthy evaluations" section.

Error event: SourceId='System.Hosting', Property='CodePackageActivation:Code:EntryPoint'. There was an error during CodePackage activation.The service host terminated with exit code:7148

I've wrapped both the program's main and RunAsync in exception handlers, but never see anything in analytics. Is there any way to look up what exit code 7148 means? Thanks.

**Comment by masnider** [comment] 2017-08-24 21:59
@jackbond usually there's information in the event log about what happened. 7148 is Service Fabric intentionally terminating the process due to some error - usually in this case if there's no exception information (did you do the last chance exception handler?) then it means that there's some misconfiguration that is making it so that SF can't launch the process correctly. Cert configuration is a common culprit but there can be others. 

I'm also marking this as an enhancement since ideally we should be pushing that error information into the same error health report, rather than just tossing back the error code.

**Comment by nareshkhatri81** [comment] 2017-09-19 03:54
+1. i tried to look into event viewer logs but couldnt able to find any error. is there any other places i can see traces logs ?

**Comment by VipulM-MSFT** [comment] 2017-10-25 22:00
If you have a large number of applications we might be running out of desktop heap trying to fork the processes. Change EnableActivateNoWindow setting under Hosting section to be true.

**Comment by karunasagark** [comment] 2017-10-26 21:27
What does "EnableActivateNoWindow" setting imply?

**Comment by harahma** [comment] 2017-10-26 21:30
By default when SF launches the service exe, it uses desktop heap which allows SF to send Ctrl-C signal to process to gracefully bring it down during failover scenarios. With "EnableActivateNoWindow" set to true, the service exe will not consume desktop heap and SF will then directly terminate the service process during failover.

**Comment by masnider** [comment] 2018-01-03 22:56
@jackbond were you able to figure out the cause based on the feedback here? We haven't heard back from you in a while, so for now we're going to close this issue down. If you have any further questions or need more help with this, then just reopen this issue or create a new one.

**Closed by masnider** 2018-01-03 22:56 UTC
Labels: enhancement, investigating, question
