### ISSUE TITLE
ReminderLoadInProgressException In Actors

### ISSUE THREAD

**Issue by ahesami** [Azure/service-fabric-issues#1696] opened 2020-09-02 07:33 UTC
Sometimes receive 'ReminderLoadInProgressException' when getting a reminder on an actor.

Couldn't find any documentation on this exception. 

- When would you get this exception on an actor ?
- What should you do to avoid getting this exception?
- When getting this exception, what are the steps get a reminder on an actor? Retry?
- It seems the actor manager loads all the reminders of actors on a partition before letting actors to get a remidner, is this correct?

Thanks

**Comment by amanbha** [comment] 2020-09-02 15:33
@ahesami You are correct in your observation, Actor service partition replica loads reminder from the disk when it changes role to primary, during this duration reminder operations are not permitted. When this exception is thrown the operation can be retried, the exception message mentions that operation can be retried later. Usually, the cause for this issue is slow disk or too many reminders for the actor int he partition.

I am closing it, feel free to reopen if you have more questions reg. this.

**Closed as completed by amanbha** 2020-09-02 15:33 UTC
