### ISSUE TITLE
FabricApplicationGateway.exe unexpectedly crashed on most boxes of cluster

### ISSUE THREAD

**Issue by xela30** [Azure/service-fabric-issues#634] opened 2017-11-14 15:48 UTC
Windows Standalone Cluster 5.7.221.9494
Windows Server 2016

That caused a downtime in Production.
Please advise.

Faulting application name: FabricApplicationGateway.exe, version: 5.7.221.9494, time stamp: 0x59cab789
Faulting module name: FabricApplicationGateway.exe, version: 5.7.221.9494, time stamp: 0x59cab789
Exception code: 0xc0000005
Fault offset: 0x0000000000044107
Faulting process id: 0x314
Faulting application start time: 0x01d3587623d3daf0
Faulting application path: C:\Program Files\Microsoft Service Fabric\bin\Fabric\Fabric.Code\FabricApplicationGateway.exe
Faulting module path: C:\Program Files\Microsoft Service Fabric\bin\Fabric\Fabric.Code\FabricApplicationGateway.exe
Report Id: 1a180958-fca7-4f0e-ac89-e2f806f1461a
Faulting package full name: 
Faulting package-relative application ID: 
*********************************************************************************************
Version=1
EventType=APPCRASH
EventTime=131551419759668014
ReportType=2
Consent=1
UploadTime=131551438797156555
ReportIdentifier=fa0b7e61-c944-11e7-90f0-005056844b17
IntegratorReportIdentifier=1a180958-fca7-4f0e-ac89-e2f806f1461a
NsAppName=FabricApplicationGateway.exe
AppSessionGuid=00000314-0000-0011-f0da-d3237658d301
TargetAppId=W:0006a3aa3677c142219fb21cf835f2afb7a700000904!0000b34a84ab2c889990a93fd82b72673d8ff5d9db09!FabricApplicationGateway.exe
TargetAppVer=2017//09//26:20:24:41!703226!FabricApplicationGateway.exe
BootId=4294967295
Response.type=4
Sig[0].Name=Application Name
Sig[0].Value=FabricApplicationGateway.exe
Sig[1].Name=Application Version
Sig[1].Value=5.7.221.9494
Sig[2].Name=Application Timestamp
Sig[2].Value=59cab789
Sig[3].Name=Fault Module Name
Sig[3].Value=FabricApplicationGateway.exe
Sig[4].Name=Fault Module Version
Sig[4].Value=5.7.221.9494
Sig[5].Name=Fault Module Timestamp
Sig[5].Value=59cab789
Sig[6].Name=Exception Code
Sig[6].Value=c0000005
Sig[7].Name=Exception Offset
Sig[7].Value=0000000000044107
DynamicSig[1].Name=OS Version
DynamicSig[1].Value=10.0.14393.2.0.0.272.7
DynamicSig[2].Name=Locale ID
DynamicSig[2].Value=1033
DynamicSig[22].Name=Additional Information 1
DynamicSig[22].Value=eb33
DynamicSig[23].Name=Additional Information 2
DynamicSig[23].Value=eb3305885595cf49d4e2e82e38693c08
DynamicSig[24].Name=Additional Information 3
DynamicSig[24].Value=f974
DynamicSig[25].Name=Additional Information 4
DynamicSig[25].Value=f974df6876579fed443a9bd715356871
UI[2]=C:\Program Files\Microsoft Service Fabric\bin\Fabric\Fabric.Code\FabricApplicationGateway.exe
UI[5]=Check online for a solution (recommended)
UI[6]=Check for a solution later (recommended)
UI[7]=Close
UI[8]=FabricApplicationGateway stopped working and was closed
UI[9]=A problem caused the application to stop working correctly. Windows will notify you if a solution is available.
UI[10]=&Close
LoadedModule[0]=C:\Program Files\Microsoft Service Fabric\bin\Fabric\Fabric.Code\FabricApplicationGateway.exe
LoadedModule[1]=C:\Windows\SYSTEM32\ntdll.dll
LoadedModule[2]=C:\Windows\System32\KERNEL32.DLL
LoadedModule[3]=C:\Windows\System32\KERNELBASE.dll
LoadedModule[4]=C:\Windows\System32\ADVAPI32.dll
LoadedModule[5]=C:\Windows\System32\msvcrt.dll
LoadedModule[6]=C:\Windows\System32\sechost.dll
LoadedModule[7]=C:\Windows\System32\RPCRT4.dll
LoadedModule[8]=C:\Windows\System32\ucrtbase.dll
LoadedModule[9]=C:\Windows\System32\WS2_32.dll
LoadedModule[10]=C:\Program Files\Microsoft Service Fabric\bin\Fabric\Fabric.Code\VCRUNTIME140.dll
LoadedModule[11]=C:\Windows\SYSTEM32\IPHLPAPI.DLL
LoadedModule[12]=C:\Program Files\Microsoft Service Fabric\bin\Fabric\Fabric.Code\MSVCP140.dll
LoadedModule[13]=C:\Windows\SYSTEM32\HTTPAPI.dll
LoadedModule[14]=C:\Windows\SYSTEM32\websocket.dll
LoadedModule[15]=C:\Windows\SYSTEM32\USERENV.dll
LoadedModule[16]=C:\Windows\SYSTEM32\NETAPI32.dll
LoadedModule[17]=C:\Windows\System32\profapi.dll
LoadedModule[18]=C:\Windows\SYSTEM32\dbghelp.dll
LoadedModule[19]=C:\Windows\SYSTEM32\CRYPTBASE.DLL
LoadedModule[20]=C:\Windows\System32\CRYPT32.dll
LoadedModule[21]=C:\Windows\System32\MSASN1.dll
LoadedModule[22]=C:\Windows\System32\bcryptPrimitives.dll
LoadedModule[23]=C:\Windows\System32\USER32.dll
LoadedModule[24]=C:\Windows\SYSTEM32\Secur32.dll
LoadedModule[25]=C:\Windows\System32\win32u.dll
LoadedModule[26]=C:\Windows\System32\GDI32.dll
LoadedModule[27]=C:\Windows\System32\gdi32full.dll
LoadedModule[28]=C:\Windows\System32\SHLWAPI.dll
LoadedModule[29]=C:\Windows\System32\combase.dll
LoadedModule[30]=C:\Windows\SYSTEM32\WINHTTP.dll
LoadedModule[31]=C:\Program Files\Microsoft Service Fabric\bin\Fabric\Fabric.Code\FabricResources.dll
LoadedModule[32]=C:\Program Files\Microsoft Service Fabric\bin\Fabric\Fabric.Code\FabricCommon.dll
LoadedModule[33]=C:\Program Files\Microsoft Service Fabric\bin\Fabric\Fabric.Code\FabricAad.Client.dll
LoadedModule[34]=C:\Windows\System32\WINTRUST.dll
LoadedModule[35]=C:\Windows\SYSTEM32\bcrypt.dll
LoadedModule[36]=C:\Windows\SYSTEM32\Cabinet.dll
LoadedModule[37]=C:\Windows\SYSTEM32\XmlLite.dll
LoadedModule[38]=C:\Windows\SYSTEM32\VERSION.dll
LoadedModule[39]=C:\Windows\SYSTEM32\mscoree.dll
LoadedModule[40]=C:\Windows\SYSTEM32\DSROLE.DLL
LoadedModule[41]=C:\Windows\SYSTEM32\SSPICLI.DLL
LoadedModule[42]=C:\Windows\Microsoft.NET\Framework64\v4.0.30319\mscoreei.dll
LoadedModule[43]=C:\Windows\System32\kernel.appcore.dll
LoadedModule[44]=C:\Windows\SYSTEM32\ondemandconnroutehelper.dll
LoadedModule[45]=C:\Windows\system32\mswsock.dll
LoadedModule[46]=C:\Windows\SYSTEM32\DNSAPI.dll
LoadedModule[47]=C:\Windows\System32\NSI.dll
LoadedModule[48]=C:\Windows\System32\rasadhlp.dll
LoadedModule[49]=C:\Windows\System32\fwpuclnt.dll
LoadedModule[50]=C:\Windows\system32\msv1_0.DLL
LoadedModule[51]=C:\Windows\SYSTEM32\NtlmShared.dll
LoadedModule[52]=C:\Windows\SYSTEM32\cryptdll.dll
LoadedModule[53]=C:\Windows\SYSTEM32\webio.dll
LoadedModule[54]=C:\Windows\SYSTEM32\WINNSI.DLL
State[0].Key=Transport.DoneStage1
State[0].Value=1
FriendlyEventName=Stopped working
ConsentKey=APPCRASH
AppName=FabricApplicationGateway
AppPath=C:\Program Files\Microsoft Service Fabric\bin\Fabric\Fabric.Code\FabricApplicationGateway.exe
NsPartner=windows
NsGroup=windows8
ApplicationIdentity=7568C55094D5EBF30634DEAD4CDF0403
MetadataHash=22820098

**Comment by kavyako** [comment] 2017-11-27 15:12
could you share the crash dump or the logs?
Was it working successfully prior to the crash?

**Comment by kavyako** [comment] 2017-11-27 16:23
@BharatNarasimman @vturecek @sridmad FYI.

**Comment by xela30** [comment] 2017-12-06 11:40
I will check the company policy and grab and share the dump next time if possible.
It was working correctly prior to the crash.
Most likely there were no requests at a time of failure.
Reverse proxy is listening on http (19081 port).
My best guess it's somehow collide with SplunkUniversalForwarder service which collects and send performance counters to remote server.
Issue appeared soon after configuration of splunk forwarder has been changed (inputs.conf).
For instance, entry [perfmon://CPU Load] was changed to [perfmon://Windows__Processor].
However that might be just a coincidence.

**Comment by xela30** [comment] 2017-12-08 10:17
Please find exception analysis generated by windbg above. Let me know if you need some extra information.

**Comment by xela30** [comment] 2017-12-11 14:22
Any update on this?

**Comment by sridmad** [comment] 2017-12-11 19:27
@xela30 we will take a look at the issue today and get back to you if we need more information.

**Comment by sridmad** [comment] 2017-12-12 21:20
@xela30 haven't got to the bottom of it will continue to investigate and get back to when I have more information or the root cause..

**Comment by xela30** [comment] 2017-12-13 00:28
thanks

**Comment by xela30** [comment] 2017-12-14 21:58
JFYI, upgraded cluster to 6.0.232.9494 version and still see the same issue.
BTW, failure is cascade. FabricApplicationGateway.exe processes are crashing on multiple boxes of cluster one by one within ~30 seconds and then quickly get back up.

**Comment by sridmad** [comment] 2017-12-15 00:38
@xela30 , Thanks for the update.

To clarify, process is crashing within ~30 seconds, they crash, restart and crash again?

Question about the exception information above. Did you set the symbol path to include Microsoft Public symbols before getting the stack? If not can run the following commands in the debugger and capture the exception information again and send the information?

.symfix+ https://msdl.microsoft.com/download/symbols
.reload
.sympath

The last command should show the path specified in the first command added to symbol search path
.

Thanks,
-sridhar

**Comment by xela30** [comment] 2017-12-15 15:12
@sridmad Process is crashing on one box then is several seconds on another one and so on. FabricApplicationGateway.exe restarts within a minute after the crash and working well until next one crash in a day or so.
Typically we have up to 4 or 5 boxes affected during one incident. (Total number of boxes in cluster is 9).

I'll try that commands and get back to you. Thanks.

**Comment by xela30** [comment] 2017-12-15 16:07
@sridmad FYI

0:006> .symfix+ https://msdl.microsoft.com/download/symbols
*** ERROR: Symbol file could not be found.  Defaulted to export symbols for ntdll.dll -

**Comment by xela30** [comment] 2017-12-15 18:06
@sridmad Adding  https://msdl.microsoft.com/download/symbols doesn't change exception analysis results at all as there is no pdb for FabricApplicationGateway.exe out there.

FYI, here is a log of .reload:

0:006> .reload /f FabricApplicationGateway.exe
SYMSRV:  BYINDEX: 0x6
         c:\cache*http://msdl.microsoft.com/download/symbols
         FabricApplicationGateway.pdb
         188EB95FA5DB4729B8D76D101FDE22AA2
SYMSRV:  UNC: c:\cache\FabricApplicationGateway.pdb\188EB95FA5DB4729B8D76D101FDE22AA2\FabricApplicationGateway.pdb - path not found
SYMSRV:  UNC: c:\cache\FabricApplicationGateway.pdb\188EB95FA5DB4729B8D76D101FDE22AA2\FabricApplicationGateway.pd_ - path not found
SYMSRV:  UNC: c:\cache\FabricApplicationGateway.pdb\188EB95FA5DB4729B8D76D101FDE22AA2\file.ptr - path not found
SYMSRV:  HTTPGET: /download/symbols/index2.txt
SYMSRV:  HttpQueryInfo: 80190190 - HTTP_STATUS_BAD_REQUEST
SYMSRV:  HTTPGET: /download/symbols/FabricApplicationGateway.pdb/188EB95FA5DB4729B8D76D101FDE22AA2/FabricApplicationGateway.pdb
SYMSRV:  HttpQueryInfo: 80190194 - HTTP_STATUS_NOT_FOUND
SYMSRV:  HTTPGET: /download/symbols/FabricApplicationGateway.pdb/188EB95FA5DB4729B8D76D101FDE22AA2/FabricApplicationGateway.pd_

SYMSRV:  HttpQueryInfo: 80190194 - HTTP_STATUS_NOT_FOUND
SYMSRV:  HTTPGET: /download/symbols/FabricApplicationGateway.pdb/188EB95FA5DB4729B8D76D101FDE22AA2/file.ptr
SYMSRV:  HttpQueryInfo: 80190194 - HTTP_STATUS_NOT_FOUND
SYMSRV:  RESULT: 0x80190194
DBGHELP: E:\bt\858872\repo\out\retail-amd64\FabricApplicationGateway\FabricApplicationGateway.pdb - file not found
*** ERROR: Module load completed but symbols could not be loaded for FabricApplicationGateway.exe
DBGHELP: FabricApplicationGateway - no symbols loaded

************* Symbol Loading Error Summary **************
Module name            Error
FabricApplicationGatew 0x80190194 - Not found (404). : srv*c:\cache*http://msdl.microsoft.com/download/symbols

************************************************************


Let me know if I'm missing something or can do anything else for you.

**Comment by sridmad** [comment] 2017-12-15 22:44
@xela30 , Taking a look at the missing symbols.

**Comment by xela30** [comment] 2017-12-19 12:44
Hi, @sridmad. Just a friendly reminder. Is there any updates?

**Comment by xela30** [comment] 2017-12-21 16:32
@sridmad Is there any file share where I can leave a full dump file for you?

**Comment by sridmad** [comment] 2017-12-27 18:01
@xela30 , sorry for the delay, I have been out of office. Let me check about sending dump file to us and get back to you later today.

**Comment by sridmad** [comment] 2017-12-28 17:36
@xela30 , With most people out of office it is taking longer to get hold of the process to get dumps from customers. Will get back to you as soon as I get hold of the details.

Thanks,
-sridhar

**Comment by sridmad** [comment] 2017-12-28 18:21
@xela30 , the easiest way to get the dump to us to open a CSS support issue. Following are the details.

open a ticket for professional support on Microsoft support portal - http://support.microsoft.com/oas/default.aspx?prid=16146

Please include a link to the GitHub issue in the details. Once the support issue is created, Support engineer will create a location to upload dump files.

Please let me know the support ticket number so I can follow up as well.

Thanks,
-sridhar

**Comment by xela30** [comment] 2018-01-10 15:53
@sridmad, support request number is 118011017440599.

**Comment by kavyako** [comment] 2018-01-11 14:52
@xela30  Thank you for sharing the dump. 

We have fixed this issue in 6.1, this is a bug in the reverse proxy where it fails to handle requests with large URL lengths, in this case, the URL length was 8858 bytes.

URL was something like http://<domain:port>/app/rst/dashboard/client/<!DOCTYPE html PUBLIC -/W3C/DTD XHTML 1.0 Transitional/EN http:/www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd><html xmlns=http:/www.w3.org/1999/xhtml><head id=Head1>.....

**Comment by kavyako** [comment] 2018-02-09 18:40
Closing the issue as it is fixed.

**Closed by kavyako** 2018-02-09 18:40 UTC
