### ISSUE TITLE
service fabric stateless service run netstandard 2.0 error

### ISSUE THREAD

**Issue by zxarcg** [Azure/service-fabric-issues#412] opened 2017-08-21 07:39 UTC
I have created a service fabric application in vs 2017, the only service is a stateless service , and this service  is referenced a netstandard 2.0 library . after service is started , the application throw a exception,  mainly info as followed: 
"exception": "System.IO.FileNotFoundException: Could not load file or assembly 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The system cannot find the file specified.
      File name: 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'
         at Stateless1.Stateless1.<RunAsync>d__2.MoveNext()
         at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine)
         at Stateless1.Stateless1.RunAsync(CancellationToken cancellationToken)
         at Microsoft.ServiceFabric.Services.Runtime.StatelessService.Microsoft.ServiceFabric.Services.Runtime.IStatelessUserServiceInstance.RunAsync(CancellationToken cancellationToken)
         at Microsoft.ServiceFabric.Services.Runtime.StatelessServiceInstanceAdapter.<ExecuteRunAsync>d__18.MoveNext()

Service Fabric Version: 2.7.198

**Comment by jahmai** [comment] 2017-08-21 12:57
I'm getting the same. The sfproj Package doesn't seem to copy a large number of dll's from NETStandard across, including netstandard.dll. Manually adding those dll's to the project as items and marking them "Copy Always" does cause them to be copied and the service will run but it's a rabbit hole.

**Comment by caserzer** [comment] 2017-08-21 16:31
I got the same issue, the NETSTANDARD dll are missing in pkg folder

**Comment by jahmai** [comment] 2017-08-21 23:05
[1.txt](https://github.com/Azure/service-fabric-issues/files/1240346/1.txt)
[2.txt](https://github.com/Azure/service-fabric-issues/files/1240347/2.txt)

These files are the difference between the Service.csproj project bin folder and the Deployment.sfproj pkg folder. Not only is netstandard.dll missing on one side, but so are a tonne of other assemblies from the NETStandard.Library.

If I manually copy netstandard.dll into the package, it will at least get to the service boot strap, but then fail with the next missing reference, which for me is System.Runtime.dll.

**Comment by caserzer** [comment] 2017-08-22 06:16
The simplest workaround is create a asp.net core empty project, modify the class which inherit the StatelessService

**Comment by jahmai** [comment] 2017-08-22 12:26
@caserzer Interesting, I'll try that...

**Comment by jahmai** [comment] 2017-08-22 13:47
@caserzer Yep, your suggestion worked perfectly. That should totally be the default template for Stateless/Stateful services!

**Comment by vturecek** [comment] 2017-08-24 17:38
@jahmai we're moving in that direction with full .NET Standard 2.0 support soon.

**Comment by ToyMakerGR** [comment] 2017-09-21 17:08
@caserzer I did not understand your answer. Could you please elaborate? This also happens to me on a variety of services, right now I have encountered the problem on an Actor SF service. Thank you.

**Comment by ThiemeNL** [comment] 2017-10-04 10:29
Same issue here. 
I added the netstandard nuget to the framework project, and I see that the netstandard dll is in my bin folder. But it is not copied to service fabric pkg folder. So I got the exception.

**Comment by gnegno84** [comment] 2017-10-06 12:52
Same issue for me. I've got lot of services and all of them are not working. 
Expanding the services in the service fabric project shows allo project icons with a yellow triangle.
I'am also having issues with System.Net.Http and System.Security.Cryptography.X509Certificates libraries in services.
Can't understand why

**Comment by tanwarsatya** [comment] 2017-11-09 00:59
Any update on this, I am dealing with same issue after trying to reference a .net standard 2.0 poco class library.

**Comment by fleed** [comment] 2017-11-22 14:14
I'm experiencing the same problem. Any update on this?

**Comment by dipinbehl** [comment] 2017-12-11 09:17
Cannot refer to any of the standard libraries from within the actor. The code package does not include the netstandard.dll. Any update on when an update could be out? It basically prevents us from using actors in a solution that was build on .net core services and .net standard libraries.

**Comment by CRidge** [comment] 2017-12-17 16:20
I had this same problem - a real pain in the neck. What I finally did to fix the malfunctioning actor, was:

I added this to the .sfproj file:

```
  <Target Name="AfterPackage" AfterTargets="Package">
    <Copy SourceFiles="C:\Program Files\dotnet\sdk\2.0.0\Microsoft\Microsoft.NET.Build.Extensions\net461\lib\netstandard.dll" DestinationFolder="$(PackageLocation)\[Actor name]Pkg\Code"/>
  </Target>
```

This did the trick (for this problem, at least). A simple upgrade of the SF-application in Azure didn't work, but I had the luxuary of being able to delete the applicate completely and reinstall - and then it worked!

**Comment by ashishnegi** [comment] 2017-12-18 07:45
@CRidge @dipinbehl @zxarcg  how is your actor project references the netstandard assemblies? Can you please share your project files?

See if adding `<DependsOnNETStandard>true</DependsOnNETStandard>` in csproj fixes this.

**Comment by ashishnegi** [comment] 2017-12-18 11:39
Also, Can you confirm following :
1. Do you see netstandard.dll and System.Runtime.dll and lot of other dlls in `<stateless_csproj_folder>\bin\x64\Debug` ?
2. Are these dlls present in `<stateless_sfproj_folder\pkg\Debug\<Proect>Pkg\Code` ?

Also, What is Visual Studio version number ?

**Comment by joakimhew** [comment] 2017-12-18 14:04
@ashishnegi  I can confirm that I have the same issue as OP for stateless services. I checked and found the netstandard and runtime DLL's in the bin folder. They are not references in the Code though.
My environment is:

Windows 10
Service fabric SDK: 2.8.232
Service fabric runtime: 6.0.232.9494
Visual studio version: 15.5.1

**Comment by ravipal** [comment] 2017-12-21 22:38
We are working on this fix and will be addressed in the next VS tooling release.

**Comment by mwonger** [comment] 2017-12-29 00:12
Hi Ravikumar, will the fix in the SDK tooling include the copy of the dll system.net.http.dll in addition to netstandard.dll?  We ran into the issue with both dlls.
much appreciated!

**Comment by ravipal** [comment] 2017-12-29 00:35
Yes. With the new behavior the package will include all the files from bin folder of the service project.

**Comment by salariamanisha** [comment] 2018-01-18 18:59
I am getting the same error. Is here a workaround till you guys release the fix ?

"Could not load file or assembly 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The sys"

**Comment by ashishnegi** [comment] 2018-01-19 06:04
@salariamanisha  Copy all the dlls from `<stateless_csproj_folder>\bin\x64\Debug` to `<stateless_sfproj_folder\pkg\Debug\<Proect>Pkg\Code`. Please report back if this works or doesn't work.

**Comment by GeertvanHorrik** [comment] 2018-01-23 10:16
For us the fix that works is adding this to your *package project* (sfproj):

```
  <Target Name="AfterPackage" AfterTargets="Package">
    <Copy SourceFiles="C:\Program Files\dotnet\sdk\2.0.2\Microsoft\Microsoft.NET.Build.Extensions\net461\lib\netstandard.dll" DestinationFolder="$(PackageLocation)\MyProject1.ServiceFabricPkg\Code" />
	<Copy SourceFiles="C:\Program Files\dotnet\sdk\2.0.2\Microsoft\Microsoft.NET.Build.Extensions\net461\lib\netstandard.dll" DestinationFolder="$(PackageLocation)\MyProject2.ServiceFabricPkg\Code" />
  </Target>
```

**Comment by GeertvanHorrik** [comment] 2018-01-23 11:38
Here is an even better script, it copies all the output dll's.

**Note that you need to add this *per service***

```
  <ItemGroup>
    <MyProject1Files Include="$(SolutionDir)\MyProject1.ServiceFabric\bin\x64\$(ConfigurationName)\*.dll" /> 
    <MyProject2Files Include="$(SolutionDir)\MyProject2.ServiceFabric\bin\x64\$(ConfigurationName)\*.dll" />
  </ItemGroup>
  
  <Target Name="AfterPackage" AfterTargets="Package">
    <Copy SourceFiles="@(MyProject1Files)" DestinationFolder="$(PackageLocation)\MyProject1.ServiceFabricPkg\Code" ContinueOnError="false" />
    <Copy SourceFiles="@(MyProject2Files)" DestinationFolder="$(PackageLocation)\MyProject2.ServiceFabricPkg\Code" ContinueOnError="false" />
  </Target>
```

**Comment by jahmai** [comment] 2018-01-23 11:41
It's worth reiterating that the suggestion in [https://github.com/Azure/service-fabric-issues/issues/412#issuecomment-323929697](comment) works perfectly well and doesn't require these project hacks.

**Comment by GeertvanHorrik** [comment] 2018-01-23 12:04
@jahmai  That sucks a bit if you already have several projects created. Let's just hope this tooling fix comes out real soon so we can leave all this alpha stuff behind us.

**Comment by jahmai** [comment] 2018-01-23 12:09
I think we'll find that the fix will be exactly the same as the workaround, only in the default template instead of requiring the one line change.

**Comment by ravipal** [comment] 2018-01-23 18:12
Replace the Microsoft.VisualStudio.Azure.Fabric.Application.targets with the attached one in your Microsoft.VisualStudio.Azure.Fabric.MSBuild nuget package. Then set the below property in your *.sfproj. This will package the output folder.
\<PackageOutputFolder\>true\</PackageOutputFolder\>

[Microsoft.VisualStudio.Azure.Fabric.Application.zip](https://github.com/Azure/service-fabric-issues/files/1657096/Microsoft.VisualStudio.Azure.Fabric.Application.zip)

**Comment by qJake** [comment] 2018-01-25 22:09
@jahmai [That link you pasted]( https://github.com/Azure/service-fabric-issues/issues/412#issuecomment-323929697) 404's for me - can you provide a summary or copy/paste the workaround in this thread?

**Comment by ravipal** [comment] 2018-01-29 20:22
The latest nuget package (1.6.4) has the fix. Please add the property \<PackageOutputFolder\>true\</PackageOutputFolder\> to *.sfproj to change the package behavior that will include all the files from output folder.

**Closed by ravipal** 2018-01-29 20:22 UTC
Labels: bug, fix coming

**Comment by rexwhitten** [comment] 2018-02-02 16:50
This still occurs when following the new project wizard using  Service Fabric SDK 3 + VS 2017 15.5.6 .  Which then causes a VS crash, with project files left incomplete.  

Only the Service Fabric project is created.  No other projects.

**Comment by ravipal** [comment] 2018-02-02 18:12
@rexwhitten, This seems like a separate issue. Can you please open a separate issue. Is VS crash reproducible?

**Comment by geedsen** [comment] 2018-02-09 15:48
@ravipal >>The latest nuget package (1.6.4) has the fix. Please add the property 
Which package is that? Thanks

**Comment by abatishchev** [comment] 2018-05-31 06:45
Any news, known fix for this?

**Comment by ashishnegi** [comment] 2018-05-31 06:51
@abatishchev Is solution in this [comment](https://github.com/Azure/service-fabric-issues/issues/412#issuecomment-361374049) not working for you ? Otherwise, see this [comment](https://github.com/Azure/service-fabric-issues/issues/412#issuecomment-359764165) for workaround and please open a new bug with VS version, SF plugin version and a sample repo project. This might be a regression.

**Comment by tastyeggs** [comment] 2018-06-15 14:32
This issue still exists in VS 15.6.7 when I try to deploy a .NET Framework 4.71-based Stateless Service. I had to copy netstandard.dll to my output directory manually from `C:\Program Files\dotnet\sdk\2.0.2\Microsoft\Microsoft.NET.Build.Extensions\net461\lib`.

**Comment by abatishchev** [comment] 2018-06-15 14:36
The only thing worked for me is to switch to net462. I don't get any traction from the dotnetstandard folks.

**Comment by tastyeggs** [comment] 2018-06-16 02:56
I wonder if this is because the underlying fabric framework uses .NET 4.6, even though the machine says its on 4.7.2. My understanding is .NET Framework 4.7.2 has built in support for .NET Standard 2.0.

**Comment by abatishchev** [comment] 2018-06-16 03:17
To my understanding, this is not SF issue but rather .NET Core, so with the build rather than remote cluster installed runtime: built output doesn't contain the said library.
However, since it's getting GAC'd when .NET 4.7.1. is installed, it'd workaround this around and just work.
