### ISSUE TITLE
CS2012 when debugging multiple sfprojs using Microsoft.VisualStudio.Azure.Fabric.MSBuild.1.6.3

### ISSUE THREAD

**Issue by mkosieradzki** [Azure/service-fabric-issues#531] opened 2017-10-14 12:04 UTC
I am using preview tooling https://blogs.msdn.microsoft.com/azureservicefabric/2017/10/12/visual-studio-2017-service-fabric-tools-2-0-preview/
I have upgraded sfproj msbuild packages to `Microsoft.VisualStudio.Azure.Fabric.MSBuild.1.6.3`

When I run multiple sfprojs as startup projects I get:
```
CSC : error CS2012: Cannot open '<MyProjectPath>\obj\Debug\net461\win7-x64\<MyProjectName>.exe' for writing -- 'The process cannot access the file <MyProjectPath>\obj\Debug\net461\win7-x64\<MyProjectName>.exe' because it is being used by another process.'
```
```
Exception of type 'Microsoft.VisualStudio.Azure.Fabric.ApplicationProject.ProjectSystem.PackageException' was thrown.
```

When I run a single startup project everything works as expected.

I have observed following:
- Different stages of build are executed simultaneously
- For unknown reasons during first rune I was asked first to grant access to a single project directory, and then to grant access to entire solution folder... IMO granting access to entire folder should be enough - and it shows something is wrong...

UPDATE:
I think this is the most important observation: when this issue occurs Visual Studio debugger is already attached and VS is in status `(Running)`, after executing earlier build steps.

UPDATE2: 
Changing debugging mode for this project from `Refresh Application` to `Remove Application` does not change anything

UPDATE3:
I have isolated the issue to `Microsoft.VisualStudio.Azure.Fabric.MSBuild.1.6.3`. After downgrading to `Microsoft.VisualStudio.Azure.Fabric.MSBuild.1.6.2` everything works as expected (even using the preview tooling).

The main difference from my observations is that in 1.6.3 debugger is attached before Get-ApplicationExistence while in 1.6.2 it is attached after.

**Comment by dbreshears** [comment] 2017-10-25 23:20
@mkosieradzki , is this a consistent repro for you as I am unable to repro this with 15.4 VS 2017,   and 2.0.20171009.2 of Service Fabric Tools, using 1.6.3 Fabric.MSbuild Nuget package, My repro was with 2 SFProj, each with a 3 services, some .net core and others .net framework .    I have tried both Remove application and Refresh Application on 1 and 5 node clusters.  Making code changes in between F5's with breakpoints.

I'll research what we changed from 1.6.2 -> 1.6.3 to see if I can spot anything,  Any more information as to what is the makeup of your solution with regards to services in the 2 SFApp projects?  What version of VS 2017 do you have and what version of Windows 10?  Are you, using a 1 node cluster and can you produce a simple repro solution?

**Comment by mkosieradzki** [comment] 2017-10-25 23:29
@dbreshears I am sorry to hear that.

Repro is consistent on my machine, however I will make another run tomorrow to make sure.

I am using 15.4 VS 2017 as well. I am using 1 node cluster. I have 5 SFApp projects with 1-3 services each, no default services, a console application responsible for creating all services. SFApps and this console app are startup projects.

Also there are around 60 other projects in this solution (some of them are libraries some are not involved).

I am afraid it would be easier to me as well to analyze the msbuild file than try to create smaller reproduction.

My another suggestion would be to have a look when the debugger is attached in both SDKs (in relation to `Get-ApplicationExistence` in the console). Maybe you will be able to spot this difference as I am observing (when using different versions of the SDK).

**Comment by masnider** [comment] 2017-11-03 22:04
@mkosieradzki any updates?

**Comment by mkosieradzki** [comment] 2017-11-09 17:38
@masnider @dbreshears My apologies for the delay, I was swamped with another tasks.

I thought that issue reproduces maybe because l have changed sfproj DefaultTargets from Build to Package. But I have changed this setting to Build, but the issue still occurs. No issues at all at 1.6.2.

Let me say it once more: I am observing on 1.6.3 that the debugger attaches to process while some of packages are still compiling.

HOWEVER! I've got a new observation! Changing all sfprojs from RefreshApplication to RemoveApplication fixes the issue!

Apparently RefreshApplication on one or more projects causes the debugger to attach prematurily!

**Comment by mkosieradzki** [comment] 2017-11-09 17:42
If this is an issue with RefreshApplication I will share another observation.
Immediately after package upgrade during I was asked to grant the service fabric user access to my application folder. What was curious is that I have 5 sfprojs.
For the first sfproj I was asked individually to grant this specific sfproj folder access,, but then I was asked to grant the entire solution access. So it might be possible that there are way to wide symlinks.

**Comment by dbreshears** [comment] 2018-06-26 22:13
@mkosieradzki , does this repro with latest 15.7.4 tooling and 1.6.6 Fabric nuget package.   If not will close this out.

**Comment by nebffa** [comment] 2018-07-31 03:44
This occurs for me even on the 15.7.5 of Visual Studio and 1.6.2 Fabric nuget package. It also occurs when upgrading to the 1.6.7 version of the Fabric nuget package.

I am only debugging a single Service Fabric application, not multiple separate ones as the original poster was doing, but it's the same issue and occurs with `Refresh Application`.

Are there any logs I can get you guys that will make a difference?

**Comment by dbreshears** [comment] 2018-07-31 16:10
@nebffa,  dialing up the MSBuild Output Verbosity under Tools->Options->Projects and Solutions->Build and Run to "Detailed" or "Diagnostic" and then share the build log with us might help us but more importantly sharing the below information for us to attempt to reproduce it or at least get a  better understanding of why it might be occurring 

- Which  assembly is getting locked and always the same assembly / project output? 
- How many services in your solution?  
- Using .Net Framework services or .Net Core services?
- Can you share details about the folder structure from the solution on down     
- Are you referencing other projects such as Classlibrary and what framework are they targeting?   
- Will assume it only locks in Refresh mode for you?
- Make any difference if you set maximum number of parallel project builds to "1"
- Does it only occur after you have F5'd and running the service in the cluster?
- What resolves the issue,  closing and restarting VS, removing the service from the cluster, or restarting the cluster? 
-  Can you use a SysInternals utility such Process Explorer to identify what has it locked?

**Comment by nebffa** [comment] 2018-08-01 03:07
The logs are pretty enormous (58 MB). Do you have an email address I can send them to?


Assemblies that are being locked: A variety of our own assemblies - no 3rd party dependencies are showing up as being locked.

How many services in the solution: roughly 15

Using .Net Framework or .Net Core: Both, but mostly .Net framework. The assemblies being locked are all .Net framework assemblies

Folder structure: It's mostly a two-tiered folder structure - one folder for each service, and then a variety of subfolders for each component in each service. There is also a separate folder to house the `.sfproj` Service Fabric project

Are we referencing other projects such as Class library: All the involved/problematic projects are using .NET Framework 4.6.1

Yes, it only locks in Refresh mode for me.

Changing the number of parallel project builds to "1" changes nothing.

If occurs when the service is already running in the cluster. So the new build comes along and tries to update files in the `bin` folder but they are being locked by services in our application in the cluster. This leads into your later question about SysInternals. I can see that the files that Visual Studio cannot overwrite are being locked by our services that are being run in Service Fabric. 

To resolve the issue, I delete the application from Service Fabric via the Service Fabric Explorer, then I restart Visual Studio (have to restart, otherwise VS has cached something and assumes the application is still there even when it isn't). 

Also, FYI I am running a local cluster with no changes after running `& "$ENV:ProgramFiles\Microsoft SDKs\Service Fabric\ClusterSetup\DevClusterSetup.ps1" -AsSecureCluster -CreateOneNodeCluster -Auto` in PowerShell.

**Comment by nebffa** [comment] 2018-08-01 03:27
Just to be specific, it's clear that the problem is that the services running in Service Fabric are locking various assemblies that are trying to be overwritten. This seems fairly normal - an application that's running previously (because we asked it to by debugging it) should be locking those files. What is the way you would normally expect them to become unlocked so that subsequent builds could overwrite such files?

**Comment by dbreshears** [comment] 2018-08-01 20:51
@nebffa, I have tried a bit today to reproduce this but as you notice that you are impacted on one device I haven't been successful attempting to repro but will continue to try and beef up my solution a bit and try various things.   At this point I am going to log a workitem for us to put additional (verbose) tracing in so we can get better tracing information.  Looking at the code more I now don't believe the MSBuild output will help us but perhaps you can include the logsalong with the traces from c:\sfdevcluster\log\traces (please recreate the cluster and create the repro so the traces are small).   Please send them to devinb-at-Microsoft-dot-com

So in Refresh mode we set a symlink back to the build output folder from C:\SfDevCluster\Data\_App\_Node_0\... folder where the services reside,  we then set an event in code prior to build to have the build wait on that event to be reset.  We then initiate a service restart for and place a lock file (text) in the build output folder.  The service will  shutdown as part of the restart which we monitor and then we reset the event to resume the build.  Once the build completes we remove the lock file from the build output and the runtime continues to start the service as part of the service restart.    

So we have some issue still evidently where one of these steps is not working or a timing issue with your particular solution on the desktop machine .     In one case recently there happened to be a "zhombie" service process hanging around that was keeping things locked. When you launch the build via F5 and things are locked on build,  do you see more than one process running  for the <service>.exe by chance?   Do you notice in SFX if the service causing the issues is actually restarting?

**Comment by dbreshears** [comment] 2018-08-01 20:57
@nebffa ,  one other thing, does the service process Id change as a result of the build?   That will tell us if the service is getting restarted and actually shutting down or not.   if it is shutting down then perhaps we need to figure out why it is coming back up prior to the build completing when there should be a lock file in the build output folder.

**Comment by nebffa** [comment] 2018-08-02 03:38
@dbreshears I've sent you those trace logs now. I saw some errors relating to not being able to find the private key of the `ServiceFabricDevClusterCert` certificate, which makes some sense given that this problem is occuring when the cluster is running in HTTPS mode.

**Comment by dbreshears** [comment] 2018-08-02 23:19
@nebffa  Ah... thanks for the traces and pointing out the secure cluster, I overlooked that above initially and I bet that is the issue as you are seeing.     I will see if I can setup a repro with secure cluster and if not, maybe can diagnose the issue through the traces.

**Comment by ravipal** [comment] 2019-11-01 18:53
@nebffa I tied with the secure cluster and I am not able to repro. 

We need to collect the diagnostics level logging to narrow down this issue. Please enable the diagnostics level log, by setting the environment variable "MS_VS_SF_TOOLS_LOGGING_ENABLED=true" and relaunch the VS. This flag will produce the diagnostics log at %temp%\Microsoft.VisualStudio.Azure.Fabric. Once you hit the issue, please share the log with me at ravipal@microsoft.com.

For now I am closing this issue. Please reopen with either a repro project or diagnostics log.

**Closed by ravipal** 2019-11-01 18:53 UTC
Labels: question
