### ISSUE TITLE
Having both WebListener and Remoting endpoints on stateless service fails WebListener comms

### ISSUE THREAD

**Issue by loekd** [Azure/service-fabric-issues#528] opened 2017-10-12 16:04 UTC
Please have a look at this code:
https://github.com/loekd/ServiceFabric.Dictionary

In `IndexApiService` I create one web listener. If I add an additional Remoting Listener, the WebListener becomes unusable and returns bad data.
See example code below:
```
protected override IEnumerable<ServiceInstanceListener> CreateServiceInstanceListeners()
        {
            var listeners = new List<ServiceInstanceListener>();
            listeners.Add(            
                new ServiceInstanceListener(serviceContext =>
                    new KestrelCommunicationListener(serviceContext, "ServiceEndpoint", (url, listener) =>
                    {
                        ServiceEventSource.Current.ServiceMessage(serviceContext, $"Starting Kestrel on {url}");

                        return new WebHostBuilder()
                                    .UseKestrel()
                                    .ConfigureServices(
                                        services =>
                                        {
                                            services.AddSingleton(serviceContext);
                                            services.AddSingleton<IIndexService>(this);
                                        })
                                    .UseContentRoot(Directory.GetCurrentDirectory())
                                    .UseStartup<Startup>()
                                    .UseServiceFabricIntegration(listener, ServiceFabricIntegrationOptions.None)
                                    .UseUrls(url)
                                    .Build();
                    }), IndexServiceListenerSettings.WebListenerName)
            );
//Second listener causes first to break:
            listeners.Add(new ServiceInstanceListener(serviceContext =>
               new FabricTransportServiceRemotingListener(serviceContext, this), IndexServiceListenerSettings.RemotingListenerName));

            return listeners;
        }

```

**Comment by Mardoxx** [comment] 2017-10-13 10:23
Possibly related? https://github.com/Azure/service-fabric-issues/issues/511

**Comment by loekd** [comment] 2017-10-15 07:51
Sounds similar, but I did provide listener names.

**Comment by amanbha** [comment] 2017-11-04 03:19
@loekd I believe the issue is that you are using the same port for both the listeners. You are using endpoint resource name ServiceEndpoint for KestrelCommunicationListener. This is also the default endpoint resource used by default by the remoting listener. Try adding another endpoint resource name in service manifest for Kestrel listener as   <Endpoint Name="KestrelEndpoint" Port="80" Protocol="http" />
For remoting listener leave the default one as 
<Endpoint Name="ServiceEndpoint" />

**Comment by amanbha** [comment] 2018-04-28 00:25
Closing this, please open if you still need help

**Closed by amanbha** 2018-04-28 00:25 UTC
Labels: question
