### ISSUE TITLE
Scale out should deploy containers in parallel in new VMs

### ISSUE THREAD

**Issue by gustavo-armenta** [Azure/service-fabric-issues#254] opened 2017-04-26 16:41 UTC
I expanded a fabric cluster from 6 nodes to 8 nodes. It took 12 minutes to create the empty VMs. Then, it took 13 minutes to deploy containers on first VM, and other 13 minutes to deploy containers on second VM.

I was surprised to see it deployed the containers sequentially on the VMs so I repeated the process. I shrink to 6 nodes and expand to 8 nodes. I got similar results.

I ran these commands to perform scale.
```
$vmss = Get-AzureRmVmss -ResourceGroupName "test-scus" -VMScaleSetName "test-scus-fabric-nt0"
$vmss.sku.capacity = 8
Update-AzureRmVmss -ResourceGroupName "test-scus" -Name "test-scus-fabric-nt0" -VirtualMachineScaleSet $vmss 
```

**Comment by RajeetN** [comment] 2017-06-05 21:25
Windows or Linux?

**Comment by gustavo-armenta** [comment] 2017-06-07 20:15
windows

**Comment by mani-ramaswamy** [comment] 2017-06-23 16:26
Gustavo - were you able to reproduce this with the latest 5.6 release?

**Comment by mani-ramaswamy** [comment] 2017-06-23 18:06
And while Service Fabric will be deploying in parallel, the VM instances may be coming up sequentially leading you think so.

**Comment by gustavo-armenta** [comment] 2017-06-29 20:28
it happens on Service Fabric 5.6.210.9494 windows

**Comment by mani-ramaswamy** [comment] 2017-08-18 22:04
Can you confirm that on a  fixed size cluster, it is happening in parallel? When the cluster size scales, it might scale sequentially (though SF deploys in parallel) causing this behavior.

**Comment by mani-ramaswamy** [comment] 2018-01-12 18:13
Since we've not gotten a response for a few months, I am closing this issue. Please reopen the issue as appropriate.

**Closed by mani-ramaswamy** 2018-01-12 18:13 UTC
Labels: investigating

**Comment by gustavo-armenta** [comment] 2018-01-12 19:18
Mani, please reopen this issue or explain how the team decided this issue is not important to fix

**Comment by mani-ramaswamy** [comment] 2018-01-13 00:50
@gustavo-armenta - were you able to confirm that on a fixed size it isn't happening in parallel?  It should be happening in parallel.   The issue you are hitting is because one node is being added  at a time - we can redirect the issue to the appropriate team on adding more VMs simultaneously.
