### ISSUE TITLE
Visualstudio is released to Linux clusters

### ISSUE THREAD

**Issue by anlem12** [Azure/service-fabric-issues#1246] opened 2018-08-29 02:20 UTC
My Service Fabric environment is a local Linux cluster, using Visual studio to build a serviceless Web API project, which is published directly to the Linux cluster via VS

Error event: SourceId='System.Hosting', Property='CodePackageActivation:Code:EntryPoint'.
There was an error during CodePackage activation.The service host terminated with exit code:6

My code was developed in a Windows environment, how do I deploy to the Service Fabric cluster in Linux？

@masnider  @oanapl help please

**Comment by daviddob** [comment] 2018-08-31 20:39
I am also experiencing this issue the example templates when deploying stateful apps.

**Comment by ashishnegi** [comment] 2018-09-01 07:01
@anlem12 Can you make sure that the script mentioned in ServiceManifest.xml (usually run.sh or entryPoint.sh) has `LF` line encoding and not `CRLF` encoding ? Please check this in your actual package that you deployed.

You can use any editor to find and change this information. 
This also depends on your git settings and `.gitattributes` file.

**Comment by daviddob** [comment] 2018-09-03 02:55
Confirmed all manifests and associated entrypoint scripts were LF, issue still persists.

**Comment by daviddob** [comment] 2018-09-03 04:30
I have tried to debug that way for the past few days without success. It generates a segfault (sigsegv) in FabricRuntime.so that I have been unable to resolve. I have tested the same example code on another Linux cluster that should be identical and it seems to work fine. That said, when running it manually via entrypoint.sh on either deployment the segfault was present so I was unsure if it was a red herring.

**Comment by daviddob** [comment] 2018-09-03 04:32
https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-create-your-first-linux-application-with-java These instructions were followed on an Ubuntu machine to generate and deploy the application to both SF clusters.

**Comment by ashishnegi** [comment] 2018-09-03 04:42
Try `sudo journalctl -u servicefabric -r` in a terminal on failing machine when you are deploying the code to see any failure messages in SF.

Share the next SF logs that are generated after you deployed at asnegi [at] microsoft.com
They will be somewhere at `SvcFab\Log\work\WFab\0\0\Log\Fabric`

+ @PavanKunapareddyMSFT for java app and fault in FabricRuntime when running the script manually in SF cluster.

**Comment by daviddob** [comment] 2018-09-03 04:45
Will do. I'll have those to you by midday PST tomorrow.

**Comment by daviddob** [comment] 2018-09-03 20:27
Looks like the log directory is empty (here is the output of tree on the logdir)

```
.
├── AppInstanceData
│   ├── Etl
│   └── Table
├── Containers
├── lttng-traces
├── Traces
│   ├── 2018-09-03_19:45:31.dtr
│   ├── 2018-09-03_19:53:09.dtr
│   └── 2018-09-03_20:03:26.dtr
├── UserTraces
│   ├── traces.dtr
│   ├── traces.dtr.1
│   └── traces.dtr.2
└── work
    ├── 0
    │   ├── 0
    │   └── WorkSubFolderMap.dat
    ├── temp
    └── WorkSubFolderMap.dat
```

**Comment by daviddob** [comment] 2018-09-03 21:07
Here is a gist of the journalctl output https://gist.github.com/daviddob/6d5abd6993c536f5a7640e2ed50be46a - didnt seem to be too helpful as it appears everything comes up OK. Is there a way to log the entrypoint.sh file output from within SF? I tried to add the logging bits to the ServiceManifest.xml but no logs were written. I also tried in the entrypoint.sh script itself to redirect output but nothing there either.

**Comment by daviddob** [comment] 2018-09-03 22:58
Okay I believe I have resolved my issue. It was multifaceted unfortunately making things difficult to debug. The first issue was the sfappsuser did not have proper permissions to access the FabricDataRoot due to umask and ACL settings on the image I am using. The second issue was w.r.t the environment passed to the entrypoint.sh script. The path reported in entrypoint.sh is as follows `'/var/vcap/data/service-fabric/sfcluster/data/_Node_4/Fabric/Fabric.Code;/var/vcap/packages/openjdk/bin:/bin:/usr/bin:/sbin:/usr/sbin'` - notice the `;` in the path. This should instead be a `:` instead as the `;` breaks the path and causes the first entry to parse incorrectly thus causing the app itself to fail.

**Comment by ashishnegi** [comment] 2018-09-04 04:08
@daviddob This `;` will be a bug if passed by runtime. 
Can you `echo $PATH` on a separate shell on same machine ? If it has `;` in `$PATH` then someone else added it. Otherwise, let me know the SF runtime and SF sdk version you are using.

>FabricDataRoot due to umask and ACL settings on the image I am using.

Do you mean docker container image ?

Sorry, my bad about traces path. These are the traces in your above path : 
```
├── Traces
│   ├── 2018-09-03_19:45:31.dtr
│   ├── 2018-09-03_19:53:09.dtr
│   └── 2018-09-03_20:03:26.dtr
```

**Comment by daviddob** [comment] 2018-09-04 04:15
Path on the system is '/var/vcap/packages/openjdk/bin:/bin:/usr/bin:/sbin:/usr/sbin', the first part is in fact added by SF. I am in the latest available version 6.3.x (I'll get you the specific version tomorrow morning when I fire everything back up). I was referring to a base AMI (in this case a BOSH stemcell image) which requires some customization to get SF working properly. The ACLs for sfappsuser we're not being set properly in addition to a strict Umask which was causing permission issues behind the scenes in the entrypoint.sh script as well. I added `/:` to the start of $PATH to clear the `;` issue and fixed the permissions issues and the app is running without issue at the moment. Note: running it manually via entrypoint.sh still has a segfault in the .so library while SF is able to run it fine.

**Comment by ashishnegi** [comment] 2018-09-04 04:28
@daviddob Also please share the traces with me :  asnegi [at] microsoft [dot] com

**Comment by daviddob** [comment] 2018-09-04 04:31
I'll get you the `SF runtime and SDK version`, `uname -a info` (it's Ubuntu Xenial 16.04 - not sure the kernel version at the moment) and a `tarball of the traces`. Is there anything else youd like while I'm gathering data?

**Comment by ashishnegi** [comment] 2018-09-04 04:49
No, this will be good enough.

**Comment by daviddob** [comment] 2018-09-04 14:18
SF Version Info
```
servicefabric/now 6.3.124.1 amd64 [installed,local]
servicefabricsdkcommon/now 1.3.0 amd64 [installed,local]
```

Linux Image Info
```
~# uname -a
Linux 821fc5b7-3104-412d-b559-514e5e7fc920 4.15.0-30-generic #32~16.04.1-Ubuntu SMP Thu Jul 26 20:25:39 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

Trace info has also been sent over.

**Comment by ashishnegi** [comment] 2018-12-18 09:35
we have fixed the `;` in `PATH`. Closing the issue.

**Closed by ashishnegi** 2018-12-18 09:35 UTC
