### ISSUE TITLE
Service cannot be accessed with its DNS name from a container

### ISSUE THREAD

**Issue by chunliu** [Azure/service-fabric-issues#1037] opened 2018-05-07 13:38 UTC
I tried to deploy 2 Windows containers to a sf cluster with docker compose. The docker-compose.yml looks like this.  

```
version: '3'

services:
  todoweb:
    image: todoweb
    build:
      context: .\TodoWeb
      dockerfile: Dockerfile
    ports:
      - "80:80"
    environment:
      TodoContext: "Data Source=db.todowebsfcontainer;Database=TodoWebDB;User Id=sa;Password=xxxxxxx;"
  db:
    image: microsoft/mssql-server-windows-developer
    environment:
      sa_password: "xxxxxxx"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
```

The DnsService is enabled in the cluster, and I configured the DNS name of the db service in the connection string, as shown the above. However, when I tried to curl the web, it returned an exception 

> The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. 

If I remote desktop to a node and try to connect the db with its name "db.todowebsfcontainer" from this node, it can be connected without problem. So it seems the DNS name works on the cluster node, but not from within another container. 

The container network is the default nat. Did I miss anything in this case?

**Comment by chunliu** [comment] 2018-05-09 09:33
Add on to this, nslookup to db.todowebsfcontainer on a node can resolve the name to an ip address. However, nslookup in the container returns an error: 

>UnKnown can't find db.todo: Server failed

**Comment by ninzavivek** [comment] 2018-05-10 21:35
Have been following up with you on the email. 

- dns resolution works on the host machine but it is failing from inside the container.
- traces show that dns resolution requests from inside the container are failing to reach onto the host machine. 
- Did check that the firewall rule to allow inbound traffic on port 53 on host machine exists.

**Comment by chunliu** [comment] 2018-05-11 02:56
@dario-ms 
Windows sku is 2016-Datacenter-with-Containers

ipconfig /all inside the container:
```
PS C:\inetpub\wwwroot> ipconfig /all

Windows IP Configuration

   Host Name . . . . . . . . . . . . : 01cd1a874d96
   Primary Dns Suffix  . . . . . . . :
   Node Type . . . . . . . . . . . . : Hybrid
   IP Routing Enabled. . . . . . . . : No
   WINS Proxy Enabled. . . . . . . . : No
   DNS Suffix Search List. . . . . . : TodoWeb.SF.Application

Ethernet adapter vEthernet (Container NIC b23a72ec):

   Connection-specific DNS Suffix  . : uimjelsvfeguhjnfqyydex131g.ix.internal.cloudapp.net
   Description . . . . . . . . . . . : Hyper-V Virtual Ethernet Adapter #2
   Physical Address. . . . . . . . . : 00-15-5D-9B-3D-CA
   DHCP Enabled. . . . . . . . . . . : No
   Autoconfiguration Enabled . . . . : Yes
   Link-local IPv6 Address . . . . . : fe80::a8ee:edd4:e572:fede%19(Preferred)
   IPv4 Address. . . . . . . . . . . : 172.30.113.15(Preferred)
   Subnet Mask . . . . . . . . . . . : 255.255.240.0
   Default Gateway . . . . . . . . . : 172.30.112.1
   DNS Servers . . . . . . . . . . . : 172.30.112.1
                                       10.0.0.4
                                       168.63.129.16
   NetBIOS over Tcpip. . . . . . . . : Disabled
```

ping the default gateway:
```
PS C:\inetpub\wwwroot> ping 172.30.112.1

Pinging 172.30.112.1 with 32 bytes of data:
Reply from 172.30.112.1: bytes=32 time<1ms TTL=128
Reply from 172.30.112.1: bytes=32 time<1ms TTL=128
Reply from 172.30.112.1: bytes=32 time<1ms TTL=128
Reply from 172.30.112.1: bytes=32 time<1ms TTL=128

Ping statistics for 172.30.112.1:
    Packets: Sent = 4, Received = 4, Lost = 0 (0% loss),
Approximate round trip times in milli-seconds:
    Minimum = 0ms, Maximum = 0ms, Average = 0ms
```

Listening ports on node: 
```
PS C:\Users\sfadmin> netstat -anob | findstr LISTEN
  TCP    0.0.0.0:135            0.0.0.0:0              LISTENING       760
  TCP    0.0.0.0:445            0.0.0.0:0              LISTENING       4
  TCP    0.0.0.0:1025           0.0.0.0:0              LISTENING       3116
  TCP    0.0.0.0:2179           0.0.0.0:0              LISTENING       2148
  TCP    0.0.0.0:3389           0.0.0.0:0              LISTENING       3024
  TCP    0.0.0.0:5985           0.0.0.0:0              LISTENING       4
  TCP    0.0.0.0:19000          0.0.0.0:0              LISTENING       4884
  TCP    0.0.0.0:19080          0.0.0.0:0              LISTENING       4
  TCP    0.0.0.0:47001          0.0.0.0:0              LISTENING       4
  TCP    0.0.0.0:49664          0.0.0.0:0              LISTENING       492
  TCP    0.0.0.0:49665          0.0.0.0:0              LISTENING       628
  TCP    0.0.0.0:49666          0.0.0.0:0              LISTENING       1364
  TCP    0.0.0.0:49668          0.0.0.0:0              LISTENING       888
  TCP    0.0.0.0:49669          0.0.0.0:0              LISTENING       1888
  TCP    0.0.0.0:49672          0.0.0.0:0              LISTENING       620
  TCP    0.0.0.0:49753          0.0.0.0:0              LISTENING       3116
  TCP    0.0.0.0:49771          0.0.0.0:0              LISTENING       3116
  TCP    0.0.0.0:49774          0.0.0.0:0              LISTENING       3516
  TCP    0.0.0.0:49776          0.0.0.0:0              LISTENING       5064
  TCP    0.0.0.0:49786          0.0.0.0:0              LISTENING       3092
  TCP    10.0.0.4:139           0.0.0.0:0              LISTENING       4
  TCP    10.0.0.4:1026          0.0.0.0:0              LISTENING       4
  TCP    127.0.0.1:1027         0.0.0.0:0              LISTENING       3116
  TCP    127.0.0.1:2375         0.0.0.0:0              LISTENING       728
  TCP    127.0.0.1:49742        0.0.0.0:0              LISTENING       3564
  TCP    127.0.0.1:49749        0.0.0.0:0              LISTENING       1916
  TCP    127.0.0.1:49763        0.0.0.0:0              LISTENING       3116
  TCP    172.30.112.1:53        0.0.0.0:0              LISTENING       728
  TCP    172.30.112.1:139       0.0.0.0:0              LISTENING       4
  TCP    [::]:135               [::]:0                 LISTENING       760
  TCP    [::]:445               [::]:0                 LISTENING       4
  TCP    [::]:2179              [::]:0                 LISTENING       2148
  TCP    [::]:3389              [::]:0                 LISTENING       3024
  TCP    [::]:5985              [::]:0                 LISTENING       4
  TCP    [::]:19080             [::]:0                 LISTENING       4
  TCP    [::]:47001             [::]:0                 LISTENING       4
  TCP    [::]:49664             [::]:0                 LISTENING       492
  TCP    [::]:49665             [::]:0                 LISTENING       628
  TCP    [::]:49666             [::]:0                 LISTENING       1364
  TCP    [::]:49668             [::]:0                 LISTENING       888
  TCP    [::]:49669             [::]:0                 LISTENING       1888
  TCP    [::]:49672             [::]:0                 LISTENING       620
  TCP    [::1]:1027             [::]:0                 LISTENING       3116
  TCP    [::1]:49742            [::]:0                 LISTENING       3564
  TCP    [::1]:49749            [::]:0                 LISTENING       1916
  TCP    [::1]:49763            [::]:0                 LISTENING       3116
```

**Comment by chunliu** [comment] 2018-05-11 15:22
This issue doesn't happen the cluster with os version 1709. Thanks.

**Comment by ninzavivek** [comment] 2018-05-17 02:36
Based on Chun's feedback ( on a separate email thread) I am closing the issue. 

I was unable to reproduce the issue on WS 2016 instance both with hyperv and process isolation.

**Closed by ninzavivek** 2018-05-17 02:36 UTC
