### ISSUE TITLE
Problem Serializing System.ArgumentException using V2 Service Remoting

### ISSUE THREAD

**Issue by rchien** [Azure/service-fabric-issues#921] opened 2018-03-14 23:05 UTC
My service topology is pretty simple. I have a Asp.Net Core calling stateless Svc via service remoting V2. The caller (in this case asp.net) catches `AggregateException`. I fully expect to see the original exception within but to my surprise I see `ServiceException` with serialization error. I can't think of any reason why I would have serialization error running the code locally.

I've double checked that
1. Both client and svc uses V2 remoting
1. Only concrete types are in svc interface
1. No custom exception (to keep things simple)

Setup:
- Latest SF SDK `3.0.472` installed 
- Latest SF Nuget `3.0.472`

StackTrace:
```
"The exception System.ArgumentException was unhandled on the service and could not be serialized for transferring to the client.
Detailed Remote Exception Information: System.ArgumentException: resource
   at Mojio.Platform.API.StorageService.StorageService.<GetAllKeyValueAsync>d__4.MoveNext() in C:\\....\\StorageService.cs:line 52
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ServiceFabric.Services.Remoting.V2.Builder.MethodDispatcherBase.<>c__DisplayClass8_0`1.<ContinueWithResult>b__0(Task`1 t)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ServiceFabric.Services.Remoting.V2.Runtime.ServiceRemotingMessageDispatcher.<>c__DisplayClass11_0.<OnDispatch>b__0(Task`1 t)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.ServiceFabric.Services.Remoting.V2.Runtime.ServiceRemotingMessageDispatcher.<>c__DisplayClass11_0.<OnDispatch>b__0(Task`1 t)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ServiceFabric.Services.Remoting.Runtime.ServiceRemotingCancellationHelper.<DispatchRequest>d__5`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ServiceFabric.Services.Remoting.V2.Runtime.ServiceRemotingMessageDispatcher.<HandleRequestResponseAsync>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ServiceFabric.Services.Remoting.V2.FabricTransport.Runtime.FabricTransportMessageHandler.<RequestResponseAsync>d__7.MoveNext()"
```

**Comment by sshumakov** [comment] 2018-03-16 12:50
It can happen if any exception that is thrown by any library/.net framework is not serializable. This answer has good example of exception which is serializable https://stackoverflow.com/questions/94488/what-is-the-correct-way-to-make-a-custom-net-exception-serializable. 

In remoting v2, you had to catch those manually to prevent them popping up with "can't deserialize error". Not sure what is the best way how to handle it in remoting v2.

**Comment by suchiagicha** [comment] 2018-03-16 16:10
@rchien 
Which .net framework version you are using for service project?

**Comment by rchien** [comment] 2018-03-16 16:23
@suchiagicha Both projects use `.Net Core 2.0`. Caller is Asp.Net Core 2.0 and callee is Stateless Service.

**Comment by suchiagicha** [comment] 2018-03-19 15:59
@hrushib

**Comment by hrushib** [comment] 2018-03-19 17:04
This issue is fixed in dotnet update 2.0.3 and above. Make sure that your app uses dotnet version 2.0.3 and above to get this Exception serialization working as expected.

**Comment by rchien** [comment] 2018-03-19 19:49
@hrushib thanks for the update. However, my machine has .NET Core 2.0.6 installed which I think is the latest-and-greatest. Anything else that you can think of that might cause this error?

FYI, I can check VSTS to see which .Net Core Runtime gets deployed to Azure but I think it should be the same version as I have locally.

**Comment by hrushib** [comment] 2018-03-21 08:06
@rchien please check framework version on your Azure deployment. In case this is greater than 2.0.4 then exception serialization is expected to work as expected. 

Release notes of 2.0.4 - https://github.com/dotnet/core/blob/master/release-notes/2.0/2.0.4.md 
Relevant Commit - https://github.com/dotnet/coreclr/commit/fb95b29 

If this is not working then please provide minimal sample code which is leading to this issue, this will help us quickly investigate this issue further and provide resolution.

**Comment by rchien** [comment] 2018-03-26 22:27
@hrushib Here's a sample repo to reproduce this issue https://github.com/rchien/ExceptionSerializationApplication

From my trial-and-error it seems nothing except `Exception` can be serialized properly.  In the project I have two scenarios where
1. Svc interface in common .Net Standards 2.0 proj => xxx/api/values/exception/common
1. Svc interface in svc implementation                      => xxx/api/values/exception/svc

In `Stateless1/Stateless1.cs` I randomize the type of exception to throw. In hindsight deterministic is probably more desirable.

**Comment by hrushib** [comment] 2018-04-04 08:14
@rchien Thanks for providing minimal code which reproduces this issue. I am able to re-produce this on my end and will investigate the root cause and revert to you in sometime.

**Comment by rchien** [comment] 2018-04-05 21:55
@hrushib thanks for your assistance looking into this

**Comment by hrushib** [comment] 2018-04-09 17:37
@ViktorHofer can you look at the project definitions in the repo shared by @rchien and confirm if the project definitions is correct?
Even adding <RuntimeFrameworkVersion>2.0.4</RuntimeFrameworkVersion>is helping to get system defined exceptions serialized.

**Comment by hrushib** [comment] 2018-04-10 13:29
@rchien please add below line under `PropertyGroup` to Web1.csproj and Stateless1.csproj to get system exception serialization work as expected.
`<RuntimeFrameworkVersion>2.0.4</RuntimeFrameworkVersion>`

Please confirm if this is working as expected on your end.

**Comment by hrushib** [comment] 2018-04-11 07:42
@rchien, closing this as the above steps will resolve the issue. In case you are still facing issues on your end then reopen this with more details.

**Closed by hrushib** 2018-04-11 07:42 UTC
Labels: investigating

**Comment by rchien** [comment] 2018-04-11 18:09
Confirmed to work in both sample and real project. Thanks @hrushib!

My only suggestion is to make sure the property is in all projects not just calling and called project. An easy way to do this is through `Directory.Build.props`

**Comment by hrushib** [comment] 2018-04-12 07:58
@rchien, thanks for the confirmation.

**Comment by Tadimsky** [comment] 2018-04-12 16:10
With 2.1 you won't need to specify this anymore which will be nice - it will always use the latest version your SDK knows about - https://blogs.msdn.microsoft.com/dotnet/2018/04/11/announcing-net-core-2-1-preview-2/

**Comment by Adebeer** [comment] 2019-07-22 23:21
I'm getting this serialization error in my Service Fabric project. 

Essentially, I've got a .NET Core 2.2 API Gateway project that uses V2 remoting to a .NET 4.7.2 stateless service.

This is the error I'm getting in App Insights (logging via Service Fabric Native Nuget)

`Failed to deserialize and get remote exception  System.Runtime.Serialization.SerializationException: Type 'System.Data.SqlClient.SqlErrorCollection' in Assembly 'System.Data.SqlClient, Version=4.5.0.1, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' is not marked as serializable.
   at System.Runtime.Serialization.FormatterServices.InternalGetSerializableMembers(Type type)
   at System.Runtime.Serialization.FormatterServices.<>c.<GetSerializableMembers>b__5_0(MemberHolder mh)`

**Comment by ViktorHofer** [comment] 2019-07-26 07:55
SqlErrorCollection is not serialized in .NET Core: https://github.com/dotnet/corefx/blob/master/src/System.Data.SqlClient/src/System/Data/SqlClient/SqlErrorCollection.cs
