### ISSUE TITLE
DNSService UDP listener is unable to start

### ISSUE THREAD

**Issue by EvilAvenger** [Azure/service-fabric-issues#803] opened 2018-01-30 06:38 UTC
After update from 6.0 to 6.1 there is an issue with DNSService:

Unhealthy event: SourceId='System.FabricDnsService', Property='Socket', HealthState='Warning', ConsiderWarningAsError=false. 

DnsService UDP listener is unable to start. Please make sure there are no processes listening on the DNS port 53. 

List of processes listening on the DNS port:   
`
UDP    0.0.0.0:53             *:*                                    6612`

And 6612 is blocked by svchost.exe: which is used by Docker service.

**Comment by nrandell** [comment] 2018-01-30 10:50
Exactly the same problem here as well.  Mine is blocked by svchost.exe 
c:\windows\system32\svchost.exe -k netsvcs -p -s SharedAccess
procexp says it is for Internet Connection Sharing

**Comment by kieronlanning** [comment] 2018-01-30 16:20
I've got the same problem, I'm trying to do a tutorial on SF which isn't working, and I'm not sure if it's because of this or not.

![image](https://user-images.githubusercontent.com/5364423/35577418-6d658296-05d9-11e8-8943-356b9c3c092c.png)

**Comment by nrandell** [comment] 2018-01-30 16:23
Even though I have this problem, I'm still able to use my development cluster - so your problem may be something else

**Comment by kieronlanning** [comment] 2018-01-30 16:28
@nrandell That's a pain, VS is unable to connect - even as far as resetting the cluster and uninstalling and re-installing.

**Comment by asaheed** [comment] 2018-01-30 16:45
same problem here, as soon as I kill a process which is using port 53 the next process is grabbing it ... in the end I am unable to free the port (svchost, searchUI, chrome ... this port is loved by anyone)

**Comment by milvuko** [comment] 2018-01-30 19:27
You have to stop the ICS service which is causing the issue. Go to Services  (services.msc) and find the **Internet Connection Sharing (ICS)** service, then stop the service.
This can be done from the admin cmd window as well by executing the command:
**sc stop sharedaccess**

**Comment by nrandell** [comment] 2018-01-31 21:33
I've noticed that you need to kill ICS every reboot. I tried disabling it in services, but it appeared to be re-enabled and manually started by another process.

**Comment by tanwarsatya** [comment] 2018-02-06 20:19
Exact same issues, disabled the ICS and its working. Any long term solution for this, and why this issues never came in earlier versions.

**Comment by lucamazzanti** [comment] 2018-02-14 11:53
Same issue, now i will create a node without the default Service Fabric Local Cluster Manager preset, but with the samples available [here](https://docs.microsoft.com/it-it/azure/service-fabric/service-fabric-cluster-manifest). So the issue comes out from ICS, that uses 0.0.0.0:53. Who is launching it manually? I disabled it with services, regedit, but invain. I think it is Hyper-V. I didnt had this issue months ago.
Please find a way tho configure this bootstrapper or leave each processes alive.
Docker CE for Windows is not an issue, it uses the port 53 on another network dedicated, please ask Hyper-V do the same if viable.

**Comment by nunocenteno** [comment] 2018-02-28 10:57
I've seen the same issue. In my scenario, I've a Windows 10 dev machine, with Docker for Windows installed, Visual Studio and Service Fabric. I noticed that when the error of Dns is happening in Service Fabric, docker is working just fine, if I restart the ICS service, Service Fabric just works fine, but docker stops working. Somehow ICS is essential for Docker for Windows, or Hyper-V as someone already stated.

**Comment by zaphide** [comment] 2018-03-07 11:36
Noticed same issue (and killing ICS service does seem to clear the issue).

This also resulted in a build up of excessive CPU usage for both FabricDnsService and FabricGatewayService that would build gradually over time.

**Comment by pksorensen** [comment] 2018-03-19 18:30
I disabled the dns service in my dev service fabric cluster instead.

irst select Remove local cluster from the little SF tray icon.

Then go to C:\Program Files\Microsoft SDKs\Service Fabric\ClusterSetup\NonSecure\OneNode (or FiveNode for a local 5 node cluster) and update ClusterManifestTemplate.json.

Look for:

```
"addOnFeatures": [
  "DnsService"
]
```
And just remove DnsService from that list.

Then start up the cluster again.

**Comment by MikkelHegn** [comment] 2018-04-24 17:09
This should be fixed in the 6.2 runtime release

**Comment by cod7alex** [comment] 2018-05-10 08:49
Hi, I am seeing this problem using 6.2 runtime.

**Comment by ninzavivek** [comment] 2018-05-10 20:36
Could you provide information about your environment ?

- Is this is SFRP cluster on One box environment?
- Is this is Windows or Linux?
- What the error are you getting, we do list message on SF explorer page. 
- What is the exact version?

**Comment by cod7alex** [comment] 2018-05-11 07:41
@ninzavivek Hi, this seems sporadic, i will get back to you if i am able to catch it.

**Comment by cod7alex** [comment] 2018-05-14 11:25
@ninzavivek 
1. Local 1 Node cluster
2. Windows 10 with latest updates
3. 
```
Unhealthy event: SourceId='System.FabricDnsService', Property='Socket', HealthState='Warning', ConsiderWarningAsError=false. DnsService UDP listener is unable to start. Please make sure there are no processes listening on the DNS port 53. List of processes listening on the DNS port:   
UDP    0.0.0.0:53             *:*                      7664    
UDP    127.0.0.1:53           *:*                    8924    
UDP    172.20.208.1:53        *:*                 5888
--
```

Those processes are Internet Connection Sharing (ICS), Cisco DNS Proxy, dockerd.
4. Version listed for services is `6.2.269.9494`

**Comment by ninzavivek** [comment] 2018-05-15 01:07
Could you provide more information on how the cluster was created? 

Also, please confirm the value of  "AllowMultipleListeners" parameter in DNS Service section of cluster manifest - http://localhost:19080/Explorer/index.html#/tab/manifest

 <Section Name="DnsService">

      <Parameter Name="InstanceCount" Value="-1" />

      <Parameter Name="IsEnabled" Value="True" />

      **<Parameter Name="AllowMultipleListeners" Value="true" />**

    </Section>

**Comment by cod7alex** [comment] 2018-05-15 07:37
Default cluster created by SDK, no modifications.
`AllowMultipleListeners` is `true`.

**Comment by ninzavivek** [comment] 2018-05-17 02:43
I am unable to reproduce this issue on RS3, RS4 machines and we haven't seen any other reports of it.

**Comment by benmartens** [comment] 2018-05-17 03:07
By "no other reports" I assume you mean no reports other than every else on this thread. I worked around this by using pksorensen's most recent post (and I assume all the other thumbs up did as well.)

**Comment by suhuruli** [comment] 2018-07-23 23:16
Any updates on this?

**Comment by anousham** [comment] 2018-08-31 17:52
I am seeting the same issue.

**Comment by MikkelHegn** [comment] 2018-09-03 10:05
To summarize some of the things on this thread. Original problem with the DNS Service not being able to share port with other services was fixed in 6.2.

There are other Cluster setup issues that some might run in to, this for instance (although title is "DNS Issue"): https://github.com/Microsoft/service-fabric-cli/issues/110

I'm closing this issue, as the original problem is solved, please open new issues for specific problems you may run in to. Thanks.

**Closed by MikkelHegn** 2018-09-03 10:05 UTC
Labels: doc follow-up

**Comment by ibuildit** [comment] 2018-09-20 10:37
I'm trying to get it to work with Mesh on localhost, which in turn needs Docker...which uses the port.

It seems to me that what ever was attempted fixed in 6.2 is still there.

**Comment by ibuildit** [comment] 2018-09-20 11:59
If I disable Hyper-V, the problem is gone and DNS service is OK.

**Comment by joshmouch** [comment] 2019-04-18 14:03
I get a similar issue with the latest Service Fabric on a local cluster with the default SDK installation. In the windows event log, I see:
`DnsRemoteQueryOp activityId {4e50cbf3-0f56-4aa9-8dcd-de6837fea69e}, failed to start the UDP listener`

I tried disabling the Internet Connection Sharing services.  I tried closing Docker for Windows.  I haven't tried disabling Hyper-V yet.

**Comment by kseager** [comment] 2019-04-18 17:33
Are you sure there is nothing outstanding that is listening on UDP port 53? Check the output from: netstat -nao | find ":53" | find "UDP" to see if there are any processes listed

**Comment by festivus** [comment] 2019-05-15 02:04
I have the same issue with latest sdk, single node cluster built using defaults. i have docker installed. ICS is using port 53.

**Comment by joshlang** [comment] 2019-08-19 14:47
Same problem.  Fresh install of service fabric & docker.  

The instant I stop Internet Connection Sharing, the problem goes away.

**Comment by mchudinov** [comment] 2020-03-10 17:38
Same problem with Fabric v 7.0.457 DNSService does not start. And the whole local cluster does not work.
I have docker for Windows installed.

**Comment by RaulRG** [comment] 2020-10-12 10:56
I am having the same problems. Docker will not start and the problem is that the port 53 is in use. The culprit is a service from Microsoft

c:\windows\system32\svchost.exe -k netsvcs -p -s SharedAccess

@nrandell already posted about this in 2018. Is there a way of configuring Docker to use another port? Killing the service does not make me feel very good and as I am using Docker for Windows it should coexist with it. As it seems, the service is configured to auto start.
