### ISSUE TITLE
Remove crashed Service Fabric On Premise node

### ISSUE THREAD

**Issue by shlomcoh** [Azure/service-fabric-issues#356] opened 2017-07-19 13:35 UTC
Hello,
I have an on premise cluster with 5 nodes and one of my nodes crashed yesterday.
i were able to add a new node instead of the broken one with Addnode.ps1.
after the new node added i went to remove the broken node ( a server that crashed and can't get back online) and I see that the script for removing a node and also the function for removing the node from the module, both work only on local node. and i couldn't find a way to remove a node from the cluster manifest.
is there anything supported for this issue? Do I need to load a new configuration file to the cluster with the existing nodes, will it work?

**Comment by edu1409** [comment] 2017-07-24 13:42
Same problem here. I tried to update manifest throught **Start-ServiceFabricClusterConfigurationUpgrade** (https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-cluster-windows-server-add-remove-nodes#remove-nodes-from-your-cluster) without success. The error message indicates that node must be online :(

> Start-ServiceFabricClusterConfigurationUpgrade : System.Runtime.InteropServices.COMException (-2147017627)
> ValidationException: Model validation error. Required ports on the node to be removed are not reacheable. Check connectivity/open ports.

**Comment by Liphi** [comment] 2017-08-17 18:45
What is the code version of ur cluster? There are many problems with AddNode and RemoveNode for code versions prior to 5.6 and json apiVersion prior to '04-2017'.

**Comment by shlomcoh** [comment] 2017-08-17 19:02
I had couple of clusters with the same issue.
one lost a node on version 5.5 and i was able upgrade it all the way to 5.7 with no problem as it was in silver reliabilityLevel so upgrade was possiable.
the second one was 5.6 and I couldn't upgrade it as it has only bronze reliabilityLevel and one of the seed nodes fail so I couldn't upgrade any seed node.

**Comment by rakshitatandon** [comment] 2017-08-17 19:39
The nodes need to be online for SF to be able to reach them, uninstall Service Fabric on the node and remove it from the cluster ring. If the node is not reachable, we will not be able to perform any service fabric operations on it.
@shlomcoh For the other issue on upgrading from 5.6 with reliabilityLevel Bronze with one seed node down, we block the upgrade because the upgrade operation will result in quorum loss since one seed node is already down. In order to allow the upgrade, you should bring the node back up. For production clusters, our recommendation is to have atleast 5 nodes (Silver).

**Comment by shlomcoh** [comment] 2017-08-17 19:45
ok.
so basically you are saying that If i have a node down, doesn't meter the reliablitylevel, I can't do anything to get ride of it?
so if I am live in production with 5/7/9 or more nodes and i have one node down I have no way of removing it from my cluster, on in other words, if a server crashed and can't get back online, I will have one node in the cluster marked as unknown or down with no option to go around it by design?
let me ask a following question. if its a seed node? doesn't the cluster need to move the seed to another server? so the reliablitylevel won't get impact?

**Comment by rakshitatandon** [comment] 2017-08-17 21:05
Seed nodes are selected out of the nodes that are marked as IsPrimary:True (in the NodeType section) during deployment. Depending on the reliabilityLevel set, we choose as many seed nodes (3/5/7/9). 
If you have 5 seed nodes, we need atleast 3 seed nodes to be up to maintain quorum. Similarly if you have 7 seed nodes, atleast 4 seed nodes should be up. Choosing silver or higher gives us more margin since we can afford to lose more nodes and still maintain quorum.

The reason Bronze is not recommended for production is because we have only 3 seed nodes and losing even one of them can result in quorum loss. By design, the system will not initiate a seed node upgrade if a seed node goes down. The upgrade has to be manually initiated. Now say, if you were at Silver and one seed node goes down (we are not losing quorum, 4/5 seeds are still up), you can always remove this node (if it is reachable). The system will pick a new seed node to maintain the reliabilityLevel (provided you have sufficient nodes marked with IsPrimary:True) and remove the down node from the cluster. If the node itself is not reachable, there is no way for us to talk to it to remove it from the ring. The best mitigation here would be to deactivate the node so that all replicas are moved away from this node and then go fix the machine. As long as quorum is maintained, the ring is healthy.

On a side note, we also recommend that you keep system nodes and application nodes separate (by using different nodetypes) so that any application issue does not cause the system nodes to go down.

**Comment by shlomcoh** [comment] 2017-08-17 21:20
first of all thank you very much for your fast replies.
so everything you just replied on reliabilitylevel are things i read about in your documentation. 
I didn't see the behavioral when a seed node crashed that the cluster moved the seed to another server, and all of my servers are in the same nodetype and marked as primary.

leaving that a side, as we will have at least Silver in our QA environments from now on. and Gold in our new production cluster I believe this part of the issue is behind us.
I do want to know if there is any plan for removing a problematic Servers without the option of reaching it.
it is possible for a server to crash and not got back online, a spicily if we use physical servers.
I don't think having a cluster with nodes marked as deactivate,is best practice. and also I see that i can't add new nodes to the cluster on the same nodetype, as it looks the servicefabricclusterupgrade config is trying to communicate the change for all the nodes and fails as one of the node is down (could be related to the fact that one of the nodes that was down was a seed node).
beside this issue there is always the fact of having an unclean cluster with nodes that are no longer active.
is there a plan to change this method? will SF provide an option in the future to remove nodes without the need for the server to be online and activated?

and for your side note,
I didn't see your recommendation anywhere, does it documented? you suggest i will keep 5+ servers in production with no application installed on them and have another nodeType for the rest of the applications? if so, do you have documentation for supporting this type of methodology with publish-newservicefabriccluster/upgrade... 

again, 
thank you very much for all your help

**Comment by rakshitatandon** [comment] 2017-08-17 21:42
It is possible to upgrade the cluster even if some nodes are down as long as quorum is not lost. You can set the upgrade parameters to allow unhealthy nodes/applications (https://docs.microsoft.com/en-us/powershell/module/servicefabric/start-servicefabricclusterconfigurationupgrade?view=azureservicefabricps)
There is no plan as of now to support scenarios where node communication itself is lost (because node is not reachable). For the side note, I believe we don't have any concrete documentation on those guidelines. We will add more details to the existing documentation in future.
Thank you for pointing it out.

**Comment by shlomcoh** [comment] 2017-08-17 21:49
ok.
so first of all i wasn't aware that MaxPercentUnhealthyNodes will let you update my manifest, I though when adding a new node to the cluster it need to be updated in all the nodes available in the cluster, so thank you for that and I will give it a try once possible.

if you don't have documentation for how to deploy application on a specific nodetype do I need to open another issue for that or maybe contact Support?
if you suggest separating seed nodes from application nodes, we will most likely try listening these guidelines. the question now is how...

again I want to thank you for your time and @dkkapur for assigning someone to this issue.

**Comment by rakshitatandon** [comment] 2017-08-17 21:52
Yes, you may contact support and they will be able to guide you in setting up a cluster with the recommended guidelines.

**Comment by shlomcoh** [comment] 2017-08-17 21:52
thank you very much.

**Closed** 2017-08-17 21:53 UTC

**Comment by Thieund** [comment] 2018-02-06 05:19
@rakshitatandon  Could you please explain why "The reason Bronze is not recommended for production is because we have only 3 seed nodes and losing even one of them can result in quorum loss." Thanks.

**Comment by rakshitatandon** [comment] 2018-02-06 18:48
@Thieund Bronze should only be used for test clusters. With Bronze only 3 seed nodes are configured. If any of the seed nodes go down (network outage, hardware issues etc.), then the cluster would be left with only 2 healthy seed nodes. In such a state, all config/code upgrades will be blocked since an upgrade requires UD by UD walk and takes down nodes one-by-one while upgrading. Due to safety checks, it is not possible to take down any more seed nodes (since we are already at quorum edge with only 2/3 healthy seed nodes). For production clusters, the minimum supported reliability level is Silver.

**Comment by Thieund** [comment] 2018-02-07 04:27
@rakshitatandon Thanks very much for your clarification

**Comment by xela30** [comment] 2018-09-29 11:51
@rakshitatandon I've got into exactly the same situation and need your assistance please.
I have standalone cluster of 7 boxes where 3 of them are seed (6.3.162.9494).
After trying to remove crashed seed node via NodesToBeRemoved parameter SF elected new seed node and uninstalled all SF components from that box.
However configuration upgrade has eventually failed and rolled back (due to MaxUnhealthyNodesPercent=0) thus crashed node is still there in the cluster map.
Is it possible to somehow reinstall SF runtime on that node and repeat the removal attempt?
It's not seed node anymore so should be possible, correct?

**Comment by shlomcoh** [comment] 2018-10-02 09:54
this didn't work for you:

Remove-ServiceFabricNode

Reference:
https://docs.microsoft.com/en-us/powershell/module/servicefabric/remove-servicefabricnodestate?view=azureservicefabricps


this is their best practice, if it doesn't work the removal is much more
complicated. it involve modifying the nodes jsons to remove, I will look
for it if needed
