### ISSUE TITLE
VS2015 Upgrade publishing to cloud fails : An item with the same key already exists

### ISSUE THREAD

**Issue by johnkattenhorn** [Azure/service-fabric-issues#48] opened 2016-09-13 17:16 UTC
After setting the manifest versions to 2.1.0-beta.38 (fullsemver) and attempt to publish build fails with `An Item with the same key already exists`

Run Build and Package works fine with same setting works fine.

Deploying via PowerShell also works fine.

**Comment by MikkelHegn** [comment] 2016-09-13 18:12
We probably need a bit more info on the error side. @ravipal, @dbreshears

**Comment by johnkattenhorn** [comment] 2016-09-13 18:13
No worries, let me know what I can give you ? Would cranking up the build output verbosity help ?

**Comment by dbreshears** [comment] 2016-09-13 18:56
Hmm.. can't get an immediate repro.   Can you paste the output from the Build and Service Fabric panes after the Publish fails.    Are you updating the versions of everything or only some services code/config packages?.  What does your upgrade settings look like in the publish profile?   What is the make-up of your application, how many services, etc..  Do you get the same error if you publish from VS to the local cluster?

**Comment by johnkattenhorn** [comment] 2016-09-13 19:02
Thanks for the quick response @dbreshears, I'll do this first thing in the morning and post it here.

**Comment by johnkattenhorn** [comment] 2016-09-15 18:41
Sorry for the delay; here is my findings

1) It fails on local too with the same error.
2) We are updating all of the versions to the same value say from `2.1.0-beta0048` to `2.1.0-beta0076`
3) Here is the cloud.xml publish profile

```xml
<?xml version="1.0" encoding="utf-8"?>
<PublishProfile xmlns="http://schemas.microsoft.com/2015/05/fabrictools">
  <ClusterConnectionParameters ConnectionEndpoint="<clustername>.westeurope.cloudapp.azure.com:19000" X509Credential="true" ServerCertThumbprint="<CertThumbprint>" FindType="FindByThumbprint" FindValue="<CertThumbprint>" StoreLocation="CurrentUser" StoreName="My" />
  <ApplicationParameterFile Path="..\ApplicationParameters\Cloud.xml" />
  <UpgradeDeployment Mode="Monitored" Enabled="true">
    <Parameters FailureAction="Rollback" Force="True" />
  </UpgradeDeployment>
</PublishProfile>
```

4) Here's the output from the pane

```Restoring NuGet packages...
To prevent NuGet from restoring packages during build, open the Visual Studio Options dialog, click on the Package Manager node and uncheck 'Allow NuGet to download missing packages during build.'
NuGet Package restore failed for project 3. Virtual Devices\MKopa.M2M.VirtualDevice.Ibis2: The process cannot access the file 'C:\Repos\M-KOPA M2MR2\src\packages\Microsoft.Bcl.Build.1.0.21\build/Microsoft.Bcl.Build.Tasks.dll' because it is being used by another process..
NuGet Package restore failed for project 3. Virtual Devices\MKopa.M2M.VirtualDevice.Ibis: The process cannot access the file 'C:\Repos\M-KOPA M2MR2\src\packages\Microsoft.Bcl.Build.1.0.21\build/Microsoft.Bcl.Build.Tasks.dll' because it is being used by another process..
NuGet Package restore failed for project 0. Common\MKopa.M2M.ServiceFabric: The process cannot access the file 'C:\Repos\M-KOPA M2MR2\src\packages\Microsoft.Bcl.Build.1.0.21\build/Microsoft.Bcl.Build.Tasks.dll' because it is being used by another process..
NuGet Package restore failed for project 0. Common\MKopa.M2M.Mock: The process cannot access the file 'C:\Repos\M-KOPA M2MR2\src\packages\Microsoft.Bcl.Build.1.0.21\build/Microsoft.Bcl.Build.Tasks.dll' because it is being used by another process..
NuGet Package restore failed for project 2. Services\Mkopa.M2M.IBIS2\MKopa.M2M.IBIS2.Service: The process cannot access the file 'C:\Repos\M-KOPA M2MR2\src\packages\Microsoft.Bcl.Build.1.0.21\build/Microsoft.Bcl.Build.Tasks.dll' because it is being used by another process..
NuGet Package restore failed for project 2. Services\Mkopa.M2M.IBIS2\MKopa.M2M.IBIS2.Notifications.Service: The process cannot access the file 'C:\Repos\M-KOPA M2MR2\src\packages\Microsoft.Bcl.Build.1.0.21\build/Microsoft.Bcl.Build.Tasks.dll' because it is being used by another process..
NuGet Package restore failed for project 2. Services\Mkopa.M2M.IBIS2\MKopa.M2M.IBIS2: The process cannot access the file 'C:\Repos\M-KOPA M2MR2\src\packages\Microsoft.Bcl.Build.1.0.21\build/Microsoft.Bcl.Build.Tasks.dll' because it is being used by another process..
NuGet Package restore failed for project 2. Services\Mkopa.M2M.IBISAg\MKopa.M2M.IBISAg.Service: The process cannot access the file 'C:\Repos\M-KOPA M2MR2\src\packages\Microsoft.Bcl.Build.1.0.21\build/Microsoft.Bcl.Build.Tasks.dll' because it is being used by another process..
NuGet Package restore failed for project 2. Services\Mkopa.M2M.IBISAg\MKopa.M2M.IBISAg.Notifications.Service: The process cannot access the file 'C:\Repos\M-KOPA M2MR2\src\packages\Microsoft.Bcl.Build.1.0.21\build/Microsoft.Bcl.Build.Tasks.dll' because it is being used by another process..
NuGet Package restore failed for project 2. Services\Mkopa.M2M.IBISAg\MKopa.M2M.IBISAg: The process cannot access the file 'C:\Repos\M-KOPA M2MR2\src\packages\Microsoft.Bcl.Build.1.0.21\build/Microsoft.Bcl.Build.Tasks.dll' because it is being used by another process..
NuGet Package restore failed for project 2. Services\MKopa.M2M.Windows.Services\MKopa.M2M.Inbound.UdpListener: The process cannot access the file 'C:\Repos\M-KOPA M2MR2\src\packages\Microsoft.Bcl.Build.1.0.21\build/Microsoft.Bcl.Build.Tasks.dll' because it is being used by another process..
NuGet Package restore failed for project 2. Services\MKopa.M2M.Windows.Services\MKopa.M2M.Outgoing.Sender: The process cannot access the file 'C:\Repos\M-KOPA M2MR2\src\packages\Microsoft.Bcl.Build.1.0.21\build/Microsoft.Bcl.Build.Tasks.dll' because it is being used by another process..
NuGet Package restore failed for project 2. Services\MKopa.M2M.IBIS\MKopa.M2M.IBIS.Notifications.Service: The process cannot access the file 'C:\Repos\M-KOPA M2MR2\src\packages\Microsoft.Bcl.Build.1.0.21\build/Microsoft.Bcl.Build.Tasks.dll' because it is being used by another process..
NuGet Package restore failed for project 2. Services\MKopa.M2M.IBIS\MKopa.M2M.IBIS.Service: The process cannot access the file 'C:\Repos\M-KOPA M2MR2\src\packages\Microsoft.Bcl.Build.1.0.21\build/Microsoft.Bcl.Build.Tasks.dll' because it is being used by another process..
NuGet Package restore failed for project 2. Services\MKopa.M2M.IBIS\MKopa.M2M.IBIS: The process cannot access the file 'C:\Repos\M-KOPA M2MR2\src\packages\Microsoft.Bcl.Build.1.0.21\build/Microsoft.Bcl.Build.Tasks.dll' because it is being used by another process..
NuGet Package restore failed for project 2. Services\MKopa.M2M.DeviceLookup\MKopa.M2M.DeviceLookup.Logic: The process cannot access the file 'C:\Repos\M-KOPA M2MR2\src\packages\Microsoft.Bcl.Build.1.0.21\build/Microsoft.Bcl.Build.Tasks.dll' because it is being used by another process..
NuGet Package restore failed for project 2. Services\MKopa.M2M.DeviceLookup\MKopa.M2M.DeviceLookup.Console: The process cannot access the file 'C:\Repos\M-KOPA M2MR2\src\packages\Microsoft.Bcl.Build.1.0.21\build/Microsoft.Bcl.Build.Tasks.dll' because it is being used by another process..
NuGet Package restore failed for project 2. Services\MKopa.M2M.DeviceLookup\MKopa.M2M.DeviceLookup.Test: The process cannot access the file 'C:\Repos\M-KOPA M2MR2\src\packages\Microsoft.Bcl.Build.1.0.21\build/Microsoft.Bcl.Build.Tasks.dll' because it is being used by another process..
NuGet Package restore failed for project 2. Services\MKopa.M2M.DeviceLookup\MKopa.M2M.DeviceLookup.Service: The process cannot access the file 'C:\Repos\M-KOPA M2MR2\src\packages\Microsoft.Bcl.Build.1.0.21\build/Microsoft.Bcl.Build.Tasks.dll' because it is being used by another process..
NuGet Package restore failed for project 2. Services\MKopa.M2M.DeviceLookup\MKopa.M2M.DeviceLookup.Domain: The process cannot access the file 'C:\Repos\M-KOPA M2MR2\src\packages\Microsoft.Bcl.Build.1.0.21\build/Microsoft.Bcl.Build.Tasks.dll' because it is being used by another process..
NuGet Package restore failed for project 2. Services\MKopa.M2M.Gateway\MKopa.M2M.Gateway.EventHub: The process cannot access the file 'C:\Repos\M-KOPA M2MR2\src\packages\Microsoft.Bcl.Build.1.0.21\build/Microsoft.Bcl.Build.Tasks.dll' because it is being used by another process..
NuGet Package restore failed for project 2. Services\MKopa.M2M.Gateway\MKopa.M2M.Gateway.Service: The process cannot access the file 'C:\Repos\M-KOPA M2MR2\src\packages\Microsoft.Bcl.Build.1.0.21\build/Microsoft.Bcl.Build.Tasks.dll' because it is being used by another process..
NuGet Package restore failed for project 2. Services\MKopa.M2M.Configuration\MKopa.M2M.Configuration.Service: The process cannot access the file 'C:\Repos\M-KOPA M2MR2\src\packages\Microsoft.Bcl.Build.1.0.21\build/Microsoft.Bcl.Build.Tasks.dll' because it is being used by another process..
NuGet Package restore failed for project 2. Services\MKopa.M2M.Configuration\MKopa.M2M.Configuration.Test: The process cannot access the file 'C:\Repos\M-KOPA M2MR2\src\packages\Microsoft.Bcl.Build.1.0.21\build/Microsoft.Bcl.Build.Tasks.dll' because it is being used by another process..
NuGet Package restore failed for project 2. Services\MKopa.M2M.Configuration\MKopa.M2M.Configuration.Test.Console: The process cannot access the file 'C:\Repos\M-KOPA M2MR2\src\packages\Microsoft.Bcl.Build.1.0.21\build/Microsoft.Bcl.Build.Tasks.dll' because it is being used by another process..
NuGet package restore failed.
1>------ Build started: Project: MKopa.M2M.Configuration.Service, Configuration: Debug x64 ------
1>  MKopa.M2M.Configuration.Service -> C:\Repos\M-KOPA M2MR2\src\MKopa.M2M.Configuration\MKopa.M2M.Configuration.Service\bin\Debug\MKopa.M2M.Configuration.Service.exe
2>------ Build started: Project: MKopa.M2M.Configuration.App, Configuration: Debug x64 ------
2>C:\Repos\M-KOPA M2MR2\src\packages\Microsoft.Bcl.Build.1.0.21\build\Microsoft.Bcl.Build.targets(243,5): warning : All projects referencing MKopa.M2M.Configuration.Service.csproj must install nuget package Microsoft.Bcl.Build. For more information, see http://go.microsoft.com/fwlink/?LinkID=317569.
2>  No way to resolve conflict between "Newtonsoft.Json, Version=9.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed" and "Newtonsoft.Json, Version=6.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed". Choosing "Newtonsoft.Json, Version=9.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed" arbitrarily.
2>  No way to resolve conflict between "Autofac, Version=3.5.0.0, Culture=neutral, PublicKeyToken=17863af14b0044da" and "Autofac, Version=3.3.0.0, Culture=neutral, PublicKeyToken=17863af14b0044da". Choosing "Autofac, Version=3.5.0.0, Culture=neutral, PublicKeyToken=17863af14b0044da" arbitrarily.
2>  No way to resolve conflict between "System.Web.Http, Version=5.2.3.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35" and "System.Web.Http, Version=5.2.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35". Choosing "System.Web.Http, Version=5.2.3.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35" arbitrarily.
2>  No way to resolve conflict between "Autofac, Version=4.1.0.0, Culture=neutral, PublicKeyToken=17863af14b0044da" and "Autofac, Version=3.5.0.0, Culture=neutral, PublicKeyToken=17863af14b0044da". Choosing "Autofac, Version=4.1.0.0, Culture=neutral, PublicKeyToken=17863af14b0044da" arbitrarily.
2>  No way to resolve conflict between "System.Net.Http.Formatting, Version=5.2.3.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35" and "System.Net.Http.Formatting, Version=5.2.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35". Choosing "System.Net.Http.Formatting, Version=5.2.3.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35" arbitrarily.
2>  No way to resolve conflict between "Microsoft.Owin, Version=3.0.1.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35" and "Microsoft.Owin, Version=3.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35". Choosing "Microsoft.Owin, Version=3.0.1.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35" arbitrarily.
2>  No way to resolve conflict between "Autofac.Integration.WebApi, Version=4.0.0.0, Culture=neutral, PublicKeyToken=17863af14b0044da" and "Autofac.Integration.WebApi, Version=3.4.0.0, Culture=neutral, PublicKeyToken=17863af14b0044da". Choosing "Autofac.Integration.WebApi, Version=4.0.0.0, Culture=neutral, PublicKeyToken=17863af14b0044da" arbitrarily.
2>  No way to resolve conflict between "System.Web.Http.Owin, Version=5.2.3.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35" and "System.Web.Http.Owin, Version=5.2.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35". Choosing "System.Web.Http.Owin, Version=5.2.3.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35" arbitrarily.
2>  No way to resolve conflict between "Microsoft.Owin, Version=3.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35" and "Microsoft.Owin, Version=2.0.2.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35". Choosing "Microsoft.Owin, Version=3.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35" arbitrarily.
2>  No way to resolve conflict between "Microsoft.ServiceBus, Version=3.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35" and "Microsoft.ServiceBus, Version=2.5.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35". Choosing "Microsoft.ServiceBus, Version=3.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35" arbitrarily.
2>  Consider app.config remapping of assembly "Autofac.Integration.WebApi, Culture=neutral, PublicKeyToken=17863af14b0044da" from Version "3.4.0.0" [] to Version "4.0.0.0" [C:\Repos\M-KOPA M2MR2\src\MKopa.M2M.Configuration\MKopa.M2M.Configuration.Service\bin\Debug\Autofac.Integration.WebApi.dll] to solve conflict and get rid of warning.
2>  Consider app.config remapping of assembly "Microsoft.ServiceBus, Culture=neutral, PublicKeyToken=31bf3856ad364e35" from Version "2.5.0.0" [] to Version "3.0.0.0" [C:\Repos\M-KOPA M2MR2\src\MKopa.M2M.Configuration\MKopa.M2M.Configuration.Service\bin\Debug\Microsoft.ServiceBus.dll] to solve conflict and get rid of warning.
2>  Consider app.config remapping of assembly "Microsoft.Owin, Culture=neutral, PublicKeyToken=31bf3856ad364e35" from Version "3.0.0.0" [] to Version "3.0.1.0" [C:\Repos\M-KOPA M2MR2\src\MKopa.M2M.Configuration\MKopa.M2M.Configuration.Service\bin\Debug\Microsoft.Owin.dll] to solve conflict and get rid of warning.
2>  Consider app.config remapping of assembly "System.Net.Http.Formatting, Culture=neutral, PublicKeyToken=31bf3856ad364e35" from Version "5.2.0.0" [] to Version "5.2.3.0" [C:\Repos\M-KOPA M2MR2\src\MKopa.M2M.Configuration\MKopa.M2M.Configuration.Service\bin\Debug\System.Net.Http.Formatting.dll] to solve conflict and get rid of warning.
2>  Consider app.config remapping of assembly "System.Web.Http, Culture=neutral, PublicKeyToken=31bf3856ad364e35" from Version "5.2.0.0" [] to Version "5.2.3.0" [C:\Repos\M-KOPA M2MR2\src\MKopa.M2M.Configuration\MKopa.M2M.Configuration.Service\bin\Debug\System.Web.Http.dll] to solve conflict and get rid of warning.
2>  Consider app.config remapping of assembly "Newtonsoft.Json, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed" from Version "6.0.0.0" [] to Version "9.0.0.0" [C:\Repos\M-KOPA M2MR2\src\MKopa.M2M.Configuration\MKopa.M2M.Configuration.Service\bin\Debug\Newtonsoft.Json.dll] to solve conflict and get rid of warning.
2>  Consider app.config remapping of assembly "System.Web.Http.Owin, Culture=neutral, PublicKeyToken=31bf3856ad364e35" from Version "5.2.0.0" [] to Version "5.2.3.0" [C:\Repos\M-KOPA M2MR2\src\MKopa.M2M.Configuration\MKopa.M2M.Configuration.Service\bin\Debug\System.Web.Http.Owin.dll] to solve conflict and get rid of warning.
2>  Consider app.config remapping of assembly "Autofac, Culture=neutral, PublicKeyToken=17863af14b0044da" from Version "3.5.0.0" [] to Version "4.1.0.0" [C:\Repos\M-KOPA M2MR2\src\MKopa.M2M.Configuration\MKopa.M2M.Configuration.Service\bin\Debug\Autofac.dll] to solve conflict and get rid of warning.
2>C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(1820,5): warning MSB3276: Found conflicts between different versions of the same dependent assembly. Please set the "AutoGenerateBindingRedirects" property to true in the project file. For more information, see http://go.microsoft.com/fwlink/?LinkId=294190.
3>------ Publish started: Project: MKopa.M2M.Configuration.App, Configuration: Debug x64 ------
3>An item with the same key has already been added.
========== Build: 2 succeeded, 0 failed, 14 up-to-date, 0 skipped ==========
========== Publish: 0 succeeded, 1 failed, 0 skipped ==========```

I could'nt find a Service Fabric pane though, could you give me a pointer ? Hope this helps.

**Comment by dbreshears** [comment] 2016-09-15 19:38
Does this only fail locally when publishing an Upgrade?  Can you overwrite or F5 to the local cluster OK without upgrade enabled?   You are not getting far enough to invoke our Deploy-FabricApplication.ps1 script in your app project as you would see this below, hence why the SF pane isn't visible yet.

4>------ Publish started: Project: Application13, Configuration: Debug x64 ------
4>Started executing script 'Deploy-FabricApplication.ps1'.

**Comment by ravipal** [comment] 2016-09-16 01:59
Do you always get the NuGet package restore failure? Is it possible to fix this and then try publish?

NuGet Package restore failed for project 3. Virtual Devices\MKopa.M2M.VirtualDevice.Ibis2: The process cannot access the file 'C:\Repos\M-KOPA M2MR2\src\packages\Microsoft.Bcl.Build.1.0.21\build/Microsoft.Bcl.Build.Tasks.dll' because it is being used by another process..

Also share local application manifest, publish profile and the application parameter file used by the publish profile so I can try to repro this locally

**Comment by johnkattenhorn** [comment] 2016-09-16 08:29
We started getting the failures a little while ago, not sure why but it was around the time the new SDK came out.

I've already put the publish profile in the message above, but here is the parameter file and the manifest files from one of the failing apps (they all fail)

ApplicationManifest.xml

```xml
<?xml version="1.0" encoding="utf-8"?>
<ApplicationManifest xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" ApplicationTypeName="MKopa.M2M.Configuration.AppType" ApplicationTypeVersion="2.1.0-beta.76" xmlns="http://schemas.microsoft.com/2011/01/fabric">
  <Parameters>
    <Parameter Name="MKopa.M2M.Configuration.ConnectionString.Name" DefaultValue="" />
    <Parameter Name="MKopa.M2M.Configuration_InstanceCount" DefaultValue="1" />
    <Parameter Name="MKopa.M2M.Loader_InstanceCount" DefaultValue="1" />
  </Parameters>
  <ServiceManifestImport>
    <ServiceManifestRef ServiceManifestName="MKopa.M2M.ConfigurationPkg" ServiceManifestVersion="2.1.0-beta.76" />
    <ConfigOverrides>
      <ConfigOverride Name="Config">
        <Settings>
          <Section Name="ConfigurationDatabase">
            <Parameter Name="MKopa.M2M.Configuration.ConnectionString.Name" Value="[MKopa.M2M.Configuration.ConnectionString.Name]" />
          </Section>
        </Settings>
      </ConfigOverride>
    </ConfigOverrides>
    <Policies>
      <RunAsPolicy CodePackageRef="Code" UserRef="SetupLocalSystem" />
    </Policies>
  </ServiceManifestImport>
  <DefaultServices>
    <Service Name="Configuration">
      <StatelessService ServiceTypeName="ConfigurationType" InstanceCount="[MKopa.M2M.Configuration_InstanceCount]">
        <SingletonPartition />
      </StatelessService>
    </Service>
    <Service Name="Loader">
      <StatelessService ServiceTypeName="LoaderType" InstanceCount="[MKopa.M2M.Loader_InstanceCount]">
        <SingletonPartition />
      </StatelessService>
    </Service>
  </DefaultServices>
  <Principals>
    <Users>
      <User Name="SetupLocalSystem" AccountType="LocalSystem" />
    </Users>
  </Principals>
</ApplicationManifest>
```

Application Parameter File

```xml
<?xml version="1.0" encoding="utf-8"?>
<Application xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" Name="fabric:/MKopa.M2M.Configuration.App" xmlns="http://schemas.microsoft.com/2011/01/fabric">
  <Parameters>
    <Parameter Name="MKopa.M2M.Configuration.ConnectionString.Name" Value="Name=MKopa.M2M.Configuration.Production" />
    <Parameter Name="MKopa.M2M.Configuration_InstanceCount" Value="-1" />
    <Parameter Name="MKopa.M2M.Loader_InstanceCount" Value="-1" />
  </Parameters>
</Application>
```

**Comment by dbreshears** [comment] 2016-09-20 01:20
Are you able to zip up and share the repro project with us easily?  If so,  you can send it to devinb-at-microsoft-dot-com.  Otherwise, can you go to Tools->Options->Projects and Solutions -> Build and run and change the MSBuild build output verbosity to "Detailed".  Then right click on the SF Application project and select "package".

**Comment by ravipal** [comment] 2016-09-20 01:43
John, I tried with duplicating your applicationmanifest.xml and application parameter file and couldn't reproduce the error. By doing code walk thru I came up with a possible scenario where this error (An item with the same key has already been added) could happen, which is if any of the services on the target cluster has code/config/data package with duplicate name. Is your target application has this situation?

If not, can you please try the following
1. My theory is that this error happens only during upgrade, can you please check if full deployment works fine?
2. If you do full deployment, then upgrade, can you reproduce this error.

**Comment by johnkattenhorn** [comment] 2016-09-20 10:37
Do you mean like this:

```
Find all " <CodePackage Name="Code"", Subfolders, Find Results 1, "Entire Solution ( Including External Items )", ""
  C:\Repos\M-KOPA M2MR2\src\MKopa.M2M.Configuration\MKopa.M2M.Configuration.Service\PackageRoot\ServiceManifest.xml(19):  <CodePackage Name="Code" Version="2.2.0-beta0000">
  C:\Repos\M-KOPA M2MR2\src\MKopa.M2M.Gateway\MKopa.M2M.Gateway.Service\PackageRoot\ServiceManifest.xml(16):  <CodePackage Name="Code" Version="2.2.0-beta0000">
  C:\Repos\M-KOPA M2MR2\src\MKopa.M2M.Device.Lookup\MKopa.M2M.DeviceLookup.Service\PackageRoot\ServiceManifest.xml(20):  <CodePackage Name="Code" Version="2.2.0-beta0000">
  C:\Repos\M-KOPA M2MR2\src\MKopa.M2M.IBIS\MKopa.M2M.IBIS\PackageRoot\ServiceManifest.xml(161):  <CodePackage Name="Code" Version="2.2.0-beta0000">
  C:\Repos\M-KOPA M2MR2\src\MKopa.M2M.OpsConsole\MKopa.M2M.OpsConsole.Service\PackageRoot\ServiceManifest.xml(8):  <CodePackage Name="Code" Version="2.2.0-beta0000">
  C:\Repos\M-KOPA M2MR2\src\MKopa.M2M.Gateway\MKopa.M2M.Gateway2.Service\PackageRoot\ServiceManifest.xml(8):  <CodePackage Name="Code" Version="2.2.0-beta0000">
  C:\Repos\M-KOPA M2MR2\src\MKopa.M2M.Gateway.EventHub\PackageRoot\ServiceManifest.xml(14):  <CodePackage Name="Code" Version="2.2.0-beta0000">
  C:\Repos\M-KOPA M2MR2\src\MKopa.M2M.IBISAg\MKopa.M2M.IBISAg\PackageRoot\ServiceManifest.xml(161):  <CodePackage Name="Code" Version="2.2.0-beta0000">
  C:\Repos\M-KOPA M2MR2\src\MKopa.M2M.IBIS2\MKopa.M2M.IBIS2\PackageRoot\ServiceManifest.xml(209):  <CodePackage Name="Code" Version="2.2.0-beta0000">
  C:\Repos\M-KOPA M2MR2\src\MKopa.M2M.Silverbill\MKopa.M2M.Silverbill\PackageRoot\ServiceManifest.xml(175):  <CodePackage Name="Code" Version="2.2.0-beta0000">
  C:\Repos\M-KOPA M2MR2\src\MKopa.M2M.Hammerkop\MKopa.M2M.Hammerkop\PackageRoot\ServiceManifest.xml(147):  <CodePackage Name="Code" Version="2.2.0-beta0000">
  Matching lines: 11    Matching files: 11    Total files searched: 1424
```

I can try making them unique if you like and see if this works

**Comment by ravipal** [comment] 2016-09-20 22:28
I mean a single service on the cluster having multiple code/config/data package with same name. It would be great if you could share your project with me (ravipal at Microsoft.com) so I can repro.

Can you please try the following 
 1. My theory is that this error happens only during upgrade, can you please check if full deployment works fine?
 2. If you do full deployment, then upgrade, can you reproduce this error.

**Comment by ravipal** [comment] 2016-09-22 19:19
It is a bug in a diff package generation code.
The issue is caused by the way how the serviceTypes are defined. In this case a single ServiceManifest.xml file defines two services, which isn’t handled well in diff package creation code. We will address this issue in the future release.

As a workaround please disable the diff packaging in the publish profile as shown below.
\<PublishProfile xmlns="http://schemas.microsoft.com/2015/05/fabrictools" DisableAutoDiffPackaging="true"\>

**Comment by johnkattenhorn** [comment] 2016-09-23 14:42
Hey @ravipal - We tried this workaround today and it works in VS. 

Do you want us to close this issue or are you tracking the fault with it here ?

**Comment by ravipal** [comment] 2016-09-23 17:52
Since this issue is not fixed, lets keep it open.

**Comment by dendle** [comment] 2017-01-23 22:27
Hi folks,

> As a workaround please disable the diff packaging in the publish profile as shown below.

How do you disable the diff packaging? - I couldn't see a "below" 

Cheers,
Matt

**Comment by ravipal** [comment] 2017-01-24 06:08
Updated my previous comment. For some reason the escape for \< and \> disappeared and the xml tag disappeared

**Comment by dendle** [comment] 2017-01-25 20:33
thanks mate

**Comment by cjlpowers** [comment] 2017-04-05 05:40
Just ran into this issue under VS 2017. I had a actor service with two actor types. The workaround involving disabling the diff packaging worked for me.

**Comment by ravipal** [comment] 2017-04-05 17:38
@cjlpowers VS 2017 has 1.4 Service Fabric Tools which didn't have this fix. This issue is fixed in 1.5 Service Fabric Tools which will be released soon for VS 2017.

**Closed** 2017-05-18 00:47 UTC
Labels: bug, fix coming

**Comment by fehro** [comment] 2017-06-12 04:01
Same issue with my reliable actors in a VS2015 project. Setting DisableAutoDiffPackaging="true" worked.

**Comment by justinSelf** [comment] 2018-04-20 16:00
Coming in as a gravedigger to bring this up again, how does setting `DisableAutoDiffPackaging` to `true` get around this issue?
