### ISSUE TITLE
Service Fabric Reverse Proxy Decoding Suffix Path

### ISSUE THREAD

**Issue by AndrewJWaite** [Azure/service-fabric-issues#418] opened 2017-08-22 10:00 UTC
The reverse proxy appears to be decoding the suffix path of a URL encoded request.

Some URL encoded values are OK, others result in the error below.

The following request fails with **FABRIC_E_INVALID_ADDRESS**
 
[ApplicationName]/[ServiceName]/api/v1/customers/auth0%7C598dbaa40c3edf420d63590f
 
Service Fabric Reverse Proxy is decoding **%7C** as a '**|**' (pipe)

 
From the node event log...
 
eafc4c08-a207-44bc-8496-ae4ea3e60ff4 The ServiceName from URI cannot be parsed as Fabric URI: URI = identity/web/api/v1/customers/auth0%7C598dbaa40c3edf420d63590f, error = FABRIC_E_INVALID_NAME_URI
 
 
fabric:/identity/web/api/v1/customers/auth0|598dbaa40c3edf420d63590f: Input uri is not a valid naming uri.
 
We are using Auth0 and are not in control of the userId construct. This is prefixed with the identity provider: auth0, waad, facebook, google, etc and a |

**Comment by Mardoxx** [comment] 2017-08-22 14:43
Similar to https://github.com/Azure/service-fabric-issues/issues/274?

**Comment by kavyako** [comment] 2017-08-22 19:10
We will fix this for the next release (6.0). Meanwhile would any one of these workarounds work:
1. Pass the auth0|12345 value as a query parameter instead of path segment.
2. Pass the ServiceName as a query param, in that case the auth0|12345 in the path segment would still work, something like
http://localhost:19081/App1/Service1/auth|12345?ServiceName=fabric:/App1/Service1

**Comment by iamkoch** [comment] 2017-08-22 21:24
When is 6.0 scheduled for release?

**Comment by AndrewJWaite** [comment] 2017-08-24 06:18
Thanks @kavyako

As asked above, is there a timeframe that you can share for version 6.0?

Changing the contract or the SDK was something we wanted to avoid.

Another option we've tested, is for this one service to bypass the reverse proxy and be accessed directly via the load balancer and a sub domain.

This does mean the services has to run on all nodes and we lose the retry logic from the reverse proxy.

Can you see any issues with this approach, or any reasons why we shouldn't use this as a workaround?

**Comment by kavyako** [comment] 2017-08-24 16:01
6.0 is scheduled to be released end of September.
Is it a stateless service? If yes, that looks like a reasonable approach.

**Comment by AndrewJWaite** [comment] 2017-08-29 08:33
Thanks for the update @kavyako 

Yes it is a stateless service

**Comment by kavyako** [comment] 2017-09-09 00:16
Closing this issue, the fix will be in 6.0, scheduled for end of September.

**Closed by kavyako** 2017-09-09 00:16 UTC
Labels: bug, enhancement, fix coming

**Comment by iamkoch** [comment] 2017-09-15 11:02
Should this be kept open until the fix is confirmed?

**Comment by Mardoxx** [comment] 2017-09-15 19:16
I'd assume if they say it's fixed, they've tested it extensively.... maybe
:p
