### ISSUE TITLE
Distributed Dictionary is not registered when creating and manipulating collection in single transaction

### ISSUE THREAD

**Issue by mkosieradzki** [Azure/service-fabric-issues#24] opened 2016-06-28 20:42 UTC
Consider following snippet.

```
using (var tx = StateManager.CreateTransaction())
{
   var dict = await StateManager.GetOrAddAsync<IReliableDictionary<Guid, int>>(tx, "MyCollection");
   await dict.AddAsync(tx, Guid.NewGuid(), 1);
```

It throws "Distributed Dictionary is not registered".

Apparently it is impossible to create and manipulate collection in single transaction. Is it an intended behavior?

It's easy to workaround, but still doesn't feel good.

**Comment by masnider** [comment] 2016-06-28 20:45
Today this is intended behavior - the creation of the dictionary is itself a replicated operation that we need to be present and stable on the other replicas before we can do operations on it. We are considering improving this, but yeah today you need to do these operations in separate transactions.

**Comment by mkosieradzki** [comment] 2016-06-28 20:48
Thanks Matt.

**Comment by masnider** [comment] 2016-06-28 20:49
Np.

**Comment by yizhang82** [comment] 2018-07-03 22:53
@mkosieradzki I know this is two years old so it won't be that helpful to you. But anyway we have GetOrAdd overload without transaction for exactly this reason. It will create a transaction internally so after the call the dictionary should already be available for you to write/modify. We are planning to address this problem in a future release by creating a write-set for each transaction to store the dictionaries that are pending (not yet committed), and thus making it available for writes in the same transaction. 

I'm closing this for now. Let us know if you have further questions.

**Closed by yizhang82** 2018-07-03 22:53 UTC
Labels: enhancement, investigating

**Comment by mkosieradzki** [comment] 2018-07-03 23:22
@yizhang82 It's always relevant to slightly improve the initialization reliability by using transactions instead of compensation :).

**Comment by mkosieradzki** [comment] 2018-12-19 15:32
To use multiple transactions and use manual compensation if needed...
