### ISSUE TITLE
Not able to access ServiceRemotingServiceEvents in Microsoft.ServiceFabric.Services.Remoting.V2.Runtime namespace 

### ISSUE THREAD

**Issue by cpiitb** [Azure/service-fabric-issues#964] opened 2018-04-04 11:53 UTC
I am looking for a way to listen ReceiveRequest or SendResponse events while communicating with different services using ServiceRemoting.

Earlier we were able to do that with below events.

ServiceRemotingServiceEvents.ReceiveRequest
ServiceRemotingServiceEvents.SendResponse

These events were available in Microsoft.ServiceFabric.Services.Remoting.V2.Runtime namespace.
Now I am not able to find these in this namespace.

Can anyone please help me with this?
Is there any other way to get these events?

Thanks in advance.

**Comment by ashishnegi** [comment] 2018-04-04 12:04
Which SDK and runtime ? Do you have .Net Core app or Framework specifc app ?

**Comment by cpiitb** [comment] 2018-04-04 13:09
Thanks for the reply. 

I am using below nuget packages.
  <package id="Microsoft.ServiceFabric" version="6.1.480" targetFramework="net461" />
  <package id="Microsoft.ServiceFabric.Data" version="3.0.480" targetFramework="net461" />
  <package id="Microsoft.ServiceFabric.Diagnostics.Internal" version="3.0.480" targetFramework="net461" />
  <package id="Microsoft.ServiceFabric.FabricTransport.Internal" version="3.0.480" targetFramework="net461" />
  <package id="Microsoft.ServiceFabric.Services" version="3.0.480" targetFramework="net461" />
  <package id="Microsoft.ServiceFabric.Services.Remoting" version="3.0.480" targetFramework="net461" />

I am working on .Net framework (4.6.1) app.

**Comment by ashishnegi** [comment] 2018-04-06 04:58
@suchiagicha will give more details about this.

**Comment by amanbha** [comment] 2018-04-06 20:14
Closing it as duplicate of https://github.com/Azure/service-fabric-services-and-actors-dotnet/issues/105 , its tracked in actors and services repo.

**Closed by amanbha** 2018-04-06 20:14 UTC
Labels: question
