### ISSUE TITLE
MicrosoftAzure-ServiceFabric-CoreSDK fails to install via WebPi

### ISSUE THREAD

**Issue by matt-richardson** [Azure/service-fabric-issues#1020] opened 2018-04-27 20:55 UTC
Cross posting from https://github.com/MicrosoftDocs/azure-docs/issues/7781

I'm getting a 404 when using the webpicmd to install this

```
webpicmd.exe /Install /AcceptEula /SuppressReboot /Products:MicrosoftAzure-ServiceFabric-CoreSDK
```

gives:

```
The software that you obtain using the Web Platform Installer Command Line Tool is licensed to you by its owner.  Microsoft grants you no rights for third party software.
Successfully loaded primary feed: https://go.microsoft.com/?linkid=9842185
The following software is going to be installed:
EULA: 'Microsoft Visual C++ 2012 SP1 Redistributable Package (x64)', which is owned by 'Microsoft Corporation', will be downloaded from 'http://download.microsoft.com/download/1/6/B/16B06F60-3B20-4FF2-B699-5E9B7962F9AE/VSU1/vcredist_x64.exe'.
The license agreement to 'Microsoft Visual C++ 2012 SP1 Redistributable Package (x64)' may be included with the software.
You are responsible for and must separately locate, read and accept these license terms.
EULA: 'Microsoft Azure Service Fabric Runtime - 6.2.262', which is owned by 'Microsoft', will be downloaded from 'https://download.microsoft.com/download/F/C/2/FC2D7DE9-B722-4BA5-9A88-B604F636B531/MicrosoftServiceFabric.6.2.262.9494.exe'.
The license agreement to 'Microsoft Azure Service Fabric Runtime - 6.2.262' is available at 'http://go.microsoft.com/fwlink/?LinkID=780772&clcid=0x409'.
EULA: 'Microsoft Azure Service Fabric SDK - 3.1.262', which is owned by 'Microsoft', will be downloaded from 'https://download.microsoft.com/download/F/C/2/FC2D7DE9-B722-4BA5-9A88-B604F636B531/MicrosoftServiceFabricSDK.3.1.262.msi'.
The license agreement to 'Microsoft Azure Service Fabric SDK - 3.1.262' is available at 'http://go.microsoft.com/fwlink/?LinkID=780772&clcid=0x409'.
EULA: 'Microsoft Azure Service Fabric SDK - 3.1.262', which is owned by 'Microsoft' will be installed
The license agreement to 'Microsoft Azure Service Fabric SDK - 3.1.262' may be included with the software.
You are responsible for and must separately locate, read and accept these license terms.
Accepted EULA.
Starting Installation
Started downloading products...
Started downloading: 'Microsoft Visual C++ 2012 SP1 Redistributable Package (x64)'
Downloaded: 'Microsoft Visual C++ 2012 SP1 Redistributable Package (x64)'
Started downloading: 'Microsoft Azure Service Fabric Runtime - 6.2.262'
Started installing Products...
Started installing: 'Microsoft Visual C++ 2012 SP1 Redistributable Package (x64)'
DownloadFailed : Microsoft Azure Service Fabric Runtime - 6.2.262
DependencyFailed : Microsoft Azure Service Fabric SDK - 3.1.262
DependencyFailed : Microsoft Azure Service Fabric SDK - 3.1.262
Install completed (Success): 'Microsoft Visual C++ 2012 SP1 Redistributable Package (x64)'
Microsoft Visual C++ 2012 SP1 Redistributable Package (x64) : Installed
DependencyFailed : Microsoft Azure Service Fabric SDK - 3.1.262

Verifying successful installation...
Microsoft Visual C++ 2012 SP1 Redistributable Package (x64) True
Microsoft Azure Service Fabric Runtime - 6.2.262   False
    Log Location: %temp%\InstallFabricRuntime.log
Microsoft Azure Service Fabric SDK - 3.1.262       False
Microsoft Azure Service Fabric SDK - 3.1.262       False
Install of Products: FAILURE
```

in `%localappdata%\\Microsoft\Web Platform Installer\logs\install\2018-04-27T05.04.54\log.tx`t, I see

```
DownloadManager Error: 0 : Error while downloading file 'https://download.microsoft.com/download/F/C/2/FC2D7DE9-B722-4BA5-9A88-B604F636B531/MicrosoftServiceFabric.6.2.262.9494.exe'. Exception: System.Net.WebException: Url 'https://download.microsoft.com/download/F/C/2/FC2D7DE9-B722-4BA5-9A88-B604F636B531/MicrosoftServiceFabric.6.2.262.9494.exe' returned HTTP status code: 404
   at Microsoft.Web.PlatformInstaller.ManagedWinInet.OpenUrlAndFollowRedirects(Uri& uri, IntPtr& hInetFile)
   at Microsoft.Web.PlatformInstaller.ManagedWinInet.DownloadFile(Uri uri, String fileName, String& contentDispositionFileName)
   at Microsoft.Web.PlatformInstaller.InstallManager.WinInetDownloadInstallerFile(InstallerContext currentInstall, String& failureReason)
```

Seems the file was deleted from the CDN?

**Comment by lukeholbertmsft** [comment] 2018-04-27 21:05
Likely related to similar failure when using the Web Platform Installer API, it looks like there is no Installer File for the SDK ![image](https://user-images.githubusercontent.com/38229413/39384992-81382eac-4a23-11e8-8933-7c90c64455ab.png)

**Comment by sandorfr** [comment] 2018-04-30 09:27
Duplicate of https://github.com/Azure/service-fabric-issues/issues/1014 . I tried to ping Azure Support on Twitter.

**Comment by masnider** [comment] 2018-05-01 21:16
Yeah this should be a dupe. The 6.2 installation has been pulled [temporarily](https://blogs.msdn.microsoft.com/azureservicefabric/2018/04/26/second-update-on-the-service-fabric-6-2-release/). These shouldn't be showing up any more. @v-jigen fyi if they still are.

**Comment by matt-richardson** [comment] 2018-05-02 11:25
Still failing on `Microsoft Azure Service Fabric Runtime - 6.1.480`

**Comment by matt-richardson** [comment] 2018-05-12 11:17
Hello? I haven't been able to install this since the 27th of April. Is anyone looking into this?

**Comment by lukeholbertmsft** [comment] 2018-05-12 23:28
Still seeing the same errors as Matt as well.

**Comment by MicahMcKittrick-MSFT** [comment] 2018-05-13 15:37
@navyahmed @v-jigen can we have a progress update on this issue please?

**Comment by matt-richardson** [comment] 2018-05-14 01:10
Is there a way to install this that doesn't use WebPI?

**Comment by sandorfr** [comment] 2018-05-14 01:18
@matt-richardson 	look at https://github.com/Azure/service-fabric-issues/issues/1014

**Comment by lukeholbertmsft** [comment] 2018-05-14 17:58
The direct download link in [here](https://msdnshared.blob.core.windows.net/media/2018/03/Microsoft-Azure-Service-Fabric-Release-Notes-SDK-3.0-CU4-Runtime-6.1-CU4.pdf) will work for now, but it's not an ideal long-term solution for automating installation on the SDK.

**Comment by lukeholbertmsft** [comment] 2018-06-07 21:42
Can we please get an update on this? WebPi installation is still failing. I have hardcoded links to the direct downloads of SDK and runtime, but that isn't a great solution as we'll want to keep up to date.

**Comment by EM1L** [comment] 2018-06-13 09:32
Possible workaround is to use chocolatey package manager - we use it to install Service Fabric although the chocolatey is using Web Platform Installer, but still works for us. Here is the command line to try:

`choco install MicrosoftAzure-ServiceFabric-CoreSDK --source webpi --confirm`

**Comment by Va55ago** [comment] 2018-08-29 14:45
Any update on this? We are currently having to manually install this SDK every time we deploy a new Build/Release agent (time-consuming and easy to forget).

**Comment by rocifier** [comment] 2018-08-31 09:19
I think it's broken again. I can't install any version via WebPI in the past couple of days.

**Comment by MikkelHegn** [comment] 2018-08-31 14:46
I did an install using the command in the first post yesterday. @rocifier Can you share details about the error you see from running webpicmd.exe?

**Comment by Va55ago** [comment] 2018-08-31 15:56
You're right! I can also install on my local machine using the command in the original post. I posted without testing simply because I didn't see any comment saying it was fixed. My bad!

Now I just need to figure out how to incorporate this command into a PowerShell DSC script that will ensure that the SDK is always installed :)

**Comment by rocifier** [comment] 2018-09-01 02:34
@MikkelHegn I have put my log in a separate issue here: https://github.com/MicrosoftDocs/azure-docs/issues/14316

**Comment by MikkelHegn** [comment] 2018-09-03 06:32
I'm closing this, as there are no outstanding questions / issues.

**Closed by MikkelHegn** 2018-09-03 06:32 UTC
Labels: investigating
