### ISSUE TITLE
FABRIC_E_SERVER_AUTHENTICATION_FAILED: CertificateNotMatched

### ISSUE THREAD

**Issue by majkelllo** [Azure/service-fabric-issues#146] opened 2017-01-24 08:52 UTC
Hi,

When i'm publishing cluster from Visual Studio everything is going well. When i try to publish with build agent I'm receiving following error:
Failed to contact Naming Service. Attempting to contact Failover Manager Service...
Failed to contact Failover Manager Service, Attempting to contact FMM...
**FABRIC_E_SERVER_AUTHENTICATION_FAILED: CertificateNotMatched**
Any ideas ? ( I correctly configured cluster authentication in VSTS )

**Comment by MikkelHegn** [comment] 2017-01-24 16:34
Please double check the VSTS Service Connection configuration. E.g. can you connect from PowerShell using the same thumbprint (Connect-ServiceFabric) etc.? The typical issue is extra characters / whitespace in cert thumbprints when copy pasting. I have seen errors if the certificate used as input to the command [System.Convert]::ToBase64String was exported using the Export-PfxCertificate CmdLet.
 
Try to export the certificate form Certificate Management Console and rerun the System.Convert command. Check if the Client Certificate is the same.

**Comment by masnider** [comment] 2017-06-01 23:54
Hi @majkelllo - we haven't heard back from you on this. Please let us know if you are still experiencing this issue and if you were able to find and fix things per @MikkelHegn 's suggestion. If we don't hear back from you we'll consider this issue closed, so if you're still having issues please do let us know!

**Comment by awcab** [comment] 2017-08-31 16:16
I just started seeing this yesterday with no known changes to the build config.  My certificates are still valid.

**Comment by sebbrochet** [comment] 2017-09-27 16:43
@awcab, @dannythunder  I just got bitten today with the same kind of issue :)
It was working OK for several months and adding a secondary SSL certificate on the SF Cluster seems to have enforced a new constraint: **SSL certificate and SF Cluster endpoint URI should match**
 
Was able to reproduce it from a Powershell window:

```
$ClusterName = "<something>.westeurope.cloudapp.azure.com:19000"
$CertThumbprint = "<Your certificate thumbprint>"

Connect-serviceFabricCluster -ConnectionEndpoint $ClusterName -KeepAliveIntervalInSec 10 `
    -X509Credential `
    -ServerCertThumbprint $CertThumbprint  `
    -FindType FindByThumbprint `
    -FindValue $CertThumbprint `
    -StoreLocation LocalMachine `
    -StoreName My
```

The **CertificateNotMatched** was indeed the right root cause.
After changing _$ClusterName_ by the CName I have created to access my SF Cluster and that is compatible with my wildcard certificate, issue was resolved.

**Comment by rahul602** [comment] 2017-09-28 03:31
@sebbrochet I am facing the same issue. For me, the same command was working for months.
I seem to be keying in correct URI and client certificate thumbprint. Can you please explain what do you mean by After changing $ClusterName by the CName ? How exactly did you fixed the problem?

**Comment by sebbrochet** [comment] 2017-09-28 22:55
Let's say the SSL certificate you've configured on your SF Cluster is for my-site.mydomain.com and you own mydomain.com
Previously you were using cloudapp.azure.com to access your cluster and that was OK. Now there's a new constraint and you need to use a domain that **matches** with your SSL certificate.
To do so you need to go the registrar that is managing mydomain.com for you and create a CName record named my-site on mydomain.com and configured it with the previous clouapp.azure.com URI you were using. By doing so, both my-site.mydomain.com and the cloudapp.azure.com URI will resolve to  the same IP address. And now you'll be able to connect to your SF Cluster using this URI: my-site.mydomain.com:19000

**Comment by MikkelHegn** [comment] 2017-10-23 18:52
Closing as there seems to be no unresolved cases.

**Closed by MikkelHegn** 2017-10-23 18:52 UTC
Labels: investigating

**Comment by crgarcia12** [comment] 2018-10-05 01:45
I am having the same issue:

Searching for path: D:\a\r1\a\**\drop\projectartifacts\**\PublishProfiles\Cloud.xml
Found path: D:\a\r1\a\_ServiceFabricContainer-Docker container-CI\drop\projectartifacts\sfsrc\MyFirstContainer\PublishProfiles\Cloud.xml
Searching for path: D:\a\r1\a\**\drop\applicationpackage
Found path: D:\a\r1\a\_ServiceFabricContainer-Docker container-CI\drop\applicationpackage
Imported cluster client certificate with thumbprint 'AE2D7660A7DE35712226AD954A9F77FF80E81199'.
##[warning]Failed to contact Naming Service. Attempting to contact Failover Manager Service...
##[warning]Failed to contact Failover Manager Service, Attempting to contact FMM...
Service fabric SDK version: 3.2.176.9494.
##[error]FABRIC_E_SERVER_AUTHENTICATION_FAILED: CertificateNotMatched
##[section]Finishing: Deploy Service Fabric Application

My cluster has no SSL cert, and the thumbprint is "Admin client"
I can access the management portal of SF using that cert and skiping the ssl validation

Any ideas how to troubleshoot?
Thanks!

**Comment by arjunmishra13** [comment] 2020-07-14 23:29
If this issue is occurring on your service fabric cluster make sure that in the manifest, the cluster is set to read certs by subject name
e.g:
`<ClusterCertificate X509FindValue="SubjectName" X509FindType="FindBySubjectName" />`

**Comment by viktors-telle** [comment] 2020-08-31 06:49
Hi @arjunmishra13! Do you know how to add this line to the cluster manifest? I am using Terraform to describe the cluster, but ARM templates also will do.
