### ISSUE TITLE
6.1.232-preview stateful ASP.Net Core 2 template does not seem to work.

### ISSUE THREAD

**Issue by Eneuman** [Azure/service-fabric-issues#643] opened 2017-11-15 19:20 UTC
I created a new Service Fabric application using the latest SDK installed.
I selected to create a ASP.Net Core 2.0 Statefull service. (netcoreapp2)

Deployed it to my local cluster and it will not start. No changes was made to the project.

This is the error I recive:

![image](https://user-images.githubusercontent.com/12099277/32855143-399255c6-ca41-11e7-95c2-71c21b39c530.png)

Visual studio does not give me any exceptions other then:
The program '[7936] Web1.exe' has exited with code -2146232797 (0x80131623).
even though I disabled "Just My code" and selected every option in "Exception Settings".

Creating a stateless service works fine.

**Comment by raunakpandya** [comment] 2017-11-16 07:10
@Eneuman - Can you please share the application logs and the environment (Windows/ Linux) you are on?

**Comment by Eneuman** [comment] 2017-11-16 07:18
The only thing in there related to SF is this row:

`End(BeginDownloadAndActivate): Error=HostingDeploymentInProgress, VersionedServiceTypeId={SFType_App27:Web1Pkg:Web1Type,1.0:1.0:131552901826078167}, ActivationContext=, ServicePackagePublicActivationId=, SequenceNumber=185`

**Comment by raunakpandya** [comment] 2017-11-16 07:57
@Eneuman - What I meant was, can you share the SF cluster logs? Also can you check you event viewer under Windows Logs -> Application and look for event ID 1025, Source - .NET Runime which relates to your application crashing? If you find one, can you share the event data?

**Comment by Eneuman** [comment] 2017-11-16 08:03
Sure,

Complete loggs can be downloaded from [here](https://links-my.sharepoint.com/personal/per_bornsjo_links_se/_layouts/15/guestaccess.aspx?docid=0e50002a6de964c2caa6e2712d86eb03c&authkey=AZo0bIdIIfNbuCRl3z_qGkw&expiration=2017-11-29T23%3A00%3A00.000Z&e=0774d6594a0d477e9b6852a101b06141)

I dont see any error/warning Events with 1025 or source .Net Runtime

**Comment by raunakpandya** [comment] 2017-11-16 08:25
@Eneumen - I am looking for the cluster logs which would be located somewhere at c:\sfdevcluster\data\log\traces

**Comment by Eneuman** [comment] 2017-11-16 08:28
@raunakpandya I cannot find a log directory under c:\sfdevcluster\data\

**Comment by raunakpandya** [comment] 2017-11-16 08:32
Can you check once again? In the complete logs you shared above, I don't see the logs. Instead it contains your application package.

**Comment by Eneuman** [comment] 2017-11-16 08:57
I created a new package containing only the traces. 
Try [this](https://links-my.sharepoint.com/personal/per_bornsjo_links_se/_layouts/15/guestaccess.aspx?docid=03ace2b4747364f3c8be0368b891a95ce&authkey=AfmU625_rTv0LDBLARGKwPs&expiration=2017-11-29T23%3A00%3A00.000Z&e=c2eb322004d6421a84ea2f0da6ae5877) one.

**Comment by hrushib** [comment] 2017-11-22 17:18
@Eneuman, I looked at the logs attached by you, logs indicate process exited with exit code **3221225786** instead of **-2146232797** mentioned in this issue. It is possible that the logs for the period when you experienced this issue are missing from the log file shared by you. If possible, please recreate your Local cluster, repro this issue and then share the logs.

Please note that, there is known issue with CoreCLR dotnet/coreclr#12668 on non en-us version of Windows 10 which results in Stateful service process crashing with **-2146232797**, refer to #619 for details.

If possible share the application project which may help us to reproduce this issue at our end.

**Comment by Eneuman** [comment] 2017-11-22 19:48
Hi
I created a new Service Fabric Application and upgraded all the Nuget Packages to latest before publishing it. Its a Statefull ASP.Net Core 2 Web Api Service called "Web1" in a application called "TestSF".

I'm still getting the same error. 

> Unhealthy event: SourceId='System.Hosting', Property='CodePackageActivation:Code:EntryPoint', HealthState='Warning', ConsiderWarningAsError=false. There was an error during CodePackage activation.The service host terminated with exit code:2148734499

I'm on Windows 10 Pro Swedish version.



You can download the traces from [here](https://links-my.sharepoint.com/personal/per_bornsjo_links_se/_layouts/15/guestaccess.aspx?docid=0c46d3e4d3fdb45c0a6cb5ee6e6214445&authkey=ATWBTSknwUqDtxyYUS6NEPE&expiration=2017-12-19T23%3A00%3A00.000Z&e=7011f1791f84499a8aadd0c2174e2d3f)

**Comment by hrushib** [comment] 2017-11-23 11:11
Had look at the logs, from logs it seems that this issue is due to dotnet/coreclr#12668 itself. Can you try workaround mentioned in this issue to see if that resolves your problem? 

If the workaround doesn't work then do share the sample code package where this issue is present.

**Comment by Eneuman** [comment] 2017-11-23 11:50
I did try and add

```
        Thread.CurrentThread.CurrentUICulture = new CultureInfo("en-US");
        Thread.CurrentThread.CurrentCulture = new CultureInfo("en-US");
```

to my Main in Programs.cs but the problem is still there.

To reproduce this:
1) Install Windows 10 Pro 1703 Swedish Edition.
2) Install VS2017 15.4
3) Install .Net Core 2.0.3
4) Install Service Fabric
5) Create a Statefull .Net Core 2.0 Service (I choose Web API) using the template supplies in VS.
6) Deploy it without modifying anything

The sample im running is the one created by the Visual Studio template. I have not changed anything, I just pressed Debug after creating it.

The problem might be related to the CLR issue you showed, but It has not been fixed in 2.0.3 as stated in that issue.

**Comment by Eneuman** [comment] 2017-11-23 13:09
You can now download the complete sample from [here](https://links-my.sharepoint.com/personal/per_bornsjo_links_se/_layouts/15/guestaccess.aspx?docid=0c66e5b75c34542beb0c3819fb59fcbc1&authkey=AWQeUz6att3KWiva9y1nV4k&expiration=2017-12-20T23%3A00%3A00.000Z&e=ce66e9074d7040308d10438f21b177a2)

**Comment by tarynt** [comment] 2017-11-23 13:11
@Eneuman I've had the same issue as you, try adding `new ArgumentException();` to the first line of Main. See #619

**Comment by Eneuman** [comment] 2017-11-23 13:18
@tarynt Thank you for the workaround. It worked great!
This confirms that the problem I'm having is related to #619 and that the problem has **not** been fixed in 2.0.3. 

Please keep this issue open or reopen #619.

**Comment by hrushib** [comment] 2017-11-23 13:26
Thanks @Eneuman for confirming that the workaround worked for you. Will keep this issue open to understand why this is not working with 2.0.3.

**Comment by Eneuman** [comment] 2017-11-26 16:22
After adding the workaround I could publish to my local Dev SF but when I publish the code to my VMs in Azure, it gets stuck in a upgrade loop (been looping for 5 hours). I get this error when it tried to upgrade:


```
Error event: SourceId='System.FM', Property='State'. Partition is in quorum loss. fabric:/Ekonomi/Forsaljning 3 3 4dd18c68-d066-4d66-96ec-c09a220346c3   S/S Down _BackEnd_0 131551570025625077   S/S Down _BackEnd_2 131554824074422752   P/P Ready _BackEnd_3 131561681788031665   (Showing 3 out of 3 replicas. Total available replicas: 1)  For more information see: http://aka.ms/sfhealth
--

Error event: SourceId='System.Hosting', Property='CodePackageActivation:Code:EntryPoint'. There was an error during CodePackage activation.The service host terminated with exit code:2148734499
--
```

and this warning:

```
Unhealthy event: SourceId='System.CRM', Property='UpgradePrimarySwapFailure_4dd18c68-d066-4d66-96ec-c09a220346c3', HealthState='Warning', ConsiderWarningAsError=false.
The Cluster Resource Manager was unable to issue Upgrade Primary Swaps for this Partition:
fabric:/Ekonomi/Forsaljning Partition 4dd18c68-d066-4d66-96ec-c09a220346c3 could not be swapped during upgrade, due to the following constraints and properties:  
TargetReplicaSetSize: 3
Placement Constraint: (nodeType==BackEnd)
Parent Service: N/A

Constraint Elimination Sequence:
IsInTransition eliminated 2 possible node(s) for placement -- 0/2 node(s) remain.

Nodes Eliminated By Constraints:

IsInTransition -- Nodes must not have Replicas of this partition currently in Transition:
--
FaultDomain:fd:/2 NodeName:_BackEnd_2 NodeType:BackEnd NodeTypeName:BackEnd UpgradeDomain:2 nodeType:BackEnd UpgradeDomain: ud:/2 Deactivation Intent/Status: None/None
FaultDomain:fd:/0 NodeName:_BackEnd_0 NodeType:BackEnd NodeTypeName:BackEnd UpgradeDomain:0 nodeType:BackEnd UpgradeDomain: ud:/0 Deactivation Intent/Status: None/None
```

and its just keeps on trying. Not rolling back as it should.
I'm about to lose faith in .Net Core 2 on SF :(

**Comment by nrandell** [comment] 2018-01-31 22:36
This still seems to be an issue in the released packages - putting 'new ArgumentException()' at the start of main fixed it.

**Comment by nrandell** [comment] 2018-01-31 22:44
I've just referenced runtime version 2.0.5 and it works ok.

    <RuntimeFrameworkVersion>2.0.5</RuntimeFrameworkVersion>

This is with the standard stateful service from a new service fabric application project in visual studio, so it's easy to reproduce!

**Comment by hrushib** [comment] 2018-02-01 09:35
@nrandell, do you mean by using **2.0.5** as a RuntimeFrameworkVersion, you no more require workaround for stateful service to work as expected on **non** **en-us** version of OS?

**Comment by nrandell** [comment] 2018-02-01 09:47
That's correct - I'm in the UK, so on **en-gb**.

Running the stateful .Net core service with no code changes failed. 
Putting in `new ArgumentException()` at the start of main() fixed it. 
Removing `new ArgumentException()` and adding the **RuntimeFrameworkVersion** to the **csproj** also fixed it.

**Comment by hrushib** [comment] 2018-02-26 12:34
Closing this issue as Applications are working as expected post use of 2.0.5 framework version.

**Closed by hrushib** 2018-02-26 12:34 UTC
