### ISSUE TITLE
Linux cluster's Inbound NAT Rules use RDP port for SSH

### ISSUE THREAD

**Issue by jjcollinge** [Azure/service-fabric-issues#513] opened 2017-10-05 14:47 UTC
I'm sure this is a known issue but on a vanilla Linux SF cluster deployment - the default Inbound NAT Rules map RDP port (3389 + n) to SSH (22 + n). I appreciate this is a cosmetic issue but none the less it has caused customers of mine to attempt an RDP connection to the Linux nodes (facepalm). Also due to the lack of full VMSS portal support, you can not currently edit the NAT rules once provisioned.

![sshsf](https://user-images.githubusercontent.com/7241190/31233482-ae49ad38-a9e4-11e7-86fe-e7ef2c5a41fd.PNG)

**Comment by mani-ramaswamy** [comment] 2017-10-10 15:21
Thanks - that's a fair comment. We tried to keep it the same as Windows, but should be able to adjust this.

**Comment by mani-ramaswamy** [comment] 2017-10-13 17:39
We revisited this. The problem is if we started at 22, then we run into commonly used ports (e.g., 80 as just one example). The other option is to do 22, and then jump to some other higher port which is also a bit confusing. VMSS by default starts at 50000 for ssh. We started with 3389 because that's what we do for RDP in Windows, and so you can ssh to machines starting from there. 

Put another way, any which way, there is no neat solution to solve this, especially when clusters span hundreds of nodes. I had it documented @ https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-get-started-azure-cluster (at the end). 

If there are other places that you think I should call it out, happy to do so.  Closing this issue for now, but reopen as appropriate.

**Closed by mani-ramaswamy** 2017-10-13 17:39 UTC
Labels: enhancement

**Comment by jjcollinge** [comment] 2017-10-16 19:58
Thanks @mani-ramaswamy - makes sense. I appreciate there's no ideal solution, at least using a custom port range you'll avoid the confusing RDP service label.
