### ISSUE TITLE
Unable to deploy stateful service

### ISSUE THREAD

**Issue by mgrishkov** [Azure/service-fabric-issues#627] opened 2017-11-11 23:02 UTC
I create a [sample application](https://github.com/mgrishkov/sf-statefull-sample) with stateful service. It use net462 as a target framework. After publishing it comes unhealthy. 
The most interesting thing I found in debug log:
`
An unhandled exception of type 'System.IO.FileLoadException' occurred in Unknown Module.
Could not load file or assembly "System.Fabric, Version=6.0.0.0, Culture=neutral, PublicKeyToken=null"  or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
`
Application package contains System.Fabric.dll but it version 6.0.219.9494.

Can you please help me to determine what is wrong with my sample application.

P.S. Here you can see full text of [build log](https://github.com/mgrishkov/sf-statefull-sample/blob/master/logs/build.log), [debug log](https://github.com/mgrishkov/sf-statefull-sample/blob/master/logs/debug.log) and [service fabric tools log](https://github.com/mgrishkov/sf-statefull-sample/blob/master/logs/service-fabric-tools.log).

**Comment by Mardoxx** [comment] 2017-11-12 14:50
What version is your cluster runtime?

**Comment by mgrishkov** [comment] 2017-11-12 14:53
![image](https://user-images.githubusercontent.com/3851145/32700167-4566e04a-c7d2-11e7-864c-ede7d949ab33.png)
![image](https://user-images.githubusercontent.com/3851145/32700168-4ff8c4ba-c7d2-11e7-8100-274cf38518c9.png)

**Comment by mgrishkov** [comment] 2017-11-12 14:57
According to the `Get-ServiceFabricRuntimeSupportedVersion -Latest`  it is the last available runtime version.

```
Version      SupportExpiryDate TargetPackageLocation
-------      ----------------- ---------------------
6.0.219.9494                   https://download.microsoft.com/download/B/0/B/B0BCCAC5-65AA-4BE3-AB13-D5FF5890F4B5/6.0.219.9494/MicrosoftAzureServiceFabric.6.0.219.9494.cab
```

**Comment by mgrishkov** [comment] 2017-11-15 06:04
I tried to update local dev. cluster up to 2.8.232.9494 but it isn't solve the issue. It's sad...

**Comment by mgrishkov** [comment] 2017-11-15 06:41
There are some changes after updating packages to the latest versions
* Microsoft.ServiceFabric Version="6.1.232-preview"
* Microsoft.ServiceFabric.Services Version="3.0.232-preview"
* Microsoft.ServiceFabric.Services.Remoting Version="3.0.232-preview"
* Microsoft.ServiceFabric.Data Version="3.0.232-preview"
* Microsoft.ServiceFabric.FabricTransport.Internal Version="3.0.232-preview"

Service fabric explorer shows following warning (unfortunately it is on russian but you still can catch the idea) - **unable to load assembly Microsoft.ServiceFabric.Data.Interfaces, Version=6.0.0.0**:
`
Unhealthy event: SourceId='RunAsync', Property='RunAsyncUnhandledException', HealthState='Warning', ConsiderWarningAsError=false. System.IO.FileLoadException: Не удалось загрузить файл или сборку "Microsoft.ServiceFabric.Data.Interfaces, Version=6.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35" либо одну из их зависимостей. Найденное определение манифеста сборки не соответствует ссылке на сборку. (Исключение из HRESULT: 0x80131040) Имя файла: 'Microsoft.ServiceFabric.Data.Interfaces, Version=6.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'    в Sample.Service.UTILS.Logging.LoggingService.RunAsync(CancellationToken cancellationToken)    в Microsoft.ServiceFabric.Services.Runtime.StatefulServiceBase.Microsoft.ServiceFabric.Services.Runtime.IStatefulUserServiceReplica.RunAsync(CancellationToken cancellationToken)    в Microsoft.ServiceFabric.Services.Runtime.StatefulServiceReplicaAdapter.d__22.MoveNext()  === Информация о состоянии предварительной привязки === Журнал: DisplayName = Microsoft.ServiceFabric.Data.Interfaces, Version=6.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35  (Fully-specified) Журнал: Appbase = file:///C:/SfDevCluster/Data/_App/_Node_0/Sample.UTILS.LoggingType_App9/Sample.Service.UTILS.Logging.Code.1.0.0/ Журнал: Initial PrivatePath = NULL Вызов сборки: Sample.Service.UTILS.Logging, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null. === Журнал: данная привязка начинается в контексте загрузки default. Журнал: используется файл конфигурации приложения: C:\SfDevCluster\Data\_App\_Node_0\Sample.UTILS.LoggingType_App9\Sample.Service.UTILS.Logging.Code.1.0.0\Sample.Service.UTILS.Logging.exe.Config. Журнал: используется файл конфигурации главного узла:  Журнал: используется файл конфигурации компьютера из C:\Windows\Microsoft.NET\Framework64\v4.0.30319\config\machine.config. Журнал: ссылка после применения политики: Microsoft.ServiceFabric.Data.Interfaces, Version=6.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35 Журнал: попытка скачивания нового URL file:///C:/SfDevCluster/Data/_App/_Node_0/Sample.UTILS.LoggingType_App9/Sample.Service.UTILS.Logging.Code.1.0.0/Microsoft.ServiceFabric.Data.Interfaces.DLL. Предупреждение: при проверке имени сборки обнаружено несовпадение: Major Version Ошибка: не удалось завершить установку сборки (hr = 0x80131040). Проверка прекращена.
`

P.S.: I updated sources in repository and data from logs.

**Comment by raunakpandya** [comment] 2017-11-15 13:10
@mgrishkov  Thanks for reporting. Yes, this is an issue when targeting 462. The preview versions currently have the fix for running the app targeting .NET Core 2.0. We are investigating and will fix this issue in the upcoming release very soon.

**Comment by mgrishkov** [comment] 2017-11-15 13:55
@raunakpandya thank you for response. Can you please attach the issue to hotfix pull request or let me know that the issue was fixed. I hope you will fix it as soon as possible.

**Comment by hrushib** [comment] 2017-11-17 09:31
@mgrishkov, thanks for providing sample application for repro of this issue. Root cause is identified and fix is in process of validation.

**Comment by mgrishkov** [comment] 2018-01-30 07:54
Is it fixed in 6.1 release?

**Comment by am11** [comment] 2018-01-30 19:18
Also getting:

> Could not load file or assembly 'Microsoft.ServiceFabric.Data.Interfaces, Version=6.0.0.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.'

with 6.1. In pkg, there is a `Microsoft.ServiceFabric.Data.Interfaces.dll`, but with version 5.0.0.

Unzipped the raw nupkg (https://www.nuget.org/api/v2/package/Microsoft.ServiceFabric.Data/3.0.456) and found out that there is wrong assembly for .NET Standard 2.0 with v5 at `ref\netstandard2.0\Microsoft.ServiceFabric.Data.Interfaces.dll` but correct one with v6 for .NET Framework at `lib\net45\Microsoft.ServiceFabric.Data.Interfaces.dll`.

Is there any workaround? I tried adding an assembly redirect as below, but no dice:

```xml
      <dependentAssembly>
        <assemblyIdentity name="Microsoft.ServiceFabric.Data.Interfaces" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-6.0.0.0" newVersion="5.0.0.0" />
      </dependentAssembly>
```

**Comment by am11** [comment] 2018-01-30 21:36
Apologies, I take it back 😎 
Updated SF SDK to 3.0.X (using web platform installer) and now cluster is running service with netcoreapp2.0 TFM! 🎉 🚀

**Closed** 2018-02-15 11:35 UTC
Labels: bug, fix coming

**Comment by dongshengfengniaowu** [comment] 2018-09-21 08:38
Just add System.Fabric.Management.ServiceModel.dll with Nuget, then it will be ok.

**Comment by ChristianMes** [comment] 2018-09-21 08:48
Is that the official fix for the stable Service Fabric tooling to install a preview, third party nuget package with it's dependencies?
@raunakpandya

**Comment by hrushib** [comment] 2018-09-27 08:00
@ChristianMes, please open another issue for this with following details in addition to the details mentioned by you above. Please mention if this is newly generated project using Service Fabric service template available from Visual Studio, if so mention the template used to generate the project. If possible share minimal sample project where this issue is happening.
