### ISSUE TITLE
Could not load file or assembly ‘System.Fabric, Version=5.0.0.0

### ISSUE THREAD

**Issue by grahamehorner** [Azure/service-fabric-issues#140] opened 2017-01-19 18:47 UTC
using the VisualStudio 2015 'ASP.NET Core (Preview)' template results in the
build/deployment works but when running exceptions with  

Could not load file or assembly ‘System.Fabric, Version=5.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35’ 
or one of its dependencies. An attempt was made to load a program with an incorrect format.

**Comment by MikkelHegn** [comment] 2017-01-23 19:03
Not a known issue.
A few follow-up questions:
Can you give more info on the ASP.NET Core tooling version? Are you only using  ASP.NET Core services? Is this reproducible in a new project? The version of Service Fabric NuGet packages and runtime / SDK installed.

Thanks.

**Comment by grahamehorner** [comment] 2017-01-30 14:44
@MikkelHegn I'm using VS2015 preview-2 tooling; to reproduce I simply use the wizard to create the project and run.  boom exception

**Comment by CassandraDied** [comment] 2017-02-02 14:13
The same problem without ASP.NET core. Just added new stateless service several days ago and SF isn't able to instantiate it in Azure, but locally in debug everything works well. Everything works on-premises also. I can compare both System.Fabric.dll for working and not working services and they look alike.

**Comment by CassandraDied** [comment] 2017-02-02 14:18
Okay, I found the root cause in my case: it was wrong platform.

**Comment by Marusyk** [comment] 2017-02-17 18:24
@CassandraDied What platform did you install?

**Comment by vturecek** [comment] 2017-05-25 18:15
Closing this out, feel free to reopen if you have another repro.

**Closed by vturecek** 2017-05-25 18:15 UTC

**Comment by Jose-CF** [comment] 2017-07-03 06:29
Happening over here but platform is correct. Any ideas?

**Comment by Jose-CF** [comment] 2017-07-10 08:40
So, all assembles are x64. Still this is happening.

**Comment by wonix** [comment] 2017-12-07 21:55
Event if you're specifying platform target x64 on the build server, check your project build configuration to see if Release is set to platform target x64. That's how I resolved a very similar issue.

**Comment by abatishchev** [comment] 2018-03-26 22:04
Getting this error when upgraded Runtime/SDK 6.0.0.0 to the latest and try to run a stale project that still references 5.0.0.0

**Comment by rpili1313** [comment] 2019-01-04 08:36
What was the solution to this issue because experiencing the same here. I think it started after updating GIT.

**Comment by MikkelHegn** [comment] 2019-01-04 09:00
What's the exact issue you are facing?
From previous comments it sounds like the platform in the build configuration was not set correctly to x64.

**Comment by rpili1313** [comment] 2019-01-04 10:36
I'm trying to connect to my SF with PS  but get the same error as topic starter. 
Yesterday everything was still working.

**Comment by MikkelHegn** [comment] 2019-01-07 10:07
@rpili1313 - please open a new issue for the scenario of using PowerShell. If you can add info about the version of the module, that would be helpful. Thanks.
