### ISSUE TITLE
Running SF app via F5 from Visual Studio results in HTTP request spam to web API

### ISSUE THREAD

**Issue by sandersaares** [Azure/service-fabric-issues#75] opened 2016-10-19 07:37 UTC
I have a Service Fabric solution in Visual Studio, consisting of an actor and a web API. When I press F5 to start debugging, the web API is called, triggering some code in the actor.

If this code in the actor fails (e.g. due to some timeout), I find that the HTTP request to the web API is repeated many times on startup, even before a browser window shows up. Finally, after repeating the call around 20 times, the browser opens and shows me the error message.

Is this behavior intentional? Some sort of retry logic? Please help me understand what triggers this behavior (should I also expect this in production environments?) and how to disable this behavior, as it is not desirable for me to have to wait until the code fails 20+ times on startup. I just want to see the error message the first time it appears when I start debugging.

Here is a screenshot of the ETW log viewer - the web requests keep repeating for quite a few pages. The failure situation here was a TaskCanceledException from the actor code.

![image](https://cloud.githubusercontent.com/assets/9914262/19509533/cca6c57a-95e7-11e6-8159-13b1797e9f43.png)

Here is what finally shows up in the browser after it actually opens the page:

```
This XML file does not appear to have any style information associated with it. The document tree is shown below.
<Error>
<Message>An error has occurred.</Message>
<ExceptionMessage>One or more errors occurred.</ExceptionMessage>
<ExceptionType>System.AggregateException</ExceptionType>
<StackTrace>
at Microsoft.ServiceFabric.Services.Communication.Client.ServicePartitionClient`1.<InvokeWithRetryAsync>d__7`1.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at Microsoft.ServiceFabric.Services.Remoting.Client.ServiceRemotingPartitionClient.<InvokeAsync>d__8.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at Microsoft.ServiceFabric.Services.Remoting.Builder.ProxyBase.<InvokeAsync>d__0.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at Microsoft.ServiceFabric.Services.Remoting.Builder.ProxyBase.<ContinueWithResult>d__7`1.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult() at WebApi1.Controllers.ValuesController.<Get>d__0.MoveNext() in C:\Source\CloudExperiments\SimpleSfActor\WebApi1\Controllers\ValuesController.cs:line 22 --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at System.Threading.Tasks.TaskHelpersExtensions.<CastToObject>d__3`1.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__0.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__5.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__5.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at System.Web.Http.Filters.ActionFilterAttribute.<ExecuteActionFilterAsyncCore>d__0.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__2.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at System.Web.Http.Dispatcher.HttpControllerDispatcher.<SendAsync>d__1.MoveNext()
</StackTrace>
<InnerException>
<Message>An error has occurred.</Message>
<ExceptionMessage>A task was canceled.</ExceptionMessage>
<ExceptionType>System.Threading.Tasks.TaskCanceledException</ExceptionType>
<StackTrace>
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult() at FileThingy.AzureStorage.<CreateBlobIfNotExistsAsync>d__4.MoveNext() in C:\Source\CloudExperiments\SimpleSfActor\FileThingy\AzureStorage.cs:line 36 --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at System.Runtime.CompilerServices.TaskAwaiter.GetResult() at FileThingy.FileThingy.<EnsureStorageAssetsAreCreatedAsync>d__15.MoveNext() in C:\Source\CloudExperiments\SimpleSfActor\FileThingy\FileThingy.cs:line 188 --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at System.Runtime.CompilerServices.TaskAwaiter.GetResult() at FileThingy.FileThingy.<GetReadUrlAsync>d__9.MoveNext() in C:\Source\CloudExperiments\SimpleSfActor\FileThingy\FileThingy.cs:line 76 --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at Microsoft.ServiceFabric.Services.Remoting.Builder.MethodDispatcherBase.<>c__DisplayClass1`1.<ContinueWithResult>b__0(Task`1 t) at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke() at System.Threading.Tasks.Task.Execute() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at Microsoft.ServiceFabric.Services.Remoting.Builder.MethodDispatcherBase.<Microsoft.ServiceFabric.Services.Remoting.IMethodDispatcher.DispatchAsync>b__5(Task`1 t) at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke() at System.Threading.Tasks.Task.Execute() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at Microsoft.ServiceFabric.Actors.Runtime.ActorManager.<>c__DisplayClass47.<ActorMethodDispatch>b__46(Task`1 t) at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke() at System.Threading.Tasks.Task.Execute() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at Microsoft.ServiceFabric.Actors.Runtime.ActorManager.<DispatchToActorConcurrencyLockHeldAsync>d__49.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at Microsoft.ServiceFabric.Actors.Runtime.ActorManager.<DispatchToActorAsync>d__b.MoveNext() --- End of stack trace from previous location where exception was thrown --- at Microsoft.ServiceFabric.Actors.Runtime.ActorManager.<DispatchToActorAsync>d__b.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at Microsoft.ServiceFabric.Services.Remoting.Runtime.ServiceRemotingCancellationHelper.<DispatchRequest>d__5.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at Microsoft.ServiceFabric.Actors.Remoting.Runtime.ActorServiceRemotingDispatcher.<HandleActorMethodDispatch>d__c.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at Microsoft.ServiceFabric.Services.Communication.FabricTransport.Runtime.NativeServiceCommunicationMessageHandlerBroker.<RequestResponseAsync>d__3.MoveNext()
</StackTrace>
</InnerException>
</Error>
```

**Comment by masnider** [comment] 2016-10-19 18:56
I don't think that it is the http request that is getting retried, but the call to the actor. The Actor proxy does have default retry policies that will result in the calls to the actor being retried, so that does seem to correspond with what you're seeing. You would have to add some tracing to your stateless web service in order to see if the requests were being retried there - but they aren't present in the list above. Also do you know what is triggering the web API to be called? I don't believe that we would do that by default.

**Comment by sandersaares** [comment] 2016-10-20 06:42
When I press F5 to start debugging, a web browser window is opened by Visual Studio, triggering a GET call to the web API. No custom configuration involved. It started doing this immediately as I added the stateless service hosting the web API to my solution - I expect the project was configured as a startup project, to open via that URL, by the project templates.

This web API call is what is being logged as "Service request 'Get' started" in the above screenshot. You can see this line repeating in the log, so it does seem that the web API is being called multiple times. I also added a custom log line to the start of the web API method to confirm this:

![image](https://cloud.githubusercontent.com/assets/9914262/19548698/bd006f4c-96a8-11e6-83d6-9f8350ca4186.png)

To reproduce from a clean slate:

1. Create a new SF solution, initial project type Stateless Web API.
1. Replace the body of ValuesController.Get() with `throw new OperationCanceledException();`
1. Press F5.
1. Observe repeated requests to Get, *before any browser window is even visible* (it will also break into the debugger due to the exception, from which you can continue or just disable the breaking in VS exception settings).

![image](https://cloud.githubusercontent.com/assets/9914262/19548806/5e36986e-96a9-11e6-8990-955349057970.png)

**Comment by masnider** [comment] 2016-10-20 21:34
Sorry that I didn't see the ServiceRequest in the original report. My bad. I'd guess then that the error is getting returned and that VS (or whatever is making the WebAPI call is retrying). Can you try the [workaround here ](http://stackoverflow.com/questions/716494/how-do-i-stop-visual-studio-from-launching-a-new-browser-window-every-single-tim) or see if it leads you in the right direction? If this doesn't work or isn't helpful let me know and I can dig around to find someone who knows more about VS's behavior in this situation.

**Comment by sandersaares** [comment] 2016-10-21 04:54
I fear that does not help me toward a solution. The opening of the browser is desirable, only the retry behavior is not. This type of retry behavior does not occur with regular Web API projects, so it has to be something specific to Service Fabric.

**Comment by sandersaares** [comment] 2016-10-21 07:47
One more data point to add: this behavior is not constrained to failures! Here I have a log screenshot from a startup after pressing F5, which does two successful calls to my web API.

![image](https://cloud.githubusercontent.com/assets/9914262/19590590/68592712-977b-11e6-8bcd-a46446c69ddc.png)

**Comment by MikkelHegn** [comment] 2016-10-21 15:48
Hi, are you able to share you repo project and the traces that identified devenv.exe as the originator of those requests? mikhegn microsoft.com.

**Comment by sandersaares** [comment] 2016-10-26 08:08
Sure. Repro project is here: https://github.com/sandersaares/servicefabric-f5-manyrequests-repro

I will email you the traces I took and log files.

**Comment by MikkelHegn** [comment] 2016-10-27 05:37
Thanks - we have a repro and will investigate.

**Comment by MikkelHegn** [comment] 2016-10-27 23:41
The reason for the behavior observed above is that devenv.exe (VS) pings the URL specified in the “Application URL” property of the project to figure out when the service is responding with success and we can open the browser. We keep doing that until the service responds successfully.  The timeout is 30 seconds. 
If you clear the property, VS will not ping the service, nor open the browser.
This is by design and I currently see no reason to change this behavior.

**Comment by sandersaares** [comment] 2016-10-28 06:31
Thank you for taking a look! I hope my experience helps the design drift in a more user-friendly direction in the future, as at the moment the 30 second delay is purely a negative in my scenario.

**Comment by sandersaares** [comment] 2016-11-03 08:43
I am reopening this, as the behavior appears to deviate from the described. A 30 second timeout on error would be understandable, if not desirable in my scenario. However, I just experienced VS take over 5 minutes just to open the web page! Having this sort of large delay when operating using default VS settings and default VS project templates seems like a UX issue that should be corrected.

Some screenshots of the ends of the timeline, from F5 to browser opening.

![image](https://cloud.githubusercontent.com/assets/9914262/19959901/5b49bf6e-a1b2-11e6-838b-7fca5cb7dad9.png)

![image](https://cloud.githubusercontent.com/assets/9914262/19959904/5e5998aa-a1b2-11e6-9169-1d6f44956d11.png)

**Comment by MikkelHegn** [comment] 2016-11-03 16:43
Is the above experience using the code in the shared project? I will go ahead and give it a try if that is the case.

**Comment by sandersaares** [comment] 2016-11-04 06:39
The total duration of the "startup retry storm" appears to be correlated with the duration of a single request. I have modified the shared project to have a 10 second timeout (instead of instant exception) to better showcase this. This resulted in 30 requests made over a period of a little over 5 minutes, before the browser opened.

**Comment by MikkelHegn** [comment] 2016-11-04 15:58
Hi Sander, I was wrong in my initial statement about the retry. We do not have a retry timeout of 30 sec, but a maximum retry count of 30 (just as you observe above). The timeout that we have is the default of the HttpClient (I think it is 100 sec).

I don't see much we can do, unless we want to start evaluating status codes in these cases and determine whether a non 200 status code is intentional, or just the service not being ready, but that is very hard to generalize on.

**Comment by sandersaares** [comment] 2016-11-07 08:06
Why not open the browser when the Service Fabric logic says the application is ready? There already seems to be a check for this:

> Service Status:
> fabric:/Application10/WebApi1 is ready.
> 
> The application is ready.

**Comment by MikkelHegn** [comment] 2016-11-07 17:00
We implemented this feature, because that would often cause us to try to open a webpage that was not ready :-)

I had a round with the engineers, and we have similar logic for other scenarios, where we are less strict in terms of when we will open the page (not only good HTTP codes). We will get that logic into SF in an upcoming release.

**Comment by MikkelHegn** [comment] 2017-10-23 13:00
@dbreshears Was this released and can we close the issue?

**Comment by dbreshears** [comment] 2017-11-01 01:24
@MikkelHegn,  I believe it was quite some time ago,  although we dont' have the stateless webapi template I don't see the issue with .net core 2.0 webapi project.   Closing, re-open if necessary

**Closed by dbreshears** 2017-11-01 01:24 UTC
Labels: fix coming
