### ISSUE TITLE
System.Fabric.FabricObjectClosedException is raised on StateManager.SetStateAsync inside of Actor

### ISSUE THREAD

**Issue by Pisha91** [Azure/service-fabric-issues#106] opened 2016-12-15 09:11 UTC
After few hours of runnig our Aplication in Azure on 5 nodes cluster we are staring to get System.Fabric.FabricObjectClosedException which raised inside of Actors on StateManager.SetStateAsync. We are using Service Fabric Runtime version 5.3.301.9590 and packages version 2.3.311 . In our logs we were able to find next error:

{
  "Depth": 0,
  "ClassName": "System.Fabric.FabricObjectClosedException",
  "Message": "The object is closed.",
  "Source": "System.Fabric",
  "StackTraceString": "   at System.Fabric.Interop.Utility.WrapNativeSyncInvoke[TResult](Func`1 func, String functionTag, String functionArgs)\r\n   at Microsoft.ServiceFabric.Actors.Runtime.KvsActorStateProvider.<>c__DisplayClass14.<Microsoft.ServiceFabric.Actors.Runtime.IActorStateProvider.ContainsStateAsync>b__13()\r\n   at Microsoft.ServiceFabric.Actors.Runtime.ActorStateProviderHelper.<ExecuteWithRetriesAsync>d__6`1.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.ServiceFabric.Actors.Runtime.ActorStateManager.<SetStateAsync>d__e`1.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()\r\n   at Rrd.ActiveDocument.DocumentRepositoryActorService.PageActor.<SaveEncryptedBlocks>d__10.MoveNext() in C:\\Projects\\ActiveDocument\\Backend\\Rrd.ActiveDocument.DocumentRepositoryActorService\\PageActor.cs:line 93\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()\r\n   at Rrd.ActiveDocument.DocumentRepositoryActorService.PageActor.<SetBlocksAsync>d__5.MoveNext() in C:\\Projects\\ActiveDocument\\Backend\\Rrd.ActiveDocument.DocumentRepositoryActorService\\PageActor.cs:line 43",
  "RemoteStackTraceString": null,
  "RemoteStackIndex": 0,
  "ExceptionMethod": {
    "Name": "WrapNativeSyncInvoke",
    "AssemblyName": "System.Fabric",
    "AssemblyVersion": "5.0.0.0",
    "AssemblyCulture": "",
    "ClassName": "System.Fabric.Interop.Utility",
    "Signature": "TResult WrapNativeSyncInvoke[TResult](System.Func`1[TResult], System.String, System.String)",
    "MemberType": 8
  },
  "HResult": -2147017730,
  "HelpURL": null
},
{
  "Depth": 1,
  "ClassName": "System.Runtime.InteropServices.COMException",
  "Message": "Exception from HRESULT: 0x80071BFE",
  "Source": "System.Fabric",
  "StackTraceString": "   at System.Fabric.Interop.NativeRuntime.IFabricKeyValueStoreReplica6.CreateTransaction()\r\n   at System.Fabric.KeyValueStoreReplica.CreateTransactionHelper(KeyValueStoreTransactionSettings settings)\r\n   at System.Fabric.Interop.Utility.WrapNativeSyncInvoke[TResult](Func`1 func, String functionTag, String functionArgs)",
  "RemoteStackTraceString": null,
  "RemoteStackIndex": 0,
  "ExceptionMethod": {
    "Name": "CreateTransaction",
    "AssemblyName": "System.Fabric",
    "AssemblyVersion": "5.0.0.0",
    "AssemblyCulture": "",
    "ClassName": "System.Fabric.Interop.NativeRuntime+IFabricKeyValueStoreReplica6",
    "Signature": "IFabricTransaction CreateTransaction()",
    "MemberType": 8
  },
  "HResult": -2147017730,
  "HelpURL": null
}

**Comment by VipulM-MSFT** [comment] 2017-03-30 08:00
@Pisha91 - This means that this replica got demoted from primary to secondary. The client will re-resolve and reconnect to the new primary if you let the exception bubble up. The existing processing will drain on the primary. I am resolving the issue as "By Design". Please feel free to reopen if you still have question.

**Closed by VipulM-MSFT** 2017-03-30 08:00 UTC
