### ISSUE TITLE
KtlLogger cause BSOD on dev machine

### ISSUE THREAD

**Issue by antonGritsenko** [Azure/service-fabric-issues#587] opened 2017-10-31 09:21 UTC
Hello gents

I have super simple Service Fabric Visual Studio solution with just one stateless service inside (web api service). When I try to debug it with Visual Studio, my machine gets BSOD few seconds after project starts (information from minidump):

> BugCheck E0010001, {fffff8036a3b10e0, fffff8036a3b0f60, 187, 0}
> Probably caused by : KtlLogger.sys ( KtlLogger+1b91d )

The code "0xE0010001" looks like "Memory Allocation Failed" error.

After restart, sometimes a c:\SfDevCluster\Data\_App\_Node_#\MyAppName.AppType_App0\ folder is corrupted (node ID can be different).

Is any way to troubleshoot this case?

**Comment by antonGritsenko** [comment] 2017-10-31 10:00
Additional info: this is really odd, but looks like sign with certificate and\or adding strong name to executable cause this. As soon as I removed both no more BSOD. 
Any ideas?

**Comment by AlanWarwick** [comment] 2017-10-31 21:53
@antonGritsenko ,  When the machine BSOD, does a crash dump get generated ? This would typically be in %windir%\memory.dmp. If you are able to send me a memory dump then it will help to determine the cause of the issue.  This page has information on how to configure your system for this:  https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/enabling-a-kernel-mode-dump-file

Alan

**Comment by AlanWarwick** [comment] 2018-03-17 00:32
Closing since I've not got the dump.  There have been many fixes since October.

**Closed by AlanWarwick** 2018-03-17 00:32 UTC
