### ISSUE TITLE
Service Fabric Explorer (web) Does Not Show LastModifiedUtc of Health Event

### ISSUE THREAD

**Issue by phil000** [Azure/service-fabric-issues#44] opened 2016-09-02 02:45 UTC
When making custom health reports Service Fabric Explorer (web portal) neither updates the "Sequence Number" or the "Source UTC" columns displayed if a report is the same as the previous one. 

Additionally the "LastModifiedUtc" field shown by the Service Fabric Explorer (desktop app) is not show at all.  So the end result is that it *appears* that either the report hasn't been received, or it hasn't been successfully sent.

Be nice to see something changing so it's obvious reports are actually being sent and received on sched.

The desktop explorer exhibits the same behaviour - not updating "SourceUtc" column or "Sequence #" column, but at least the "LastModifiedUtc" column is updated so it is apparent everything is working ok.

From our perspective it'd be nice to see "LastModifiedUtc" in SFX(web) and also a sequence number changing.

**Comment by ms-toddabel** [comment] 2016-09-02 16:41
The TTL issues is known and should be fixed in one of the next releases, as you note the time is incorrect in SFX, but PowerShell queries are correct.

Not seeing changes in reports for the exact same report is by design (sequence number and report time are excluded in determining equality). In the article https://azure.microsoft.com/en-us/documentation/articles/service-fabric-health-introduction/ it is mentioned that "For the same entity, there is only one report for the same source and property." and while the reports are updated in memory, they are not persisted to reduce the impact of health on system performance. If you make a change to a field, for instance description, you'll see changes in both PowerShell and SFX. If you are reporting the same thing each time, you won't see changes.

**Closed by ms-toddabel** 2016-09-02 16:41 UTC

**Comment by phil000** [comment] 2016-09-03 21:25
What did you think about adding "LastUPdateDate" as the desktop SFX shows, or ReceivedAt as Powershell has? It's disconcerting to see nothing changing when routine reports are happening. For now we've added a date-time into the description.
