### ISSUE TITLE
Updating Microsoft.VisualStudio.Azure.Fabric.MSBuild to 1.5.0

### ISSUE THREAD

**Issue by eliasnawfal** [Azure/service-fabric-issues#206] opened 2017-03-23 16:52 UTC
Using VS 2017 if update Microsoft.VisualStudio.Azure.Fabric.MSBuild to 1.5.0 in my fabric project build fails giving errors
![image](https://cloud.githubusercontent.com/assets/15719103/24259548/e0015bc6-0ff9-11e7-8463-2615957441d8.png)

**Comment by sondreb** [comment] 2017-03-23 18:27
Appears to be a bug with upgrading the .sfproj files to 1.5, how to reproduce: Create a new empty project with a stateless service, go to manage nuget packages, upgrade the 4 packages, and you will get "OutputPath property not set"...

It does not upgrade the sfproj to 1.5 paths.

Then close solution, and you will see this message repeatedly until you press "No".

Press No, then unload and manually edit the sfproj, changing 1.4 in the paths to 1.5. Must be changed in 4 places.

I have reproduced this on two different computers and with one existing project and two new projects, neither upgrades the sfproj properly to new msbuild 1.5 tasks.

The dialog that repeats after closing and opening an upgraded project:

![image](https://cloud.githubusercontent.com/assets/309938/24263878/cd923fbe-0ffe-11e7-9fa5-f069f09362b3.png)

**Comment by vturecek** [comment] 2017-03-23 19:37
@sondreb Is that in VS 2017 or 2015?

**Comment by steve-torchia** [comment] 2017-03-23 19:38
Seeing the same thing in VS2017 after installing the new sdk and updating the nuget packages

**Comment by Vlad-EE** [comment] 2017-03-23 19:41
Me too! VS2017, latest SDK. 
In addition to the build issues, I also see the Null Ref exception when reloading the solution. Here is the description from the log file:
=====================
3/23/2017 3:05:40 PM
Recoverable
System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.VisualStudio.Azure.Fabric.ApplicationProject.ProjectSystem.PackageRestoreManager.<InitializeAsync>d__20.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.ProjectSystem.UnconfiguredProjectImpl.AutoLoadMethodStateMachine.<<StartExecution>b__8_0>d.MoveNext()
===================

**Comment by nrandell** [comment] 2017-03-23 21:34
Is the expected behaviour when creating a new solution to have the old packages in? All the previous SDKs have created new projects with the latest libraries in.

I'm using VS2017 and have installed the latest SDK. I think this is related to the this issue.

**Comment by dbreshears** [comment] 2017-03-23 21:49
Unfortunately right now the tooling in VS 2017 is still 1.4 but should work against the latest 5.5 / 2.5 SDK.    1.4 tooling will require the 1.4 Microsoft.VisualStudio.Azure.Fabric.MSBuild Nuget package.    The next update of VS2017 coming soon will have the new 1.5 tooling included.

**Comment by nrandell** [comment] 2017-03-23 21:53
Thanks for the update @dbreshears  - is it possible to update the release notes for the SDK to mention this? One reason for installing it so quickly was that it indicated VS2017 was fully supported. Just a small clarification is probably ok.

**Comment by dbreshears** [comment] 2017-03-23 22:04
@nrandell .  Thanks for the feedback.   Yes,  Looks like it could be more clear on the what the current version of the tooling is in VS 2017 and then what version will be in the next update.

**Comment by nrandell** [comment] 2017-03-23 22:22
Thanks for listening @dbreshears  - one other comment that may help would be to provide some early visibility of things changing. I noticed that my azure cluster was upgraded last week, some nuget packages being updated yesterday and then the post today. Yet I had no real idea what was in the changes.

Would it be possible to provide notice of the upgrade about to happen, provide some details about it including a timeline of when things should happen.

Of course, this will all become more transparent once more of ServiceFabric becomes open sourced like lots of other Microsoft technologies!

**Comment by sondreb** [comment] 2017-03-24 09:29
@nrandell I can't speak for Microsoft ;-) But from what I can remember, they won't give advance notice on the upgrades for clusters, the option you have is to configure it to manual upgrades and only upgrade after you know the changes. Their release notes are often good I think, compared to other teams and projects at Microsoft.

Download the Word document at the bottom here: https://azure.microsoft.com/en-us/blog/announcing-azure-service-fabric-5-5-and-sdk-2-5/

We use auto for demo/dev clusters and manual for production.

**Comment by MikkelHegn** [comment] 2017-08-28 19:00
Current versions are documented here: https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-get-started#install-the-sdk-and-tools

**Closed by MikkelHegn** 2017-08-28 19:00 UTC
Labels: doc follow-up
