### ISSUE TITLE
Debugging of ServiceFabric Projects not working since Visual Studio 15.8.0

### ISSUE THREAD

**Issue by markusitd** [Azure/service-fabric-issues#1234] opened 2018-08-20 08:53 UTC
Since the update to Visual Studio 15.8.0 I cannot debug Service Fabric Projects anymore.

The debugger stops with an error in the powershell publish script:

```
C:\<path to service fabric project>\pkg\Debug\ApplicationManifest.xml is not found.
In C:\Program Files\Microsoft SDKs\Service Fabric\Tools\PSModule\ServiceFabricSDK\Utilities.ps1:166 Zeichen:9
+         throw "$ApplicationManifestPath is not found."
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (C:\VANProjekt\B...l is not found.:String) [], RuntimeException
    + FullyQualifiedErrorId : C:\<path to service fabric project>\pkg\Debug\ApplicationManifest.xml is not found.
```
I checked the folder and it is no longer created by Visual Studio. Maybe the folder structure has been changed with 15.8.0?
Is there a way to provide the Powershell script with a different $ApplicationManifestPath to point it to the actual Debug folder?

**Comment by MedAnd** [comment] 2018-08-20 12:37
Is this issue a duplicate of #1228

**Comment by markusitd** [comment] 2018-08-20 13:51
I'm not sure. They are related because both struggle with the missing pkg folder. #1228 does not have a problem with the ApplicationManifest but with something else though.

**Comment by markusitd** [comment] 2018-08-23 08:02
Hello ravipal,

- MSBuild Version is 1.6.7
- the pkg Folder does not exist, it won't be created during build anymore

The detailed log does not add anything to the debug output.

**Comment by ravipal** [comment] 2018-08-23 15:04
The output log has the following error
"3>Object reference not set to an instance of an object."

This is duplicate of #1228

**Comment by ravipal** [comment] 2018-08-23 17:28
To confirm it is the same issue, update the servicemanifest that uses https protocol to http and you shouldn't hit the "Object reference not set to an instance of an Object" error.

**Comment by dbreshears** [comment] 2018-08-28 23:45
@markusitd ,  15.8.2 has released now.

**Closed** 2018-08-29 07:52 UTC
