### ISSUE TITLE
Reverse Proxy and HTTP 302

### ISSUE THREAD

**Issue by mkosieradzki** [Azure/service-fabric-issues#112] opened 2016-12-22 12:31 UTC
In the current reverse proxy implementation proxy resolves HTTP 302 redirects instead of forwarding them to the client. Is this behavior by design or is it a bug?

**Comment by lbogdanov** [comment] 2017-01-05 23:06
I attempted to put IdentityServer3 into a cluster and painfully realized that normal OAuth2 redirects do not reach clients and get handled by the proxy. Looks as a nasty bug to me, even if by design :) !

**Comment by mkosieradzki** [comment] 2017-01-09 12:02
@lbogdanov I had similar issue with my OAuth2 endpoint and I have ended up with creating a middleware translating 302 into 200 with additional my-invented-header. I have an additional internet-facing proxy which translates this header back into proper 302.

However I would definitely prefer simple 302 forwarding or a special Reverse Proxy-handled header like for 404 (in case 302 is required for some internal purposes like failover).

**Comment by lbogdanov** [comment] 2017-01-09 14:53
Thanks for sharing! I agree, that should be handled properly by the reverse proxy itself. I wouldn't mind having extra middleware to let the 302 go through the proxy if necessary, but for now will have to invent something just like you did as a workaround.
@MSFT -  can you please review and provide a solution (maybe there is one already that we are not aware of)?

**Comment by BharatNarasimman** [comment] 2017-01-09 18:48
@mkosieradzki , @lbogdanov, Does the location being redirected to include the service name in the format the reverse proxy expects?

**Comment by mkosieradzki** [comment] 2017-01-09 19:24
@BharatNarasimman I did most of tests using relative urls. However I am **quite** sure that I had this issue also when using fqdns outside of the reverse proxy range (but I am not sure whether my httpclient was properly configured back then).

**Comment by lbogdanov** [comment] 2017-01-09 19:26
@BharatNarasimman  Yes, it does. The response code is 302 and the Location header points to the service in the SF format, In my case the application name is AuthServer, service name is Sts:
    "Location": [
      "http://localhost:19081/AuthServer/Sts/login?signin=d7c192bbd112efa41c9af3f0cb6495bb"
    ],

**Comment by BharatNarasimman** [comment] 2017-01-09 22:41
@lbogdanov . that looks correct assuming the client is running on the same machine. Just to be sure, what is the error you get when accessing the uri http://localhost:19081/AuthServer/Sts/login?signin=d7c192bbd112efa41c9af3f0cb6495bb from your client?

**Comment by lbogdanov** [comment] 2017-01-09 23:39
@BharatNarasimman Yes, the client is on the same machine. The client is a js SPA trying to authenticate. I'm not sure what exactly is happening inside the client/browser, but when the client eventually gets 200 from the proxy (after proxy negotiated the redirects for it), the app/browser starts thinking it's own origin is localhost:19081/AuthServer/Sts and begins loading resources from that location, which is wrong and leads to  the time out. 
The setup is working correctly if I bypass SF proxy and go to the service directly, or if i use a different proxy (Apache web server). The only noticeable difference between the configurations -  SF proxy handles redirects internally.

**Comment by mkosieradzki** [comment] 2017-01-10 02:29
@BharatNarasimman OK. I have tripple checked this.
1. My client has - so NO redirect is not resolved by client:
```
private static readonly HttpClient httpClient = new HttpClient(new HttpClientHandler { AllowAutoRedirect = false });
```
2. I have tried:
relative urls -> handled by reverse proxy
absolute urls from my application (but not proxy) -> handled by proxy (504 actually)
completely safe absolute urls: https://google.com -> handled by proxy

So I am 99% sure the issue is on your side.

**Comment by mkosieradzki** [comment] 2017-01-10 02:42
@BharatNarasimman BTW. If you want to disallow reasonable front-resolved relative redirects you definitely need to fix #113 to allow reasonable and predictable absolute redirect url computation.

**Comment by joye-ramone** [comment] 2017-02-10 17:22
Any updates about this issue or any way how to workaround it?
We also faced same problem with SPA that setting in SF and our corporate IdentityServer4.
Basically SPA cannot redirect to IdentityServer4 login page and this makes whole application unusable...

**Comment by mkosieradzki** [comment] 2017-02-10 17:36
@joye-ramone 
I have a small workaround middleware library for this. I am considering open-sourcing it if this issue is not being solved.

It has two middlewares:
First one:
1. It replaces host and path in the request to X-Forwarded-Host etc.
2. Executes other middlewares and on completion it detects 301 and 302 responses translates it to 200 response with my custom headers.
3. As a bonus it detects 404 status code and adds X-ServiceFabric : ResourceNotFound

Second one:
Proxy middleware that does proxying to the Reverse Proxy and detects some specific responses including my custom headers and translates them back to 301 and 302.

**Comment by BharatNarasimman** [comment] 2017-02-10 17:38
This is a bug in the reverse proxy. We are working on fixing it.

**Comment by mkosieradzki** [comment] 2017-02-10 17:39
@BharatNarasimman Thanks :). Any ETA?

**Comment by joye-ramone** [comment] 2017-02-10 18:03
@BharatNarasimman Thank you for update! Will wait for fix,

@mkosieradzki sounds interesting! I still hope that issue will be fixed, but it would be nice to have a workaround for this.

**Comment by gauravhub** [comment] 2017-02-14 23:23
We are looking for a workaround for this issue as well...This is blocking our Identity Server deployment. Please advise

**Comment by elandsberg** [comment] 2017-03-07 16:52
Any update on this issue, as I've also stumbled across it

**Comment by GeneralXception** [comment] 2017-03-07 23:28
For search engine purposes - this bug causes an issue with Swashbuckle / Swagger UI when accessing the Swagger UI via the Reverse Proxy. It will only happen when accessing Swagger UI from the shortcut route `<root>/swagger` because Swashbuckle issues a 302 when that route is accessed and it tries to redirect the client to `<root>/swagger/ui/index`.  Unfortunately, the 302 gets swallowed by the proxy, the client hangs for 60 seconds waiting for a timeout and nothing happens apart from minor hair loss.

If you go direct to the `<root>/swagger/ui/index` location it works fine, but I never realised that the problem was just with the 302 being dropped, I assumed none of the Swagger UI was working until I saw this bug.

@BharatNarasimman do you have any updates on this bug?

**Comment by VipulM-MSFT** [comment] 2017-03-08 19:20
Sorry for the delay we are working through testing the changes and make them available as soon as possible.

**Comment by kellteen** [comment] 2017-03-13 10:02
Thx @BharatNarasimman @VipulM-MSFT we are eagerly awaiting the fix :-) Any updates on the progress for deployment would be appreciated so we know what steps to take near-time

**Comment by VipulM-MSFT** [comment] 2017-03-13 21:49
@kellteen  - The fix is complete, but it is still not being rolled out. We sincerely apologize that this is taking longer than it should. We will update the thread when we know the deployment it is part of.

**Comment by gauravhub** [comment] 2017-03-21 20:19
@VipulM-MSFT Can you please confirm if this is fixed in 5.5.216.0?

**Comment by VipulM-MSFT** [comment] 2017-03-21 20:34
@gauravhub - it is not. It is in the builds > 219. We are working on the mechanisms to provide on-demand QFE/CU updates for specific issues. This will be part of that. We will soon be able to update how you can get to it.

**Comment by VipulM-MSFT** [comment] 2017-03-24 18:19
@gauravhub We build 5.5.219 is available as a manual upgrade for Azure Clusters. The clusters that are set to "Automatic" upgrade will get this or a build newer than this at the next rollout in few weeks.

**Comment by gauravhub** [comment] 2017-03-27 21:45
@VipulM-MSFT...Thanks for update

**Closed** 2017-05-19 00:39 UTC
Labels: bug

**Comment by hiraldesai** [comment] 2017-06-16 22:28
Has anyone been able to run swagger UI behind a SF reverse proxy since this update? I'm having a similar issue where I can access the swagger.json through reverse proxy but can't access swagger ui. This is my configuration.

```
        public static void UseSwaggerWithOptions(this IApplicationBuilder builder, string title, string apiSuffix, string version = "v1")
        {
            builder.UseSwagger(options => options.RouteTemplate = "docs/{documentName}/swagger.json");
            builder.UseSwaggerUI(c =>
            {
                c.RoutePrefix = $"{Constants.ServiceFabric.AppName}/{apiSuffix}/docs";
                c.SwaggerEndpoint($"/docs/{version}/swagger.json", $"{title} {version}");                
            });
        }
```

I can access `http://localhost:19081/My.SF.AppName/My.Stateless.Api/docs/v1/swagger.json` but the UI doesn't load when I try to access `http://localhost:19081/My.SF.AppName/My.Stateless.Api/docs`

**Comment by masnider** [comment] 2017-06-19 22:35
Hi @hiraldesai  - can you open a separate issue for this?

**Comment by hiraldesai** [comment] 2017-06-23 16:52
@masnider - done. https://github.com/Azure/service-fabric-issues/issues/327

**Comment by masnider** [comment] 2017-06-23 18:04
@hiraldesai great! We'll take it up over there. Thanks!
