### ISSUE TITLE
Unreasonably large value for 'Lease slow send completion' warning

### ISSUE THREAD

**Issue by mkosieradzki** [Azure/service-fabric-issues#544] opened 2017-10-17 17:19 UTC
`Unhealthy event: SourceId='System.Federation', Property='Duration_<myipprefix>.7:1026', HealthState='Warning', ConsiderWarningAsError=false.
Lease slow send completion <myipprefix>.5:1026 -> <myipprefix>.7:1026, lease transport is taking 611289640ms to send and receive message.` 

611289640ms - this does not look like miliseconds - it should be something else.

BTW. The trigger for this warning is replacement of cluster certificate.

states:
primary: OldThumbprint
secondary: OldThumbprint
->
primary: NewThumbprint
secondary: OldThumbprint
->
primary: NewThumbprint
secondary: NewThumbprint

during last step transition I've started to receive this warning. (runtime 6.0.211) which may be a second issue.

**Comment by jeffreychenmsft** [comment] 2017-10-20 23:29
Thanks for your issue report.
Would you be able to send us the traces to investigate the issue?

**Comment by mkosieradzki** [comment] 2017-10-20 23:34
I think so. However not sure if those traces are still there as I have today upgraded 6.0.211 to 6.0.219, but I can try :) which traces and where I should send them?

**Comment by jeffreychenmsft** [comment] 2017-10-21 04:08
Could you [create a support request](https://portal.azure.com/?#blade/Microsoft_Azure_Support/HelpAndSupportBlade)? Someone will guide you through the process. Thanks.

**Comment by mkosieradzki** [comment] 2017-10-21 10:25
Done: 117102116532309

**Comment by hravnaas** [comment] 2017-10-23 16:37
I also started seeing this just this morning, in two separate test clusters. For both clusters, I changed MaxDiskQuotaInMB from 10240 to 5120 and updated the cluster config via a PowerShell call to Start-ServiceFabricClusterConfigurationUpgrade.

**Comment by plraustin** [comment] 2017-10-25 00:06
I just upgraded to 6.0.219.9494 and every node in the cluster is reporting this warning.


    Unhealthy event: SourceId='System.Federation', Property='Duration_servernameB:19002', HealthState='Warning', ConsiderWarningAsError=false.
Lease slow send completion servernameA:19002 -> servernameB:19002, lease transport is taking 1027009453ms to send and receive message.

**Comment by Eneuman** [comment] 2017-10-26 19:20
This is hapening to us aswell now.
Running  version 6.0.219.9494

**Comment by hiraldesai** [comment] 2017-10-26 19:58
We just experienced similar warning messages on some of our nodes which resulted in service degradation. We have opened a ticket with Azure to dig into details for it. In our case it looks like it's related to an Azure storage outage for West US as per [Azure status page](https://azure.microsoft.com/en-us/status/) showing the below message around the same time. When I RDPed to one of the nodes, it was showing that it had restarted. I will share more information when it's available to me.


> Starting at 16:45 UTC on 26 Oct 2017 a subset of customers using Storage in West US may experience difficulties connecting to resources hosted in this region. Virtual Machines hosted in this region may also experience unexpected reboots. Engineers have determined that this is caused by an underlying Storage incident which is under investigation. Other services that leverage Storage in this region may also be experiencing impact related to this and impacted services will be listed on the Azure Status Health Dashboard. Engineers have identified a possible fix for the underlying cause, and customers should start seeing signs of mitigation. The next update will be provided in 60 minutes, or as events warrant.

**Comment by plraustin** [comment] 2017-10-26 20:00
We’re getting this with our on-premises cluster – so I doubt it is related to Azure storage outage…

**Comment by yltor** [comment] 2017-10-26 21:36
To clarify, this health report indicates there is network glitch and messages may take unusually longer to deliver. It doesn't mean there is any issue in Service Fabric logic. In most cases, it should not affect the cluster or service operation unless there are large number of alerts at the same time.

**Comment by mkosieradzki** [comment] 2017-10-26 21:38
@yltor I am reporting only wrong units in the error message, nothing else.

**Comment by jahmai** [comment] 2017-10-26 21:53
@yltor My application has node behaviour based on the health status of a node, so this long running Warning status is an issue.

It also affects all 5 of our nodes in the cluster ar once which effectively takes some of our functions that rely on healthy nodes offline.

This also happens in clusters in multiple regions.

The warning also states delays up to 20 seconds.

This also cooncides with other types of monitoring alarms as it seems to cause some inbound http requests to be highly latent.

My support case currently wants network traces foe the affected machines which I am now gathering.

This is a serious issue and needs to be treated as such.

**Comment by hiraldesai** [comment] 2017-10-26 21:55
@plraustin - I'm guessing there could be multiple things that could be resulting in the same error message?

@yltor - for us, 2/3 vm scalesets (10/15 nodes) went into warning state. We saw massive degradation in performance, from <1s load times to ~20-30s load times for about an hour or so before the cluster recovered from it.

**Comment by yltor** [comment] 2017-10-26 22:07
@jahmai @hiraldesai We treat this issue with high priority and @jeffreychenmsft is actively working on it.

**Comment by hiraldesai** [comment] 2017-10-26 22:12
No problems @yltor, Thank you! I'm not trying to rush or anything, just curious about the root cause. If anyone from your team needs any additional details, feel free to ping me on MSFT Skype.

**Comment by jeffreychenmsft** [comment] 2017-10-26 22:13
@hiraldesai It might be some other reasons that caused the slow performance and also caused this warning to show up, not that this warning caused the slow performance. This is just a network latency measure warning. It does not change the cluster behavior. You could override this warning, but the cluster still suffers from the slowness.

**Comment by hiraldesai** [comment] 2017-10-26 23:59
Ohh - maybe I'm just confusing the Azure's West US storage outage resulting in node reboots to this warning. Are you absolutely certain these two cannot be related to each other?

**Comment by francescocristallo** [comment] 2017-11-08 19:11
Same problem today on a 10 machines node on Service Fabric Cluster version 6.0.219.9494 using the SDK 2.18.219 on Windows Server 2016 Datacenter-Server-Core.

**Comment by bcox24** [comment] 2018-01-10 01:31
Did this issue get resolved in the latest release of Service Fabric? We have our cluster set to manual upgrade and still receive this warning on a regular basis.  @jeffreychenmsft do you know the answer?

**Comment by jeffreychenmsft** [comment] 2019-10-24 17:56
Yes, this was fixed in the newer version.

**Closed** 2019-10-24 17:56 UTC
