### ISSUE TITLE
MSBuild target Package does not include all files

### ISSUE THREAD

**Issue by michjuh** [Azure/service-fabric-issues#771] opened 2018-01-18 13:05 UTC
Hello all, 
I have a simple class library project where I included a couple resource (.resx) files and when I package my service fabric app with Visual Studio those resources are compiled into separate dll's per culture. For example: _MyApp\pkg\Debug\MyServicePkg\Code\nl-BE\EDoc.resources.dll_

This is my expected output, this works. 

Quote Microsoft docs:
> It is also possible to programmatically package up your application using msbuild.exe. Under the hood, Visual Studio is running it so the output is same.
`$ D:\Temp> msbuild HelloWorld.sfproj /t:Package`

Unfortunately the output is not the same; I am missing my *.resources.dll's. When I look in the /bin folders of these class libraries those dll's are indeed generated but they are not copied over to the /pkg folder. 

Has someone experienced any similar issues? I don't often work with resx files so my issue may not be directly related to service fabric... 

Thank you

**Comment by michjuh** [comment] 2018-01-19 20:15
For what it's worth I'm currently using a workaround where it will look for those dll's and move them over to the package folder when packaging is finished. 

This is accomplished by adding an AfterPackage target to your sfproj file:

```xml
<Target Name="AfterPackage" AfterTargets="Package">
  <Copy SourceFiles="..\MyService\bin\$(Platform)\$(Configuration)\nl-BE\EDoc.resources.dll" DestinationFolder="$(PackageLocation)\MyServicePkg\Code\nl-BE\"/>
</Target>
```

This works for now but I was expecting the Package target to do this for me, especially because packaging the app with Visual Studio doesn't have this issue. I'm still very interested in knowing why this is and how I'm supposed to do it properly. Thx

**Comment by masnider** [comment] 2018-01-26 17:50
Hi @michjuh, this looks like it is probably a dupe of https://github.com/Azure/service-fabric-issues/issues/412 Can you take a look there?

**Comment by ravipal** [comment] 2018-03-08 21:00
The nuget package (1.6.4) has the fix. Please add the property \<PackageOutputFolder>true\</PackageOutputFolder> to *.sfproj to change the package behavior that will include all the files from output folder.

**Closed by ravipal** 2018-03-08 21:00 UTC
Labels: bug, fix coming
