### ISSUE TITLE
FabricRuntime.GetActivationContext() event handlers do not fire.

### ISSUE THREAD

**Issue by aiden56** [Azure/service-fabric-issues#493] opened 2017-09-28 18:20 UTC
If using the ```ServiceContext``` activation context to register event callbacks, the event handler for ```ConfigurationPackageModifiedEvent``` fires correctly. If using the ```FabricRuntime.GetActivationContext()``` activation context to register callbacks, the  ```ConfigurationPackageModifiedEvent``` does not fire.

**Comment by harahma** [comment] 2017-11-01 21:03
You will need to store a reference to activation context object returned from FabricRuntime.GetActivationContext() to register and unregister the callback. Otherwise object is destroyed when it goes out of scope.

**Comment by masnider** [comment] 2018-01-03 22:51
@aiden56 Did this work for you? I've seen this happen a couple of times in my own code. Since we haven't heard from you in a while and since I've confirmed that this is a fix, I'm going to close out this issue for now. If you have other questions or any further problems with this, you can just reopen this issue or file a new one. Thanks!

**Closed by masnider** 2018-01-03 22:51 UTC
Labels: investigating
