### ISSUE TITLE
CollectServiceCodeFiles MSBuild task produces the wrong packaging assemblies

### ISSUE THREAD

**Issue by jahmai** [Azure/service-fabric-issues#91] opened 2016-11-18 11:22 UTC
In Microsoft.VisualStudio.Azure.Fabric.Application.targets, the target CollectServiceCodeFiles produces a list of assemblies to be copied to the application package.

One of the steps uses MSBuild on the service project to produce a very large list of output items under the property OutputGroupsDependencies. This list includes service project outputs, direct and indirect dependencies.

When referencing NETStandard nuget packages, OutputGroupsDependencies can contain references to both nuget and framework versions of the same assembly, in my case System.Xml.ReaderWriter.dll:

```
C:\{snip}\packages\System.Xml.ReaderWriter.4.3.0\lib\net46\System.Xml.ReaderWriter.dll
C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.6\Facades\System.Xml.ReaderWriter.dl
```

The task then reduces this list using the following to produce a list of files to be copied to the package output folder:

```
    <ItemGroup>
      <CopyLocalDependencies Include="@(OutputGroupsDependencies)" Condition="Exists('$(ProjectTargetDir)%(Filename)%(Extension)')" />
    </ItemGroup>
```

Since this test only checks if the filename and extension exist in the service project output path, and the nuget package reference to System.Xml.ReaderWriter users CopyLocal (as it should), the test also passes for the framework version of System.Xml.ReaderWriter, which means CopyLocalDependencies will contain both of these versions.

In my case, since the order of the items is nuget;framework, the framework version gets copied last, and since it is only a stub and not a full assembly, actually breaks the application at runtime when it is loaded.

This could happen for any assembly that is referenced twice by the same assembly name from different paths, but would be most likely for nuget and framework versions of .net assemblies.

**Comment by jahmai** [comment] 2016-11-18 11:38
The workaround was to add the dll to the project as a Content item marked Copy Always which seems to ensure it's copied last. A bit hacky but it'll do for now.

**Comment by MikkelHegn** [comment] 2016-11-21 16:50
Duplicate of: https://github.com/Azure/service-fabric-issues/issues/54

**Closed by MikkelHegn** 2016-11-21 16:50 UTC
Labels: duplicate
