### ISSUE TITLE
ResourceOverrides switching HTTPS to HTTP fails 

### ISSUE THREAD

**Issue by eliasnawfal** [Azure/service-fabric-issues#505] opened 2017-10-03 16:12 UTC
ResourceOverrides gave us the ability to change protocol per environment.

`    <ResourceOverrides>
      <Endpoints>
        <Endpoint Name="ServiceEndpoint" Port="[PORT]" Protocol="[PROTOCOL]" Type="Input" />
      </Endpoints>
    </ResourceOverrides>`

In Dev environment, we want to use HTTP and on production, we want to use HTTPS. Setting the protocol to Http while 

`    <Policies>
      <EndpointBindingPolicy EndpointRef="ServiceEndpoint" CertificateRef="CERT_NAME" />
    </Policies>`

`  <Certificates>
    <EndpointCertificate X509FindValue="[CERT_THUMB]" Name="CERT_NAME" />
  </Certificates>`

are present leads to deployment failure with error

> The EndpointRef 'ServiceEndpoint' in EndpointBindingPolicy is invalid. There is 
no matching Resource in the corresponding ServiceManifest.

How can I use ResourceOverrides to apply HTTP and disable the specified Cert for other environments that use HTTPS?

**Comment by farukkhan** [comment] 2017-10-05 04:14
Seems you have to update the SDK...https://github.com/Azure/service-fabric-issues/issues/447

**Comment by eliasnawfal** [comment] 2017-10-06 11:15
@farukkhan I already updated SDK and ResourceOverrides is working, but when you have a CertBinding to a HTTPS  Endpoint and you want to change it to HTTP using ResourceOverrides deployment fails.

**Comment by eliasnawfal** [comment] 2017-10-12 15:27
@harahma 
[PackageRoot.zip](https://github.com/Azure/service-fabric-issues/files/1379791/PackageRoot.zip)

The case is that I have on Staging, PROD https and on Dev http.
I'm deploying App using PS and I'm sending parameters
Port= 80,
Protocol=http
S__CERT_THUMB = ""

Instead of https, the Cert Binding will make deployment fail.
Why not ignore Cert if protocol is Http

**Comment by tugup** [comment] 2017-10-18 00:16
@eliasnawfal  your port in the ServiceManifest is specified as http. It should be https if you have a corresponding endpointBinding in the application manifest. That is why you are hitting the error. 
Even if you donot use the overrides ServiceFabirc will still throw this error as it expects the endpoint specified by the EndpointRef to be an https endpoint. 

Please change the it to https.

**Comment by pwiens** [comment] 2017-10-24 18:24
@tugup I think the problem is that there currently doesn't appear to be an easy way to make the local cluster use http and production use https. Forcing https for local cluster is annoying because you end up having to manage self-signed certs that you need to share with the whole dev team. I think what @eliasnawfal is asking is for a way to remove the EndpointBindingPolicy entirely for certain environments.

**Comment by alexgman** [comment] 2017-11-20 21:20
I'm having the same issue as described. I don't know what you meant by "Forcing https for local cluster", but we are unable to switch to http when there is a certificate.

**Comment by sondreb** [comment] 2018-03-07 12:17
I get the same error on release from VSTS, have not used ResourceOverrides before and attempted to use it, but it appears that the EndpointBindingPolicy is unable to find the resource when used in combination with ResourceOverrides?

**Comment by tugup** [comment] 2018-03-07 18:40
Will need to investigate for a possible fix for this.

**Comment by vmendi** [comment] 2018-03-09 20:15
This also bit us. 

It forces us to install a self-signed ssl cert in every development machine which adds friction. We don't care about testing encryption when we are on local development.

**Comment by wkotesh** [comment] 2018-03-27 19:46
any update on this issue?

**Comment by jothipandiyan-bizruntime** [comment] 2018-05-20 07:11
Any suggestions to make this work.
Local (dev environment)-> http
Cloud (Prodcution environment) -> https

**Comment by tugup** [comment] 2018-05-21 19:29
I am making a fix to support this. Will update the release info.

**Comment by abatishchev** [comment] 2018-06-01 06:55
When this is expected to be available? In 6.2.283 I'm still getting this error. So either certificate or http.

**Comment by tugup** [comment] 2018-06-01 17:22
release 6.4

**Comment by jothipandiyanjp** [comment] 2018-09-11 17:58
When will be the approx release date of 6.4 version??

**Comment by podgito** [comment] 2018-12-04 14:13
@tugup v6.4 has been released. I don't see anything mentioned about this in the release notes. https://blogs.msdn.microsoft.com/azureservicefabric/2018/11/30/azure-service-fabric-6-4-release/

**Comment by tugup** [comment] 2018-12-04 18:56
This should be fixed in 6.4. My apologies as the release notes might be missing the update.

**Comment by jothipandiyanjp** [comment] 2018-12-06 17:50
@tugup, When this is expected to be available?

**Comment by jothipandiyanjp** [comment] 2019-10-01 04:07
Hi, any update on this issue?

**Comment by tugup** [comment] 2019-10-01 17:36
Have you tried 6.4 release. As mentioned this has been fixed in 6.4 release.

**Comment by tugup** [comment] 2019-10-01 20:37
Closing the issue since already fixed. Please reach out if you run into issues.

**Closed by tugup** 2019-10-01 20:37 UTC
Labels: enhancement, question

**Comment by jothipandiyanjp** [comment] 2019-10-02 05:31
Hi, I am getting this error...

FABRIC_E_IMAGEBUILDER_VALIDATION_ERROR: The Endpoint resource ServiceEndpoint2 associated specified in EndpointBindingPolicy must have https protocol
FileName: C:\SfDevCluster\Data\ImageBuilderProxy\AppType\284b65ae-f09b-4df1-a8dc-9776a2b20130\ApplicationManifest.xml


  <Resources>
    <Endpoints>
      <Endpoint Protocol="tcp" Name="ServiceEndpoint2" Type="Input" Port="9393"  CertificateRef="HttpsCert"/>
    </Endpoints>
  </Resources>

in local.xml I am setting this property,
       <Parameter Name="Protocol" Value="http" />

in local.xml, cloud.xml  I am setting this property,
       <Parameter Name="Protocol" Value="https" />

in application manifest,
       <Policies>
      <EndpointBindingPolicy EndpointRef="ServiceEndpoint2" CertificateRef="HttpsCert" />
    </Policies>

because of this endpoint ref i am getting this error..

**Comment by jothipandiyanjp** [comment] 2019-10-02 06:04
To work around this issue, 
I have added     < Parameter Name="IsHttps" Value="false" / >

In service manifest:
  < Resources >
< Endpoints >
< Endpoint Protocol="http" Name="ServiceEndpoint1" Type="Input" Port="9393" / >
< Endpoint Protocol="https" Name="ServiceEndpoint2" Type="Input" Port="9393" CertificateRef="HttpsCert"/ >
< /Endpoints >
< /Resources >


and in code  I am checking, 

                   var protocolConfigured = GetConfig.GetConfiguration(serviceContext,"isHttps");
                    bool isHttps = false;
                    Boolean.TryParse(protocolConfigured,out isHttps);
                     var endpointName = isHttps?"ServiceEndpoint2":"ServiceEndpoint1";
                     return  new KestrelCommunicationListener(serviceContext, endpointName, (url, listener)

**Comment by tugup** [comment] 2019-10-02 17:56
Can you share your Application and Service Manifests?

**Comment by jothipandiyanjp** [comment] 2019-10-03 06:16
[service manifest.txt](https://github.com/Azure/service-fabric-issues/files/3684676/service.manifest.txt)
[app manifest.txt](https://github.com/Azure/service-fabric-issues/files/3684678/app.manifest.txt)

**Comment by tugup** [comment] 2019-10-03 17:44
The manifests that you shared and the error seems different. Did you change them?

Are you trying to override from https to http?

Please read the article on how to override endpoints? [https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-service-manifest-resources#overriding-endpoints-in-servicemanifestxml
](url)

Few things you need to change for Protocol Override to work. 

1. In the ApplicationManifest along with Port you need to add Protocol too. That's how override work.

    <ResourceOverrides>
      <Endpoints>
        <Endpoint Name="ServiceEndpoint2" Port="[Port]"  **Protocol="http"**/>
      </Endpoints>
    </ResourceOverrides>

2. The CertRef attribute in the ServcieManifest is not supported. <Endpoint Protocol="https" Name="ServiceEndpoint2" Type="Input"  **CertificateRef="HttpsCert"**  Port="9040" />
Remove the attribute. If you want to specify the cert for your endpoint as mentioned in this article [https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-service-manifest-resources#example-specifying-an-http-endpoint-for-your-service](url) use the EndpointBindingPolicy.


If you have questions fell free to revert back.
